### ISSUE TITLE
tunl0 device present inside containers

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calicoctl#1010]
I started a k8s cluster with the calico-k8s-scale GCE scripts, which enable IPIP.  Then I ran a test pod using kubectl:

```
kubectl run -i --tty busybox --image=busybox --restart=Never`
```

Running `ip link` inside the pod showed 

```
# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop 
    link/ipip 0.0.0.0 brd 0.0.0.0
31: eth0@if32: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue qlen 1000
    link/ether ca:7b:89:d7:3a:5a brd ff:ff:ff:ff:ff:ff
    inet 192.168.255.200/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::c87b:89ff:fed7:3a5a/64 scope link 
       valid_lft forever preferred_lft forever
```

It seems odd that the `tunl0` device is present.  I couldn't seem to do anything with it (adding IPs was blocked, for example) but maybe someone with more knowledge could force a packet out of it or otherwise reconfigure it. 

I suspect the tunl0 device simply pops up in every namespace rather than us having accidentally put it in there.

**Comment by caseydavenport** [comment]
I think this is just an artifact of how some linuxes work, rather than a problem with Calico.
