### ISSUE TITLE
Make "dummy next hop" configurable

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calicoctl#1024]
Make the address we use as our container gateway configurable.  Some users may want / need a different address here.

See here: https://github.com/projectcalico/libcalico/blob/ff531d018879f7b37a40a85a6df8390590172964/calico_containers/pycalico/netns.py#L220

**Comment by tomdee** [comment]
Does anyone have any thoughts about how this should be configured? Maybe in the network config when using CNI, and a label when using libnetwork? What about when using `calicoctl container add` - does it need to be added as an option there too?

**Comment by caseydavenport** [comment]
I would think it needs to be added to all the ways we configure container networking, though some are more important than others.  I had originally though it might be a candidate for a datamodel config option, but it feels like it might be nice to be able to set this on a per-container basis, so I'd be OK with setting it in CNI config, libnetwork label, etc.

**Comment by matthewdupre** [comment]
What's the reason for configuring this?

**Comment by ae6rt** [comment]
One indirect reason for surfacing this as a configurable is to give the operator confidence that this address has not somehow been provisioned from a similar 169.254-net block that may coincidentally be used for either Service IP's or the Calico IP pool.

**Comment by matthewdupre** [comment]
Another possible justification: the datadog bug in #1099 might be workable around by changing this.

**Comment by tmjd** [comment]
Reviewed. This still seems like a valid request and is at the correct priority.
