### ISSUE TITLE
Provide Mesos-CNI with label-based policy demo

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calicoctl#1057]
I'm creating this issue to track work being done to release [the demonstration shown at MesosCon 2016 Denver which showcases label-based policy in Mesos](https://asciinema.org/a/9xy1zuhozoc76oltv3eh5eaou):
- [x] [MESOS-5592: Mesos Passes NetworkInfo to CNI Plugins](https://issues.apache.org/jira/browse/MESOS-5592)
- [x] Mesos v1.0.0 release which includes MESOS-5592
- [x] [Marathon allows setting NetworkInfo.networkName](https://github.com/mesosphere/marathon/commit/731b4d4ee7de2e48417c7b4a7833a6050e0b898a)
- [x] Release of Marathon with ability to set networkName
- [x] [calico-cni accepts Mesos Args containing NetworkInfo](https://github.com/projectcalico/calico-cni/pull/99)
- [x] Add [Calico-CNI Mesos docker-compose demo](https://github.com/projectcalico/calico-containers/pull/1035) which launches Mesos with Calico running as a CNI plugin
- [x] Release calicoctl which supports creation of label-based policy from yaml file
- [ ] Add demo scripts

**Comment by caseydavenport** [comment]
@djosborne what's the latest on this guy? Most of those bullet points are just about done?
