### ISSUE TITLE
failure in assigning more than one IP address in native docker networking (libnetwork) mode.

### ISSUE THREAD

**Issue by dp-farm** [projectcalico/calicoctl#1116]
I am trying to assign more than one IP addresses to an existing interface in a container (created using calico libnetwork plugin). and it fails with below errors. Is this because when we use libnetwork plugin, calico based etcd structure is not used. (as defined in https://github.com/projectcalico/calico-containers/blob/master/docs/etcdStructure.md)?   

``` sh
ubuntu@ubuntu-temp-1:~$ sudo calicoctl container ccd1d71ad294094300e7dfb181a512336ebded98219cbb4c8e71ccecfc1a2c64 ip add 192.168.4.2 --interface=ns0
Failed to add IP address to container.

Container ccd1d71ad294094300e7dfb181a512336ebded98219cbb4c8e71ccecfc1a2c64 is
unknown to Calico.

Use `calicoctl container add` to add the container to the Calico network.
```

'calicoctl container add' obviously fails as interface is already present. 

``` bash
ubuntu@ubuntu-temp-1:~$ sudo calicoctl container add ccd1d71ad294 192.168.3.3 --interface=ns0
CalledProcessError: Command '['ip', 'netns', 'exec', '1290211c641011e6ac188a94a4d80bc5', 'ip', 'link', 'set', 'dev', 'tmp1277e980641', 'name', 'ns0']' returned non-zero exit status 2

Traceback (most recent call last):
  File "<string>", line 144, in <module>
  File "calico_ctl/container.py", line 177, in container
  File "calico_ctl/container.py", line 282, in container_add
  File "site-packages/pycalico/netns.py", line 169, in move_veth_into_ns
  File "site-packages/pycalico/netns.py", line 351, in check_output
  File "site-packages/subprocess32.py", line 638, in check_output
CalledProcessError: Command '['ip', 'netns', 'exec', '1290211c641011e6ac188a94a4d80bc5', 'ip', 'link', 'set', 'dev', 'tmp1277e980641', 'name', 'ns0']' returned non-zero exit status 2
```

**Comment by tmjd** [comment]
@dp-farm Are you still interested in this issue.  If so could you give some context on what you are trying to achieve?  In general we don't suggest adding multiple IP addresses to an interface, so I was wondering if I could help you achieve your goal another way.

**Comment by dp-farm** [comment]
@tmjd My idea is to use a user-space load-balancer (in container form) in calico environment. 
In this deployment calico does the network isolation of applications by keeping instances of an application in one calico profile. So if 3 applications are launched (say with 2 instances each) then we have 3 calico profiles. 

And LB is assigned a vserver IP from calico application profile itself. 
```
client -----> (vserver IP for app 'A') LB ----> app 'A' instance  
```

In this way, LB has multiple vserver IP on single interface for each application (or calico profile).

**Comment by tmjd** [comment]
@dp-farm I'm not sure that I totally understand what you are going for.  Are you adding the LB to the network/profile with the application it is load balancing?   If that is the case then could you instead put the LB in a new network/profile then just allow access to the appropriate application profile through profile configuration?

What is the purpose of giving the LB multiple vserver IPs?  Could you just have one VIP per LB and just launch an LB per needed VIP?

Are the VIPs defined externally or could they come from a Calico IP pool?

**Comment by dp-farm** [comment]
`Are you adding the LB to the network/profile with the application it is load balancing? >>
yes.`
in any case we need VIP per application whether VIP is from application profile or a VIP per profile is created. 
Idea is that each VIP will be doing LB for all instances of application.  

`Are the VIPs defined externally or could they come from a Calico IP pool?`
Both approaches are good as long as we can use calico for policy enforcement. The deployment I suggested VIP comes from calico IP pool.

**Comment by tmjd** [comment]
If the IP being assigned from the IP pool can be used as the VIP then what is the need of assigning a second address?

**Comment by dp-farm** [comment]
what about multiple application hosted by LB instance? It is important that VIP can be identified as application. And thus when someone connects to a VIP related to particular app, appropriate application profile can be invoked and thus policy enforcement based on VIP (application).

all such VIPs (one VIP per application) will be hosted on single LB instance.

**Comment by tmjd** [comment]
There are probably several solutions you could use/test out:
1. Run an LB instance for each application, these are light weight containers so I wouldn't think that would be too much of a stretch.  The LB could be added to the network/profile of the application or even its own profile with access to the application profile which would allow even tighter policy on the LB.
2. A colleague of mine said that they believe OpenStack using Calico can give multiple IP addresses to an interface so it sounds like it can be done. @neiljerram do you know if this is correct and where the code that does it lives?  Obviously, outside of OpenStack, this isn't something that is regularly done with calico.
3. Use an external LB (probably obvious).
4. Register each of the IPs for application instances under the same DNS name and allow DNS to round robin to the applications.

I'm sure there are other ways to do this too but those are a few that I can think of.

**Comment by neiljerram** [comment]
@tmjd Yes, with Calico for OpenStack, http://docs.projectcalico.org/master/usage/openstack/service-ips describes how a VIP can be added to a Calico-networked VM.

**Comment by dp-farm** [comment]
thanks @tmjd @neiljerram 
yes this OpenStack link describes the exact requirement this current enhancement is seeking in docker libnetwork context.

yes I understand that there are multiple ways an LB can be used in calico. This requirement is one of the natural ways LB can be used. 

1. will be some wastage of container instances. 
3. we wanted to use container form of LB.
4. DNS based LB has its own set of issues.

**Comment by tmjd** [comment]
Since I don't believe what you are trying to do right now is possible with calicoctl I am going to close this issue.  I created #1561 to track a feature request to add it.  ProjectCalico does welcome PRs and the company I work for Tigera Inc. (contact@tigera.io) is available to develop the feature if it is critical for you.
