### ISSUE TITLE
calicoctl node remove should warn when the invocation would produce no result

### ISSUE THREAD

**Issue by ae6rt** [projectcalico/calicoctl#1121]
calicoctl should complain when the target of a _node remove_ would produce no result because the node doesn't exist.  

For example, if the given hostname exists in the etcd backing store, then the second invocation should produce a warning saying no such host exists:

```
[centos@ip-10-2-23-158 ~]$ sudo -E /opt/xoom/apps/calico/bin/calicoctl node remove  --hostname=10.2.23.155 --remove-endpoints 
Node configuration removed

[centos@ip-10-2-23-158 ~]$ sudo -E /opt/xoom/apps/calico/bin/calicoctl node remove  --hostname=10.2.23.155 --remove-endpoints 
Node configuration removed
```

**Comment by matthewdupre** [comment]
+1

**Comment by gunjan5** [comment]
We don't have remove command anymore. We just stop/kill/delete the calico/node container/pod depending on the orchestrator (docker, k8s, rkt)
