### ISSUE TITLE
Ability to use ipip only when communicating across different subnets

### ISSUE THREAD

**Issue by garo** [projectcalico/calicoctl#1127]
Currently enabling ipip will force every connection to use ipip encapsulation. It would however be more optimal to let Calico to use native connection whenever both src and dst hosts are in the same network, but fallback to ipip when they are in different networks and when the cross network router doesn't support BGP (thus as in AWS EC2 VPC). This would give the best possible performance in both inter-subnet traffic and cross-subnet traffic.

After some discussion in the IRC channel I got the impression that this might be possible relatively easy by modifying the bird config.

**Comment by caseydavenport** [comment]
Yep!

@robbrockbank has done this on AWS.  Plan is to get this into Calico in the near future.

**Comment by caseydavenport** [comment]
See https://github.com/projectcalico/calicoctl/pull/1453 for a PR which implements this.
