### ISSUE TITLE
Please use IPv6 Documentation prefix

### ISSUE THREAD

**Issue by krunal7558** [projectcalico/calicoctl#1131]
Please use IPv6 prefix 2001:db8::/32 that is reserved via RFC 3849 in below help file.  

https://github.com/projectcalico/calico-containers/blob/master/docs/calico-with-docker/without-docker-networking/IPv6.md

Use of ULA means all IPv6 communication has to be NATed for services that are exposed to internet via container.

**Comment by tmjd** [comment]
@caseydavenport Are you aware of any instances that this needs to be updated for? The only ULA addresses I could find were in some felix FV tests.  I did find several references to 2001::db8::/32 addresses in the docs so I believe this is already complete.

**Comment by caseydavenport** [comment]
@tmjd I'm not aware of any, so given we think this is fixed I'll close for now.

Please shout / open a PR if there are any outstanding.
