### ISSUE TITLE
Support for Docker Swarm mode

### ISSUE THREAD

**Issue by singhwang** [projectcalico/calicoctl#1133]
Now,calico does not Docker 1.12 swarm mode.Whether can support Docker 1.12 swarm mode in the near future?

**Comment by lxpollitt** [comment]
Yes, it should be supported in the future, but timing is unclear.  cc @mavenugo

**Comment by jiaoge** [comment]
oh no!
@lxpollitt could you hurry up?

**Comment by cirocosta** [comment]
as of https://github.com/docker/docker/issues/24569#issuecomment-267044175 1.13 will ship with the network plugins support 😁 it'd be awesome to have calico support!

**Comment by lxpollitt** [comment]
cc @tomdee

**Comment by liftedkilt** [comment]
With 1.13 officially out, is there an update on this?

**Comment by cirocosta** [comment]
Hey, just noticed the change of milestone to 2.3.0; are there any specific issues that we can link to or that's more of a vague milestone?

Thx!

**Comment by caseydavenport** [comment]
Would love to see this issue addressed, but I'm not aware of anyone currently working on it.

@liftedkilt @cirocosta This is tentatively in the milestone, but I think this issue needs a champion to drive to completion.

**Comment by cirocosta** [comment]
@caseydavenport interesting to know! 

I'll take a look at the new plugins API and see whether I can have some work at least started; I hope this gets on the track 😁  I'll let you know.

Thx! 👍

**Comment by caseydavenport** [comment]
@cirocosta great! Let me know here if you do get started and would like any help.

**Comment by gcavalcante8808** [comment]
Is there any news about this topic?

For now, looks like Weave now support V2 plugin support for Docker:

https://www.weave.works/docs/net/latest/install/plugin/plugin-v2/

**Comment by cirocosta** [comment]
I end up having 0 time to tackle it, even though now I'm more familiar with the plugin API 😬  sorry for raising the expectation (even though I still plan to implement)

**Comment by vlindhol** [comment]
Docker Swarm has a very low quality overlay network, as can be seen by this issue:

https://github.com/moby/moby/issues/32195

I am hoping Calico could fix this issue, when Docker Swarm support arrives! It also seems a bit more performant.

**Comment by Chrislevi** [comment]
@caseydavenport Is there any news about this?

**Comment by olljanat** [comment]
@Chrislevi 
 status looks to be documented to https://github.com/projectcalico/libnetwork-plugin

```The libnetwork plugin integration is no longer included as a core component in Calico releases, and is not being actively developed or supported by the core Calico team. The latest release of Calico which includes this plugin is the v2.6.x series of releases.```

However overlay networking driver have been improved a lot so it is best option with swarm.
