### ISSUE TITLE
Ability to customize export filters is needed

### ISSUE THREAD

**Issue by adidenko** [projectcalico/calicoctl#1138]
Right now export filter is quite restrictive as it allows to export only IP pools defined in Calico. As a cloud operator I may want to reuse existing Bird from calico/node to also export some additional routes needed for my infrastructure. For instance, export routes for all 'tap*' interfaces or for some specific IP addresses which are not a part of Calico pool.

**Comment by caseydavenport** [comment]
@neiljerram I believe you've been involved here, so assigning to you!

**Comment by robbrockbank** [comment]
I believe this has been merged some time ago, and custom filters can now be applied writing to the relevant etcd location.  

@adidenko :  Please re-open if you believe this is not the case.

Regarding doc's/calicoctl control of this - I think this is a broader question about how we handle additional BGP configuration, and is dependent on the BGP backend that we use.  Needs some thought - but I'll raise a different issue for that.
