### ISSUE TITLE
Can't use docker network names as profile names when they contain special characters.

### ISSUE THREAD

**Issue by matthewdupre** [projectcalico/calicoctl#1155]
You can `docker network create` a network with a name like `a/b`, which works, but attempting to use `calicoctl profile a/b rule show` (e.g.) fails, because / isn't accepted.

It's not valid for a Calico profile name, but perhaps we should accept it for the 'convenience' docker network name => profile uuid lookup?

What do people think?

**Comment by caseydavenport** [comment]
Calico supports `/` characters in Profiles now.
