### ISSUE TITLE
hostname -i doesn't work to find IP address inside docker container

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calicoctl#1201]
With normal docker networking, `hostname -i`run from inside the container shows the containers IP address but this doesn't work when networked with Calico.

**Comment by ae6rt** [comment]
I find that _hostname -i_ works from inside a pod networked with Calico.  Hmm.

```
$ k --namespace=service-1 get pod webserver-464642244-ite1k -o wide
NAME                        READY     STATUS    RESTARTS   AGE       IP              NODE
webserver-464642244-ite1k   1/1       Running   0          8d        10.131.240.14   10.2.23.171
```

```
$ k --namespace=service-1 exec -it webserver-464642244-ite1k -- hostname -i
10.131.240.14
```

```
$ k --namespace=service-1 exec -it webserver-464642244-ite1k -- cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.4.0
PRETTY_NAME="Alpine Linux v3.4"
HOME_URL="http://alpinelinux.org"
```

**Comment by aslanbekirov** [comment]
I am using it in Mesos environment, and I am not using latest Mesos, so we dont have pod yet. and `hostname -i` does not work

**Comment by aslanbekirov** [comment]
But if the goal is to get the hostname by someway , `networkctl status | awk '/Address/ { print $2 }'` works if you have networkctl installed

**Comment by matthewdupre** [comment]
What was the container you were running (and does it reproduce in a reasonably capable container: say an ubuntu), and what did `ip addr list` look like in that container?

**Comment by caseydavenport** [comment]
Maybe a libnetwork vs CNI plugin thing? @fasaxc do you know what versions you were using? I'm tempted to close unless you think there is something we should do.

**Comment by tmjd** [comment]
There hasn't been any traffic on this for a while so I'm going to close this.
