### ISSUE TITLE
Add ST for: tunl0 takes 4 minutes to be re-created after calico container restart

### ISSUE THREAD

**Issue by xh3b4sd** [projectcalico/calicoctl#1209]
I have the following systemd units running on a systemd `225`. One runs calico, one restarts it. The restart is required for certificate renewal. I already created issues about the restart behaviour in https://github.com/projectcalico/calico-containers/issues/1177 and https://github.com/projectcalico/calico-containers/issues/1178.

```
$ systemctl cat calico-node
# /run/systemd/system/calico-node.service
[Unit]
Description=calicoctl node

[Service]
Restart=always
RestartSec=0
TimeoutStopSec=10
StartLimitIntervalSec=0
EnvironmentFile=/etc/network-environment
Environment="ETCD_AUTHORITY=<etcd endpoint>"
Environment="ETCD_SCHEME=https"
Environment="ETCD_CA_CERT_FILE=/etc/kubernetes/ssl/etcd/client-ca.pem"
Environment="ETCD_CERT_FILE=/etc/kubernetes/ssl/etcd/client.pem"
Environment="ETCD_KEY_FILE=/etc/kubernetes/ssl/etcd/client-key.pem"
ExecStart=/opt/bin/calicoctl node --ip=${DEFAULT_IPV4} --detach=false --node-image=giantswarm/node:v0.22.0
ExecStartPost=/bin/bash -c "/opt/bin/calicoctl bgp peer add $(echo 10.2.95.1 | cut -d'.' -f1-3).0 as $(/opt/bin/calicoctl bgp default-node-as)"
ExecStop=/opt/bin/calicoctl node stop --force
ExecStopPost=/bin/bash -c "/opt/bin/calicoctl bgp peer remove $(echo 10.2.95.1 | cut -d'.' -f1-3).0"

[Install]
WantedBy=multi-user.target
```

```
$ systemctl cat calico-node-restart
# /etc/systemd/system/calico-node-restart.service
[Unit]
Description=calico-node-restart

[Service]
Type=oneshot
ExecStartPre=/usr/bin/systemctl stop calico-node.service
ExecStartPre=/usr/bin/bash -c 'while systemctl is-active --quiet calico-node.service; do sleep 1 && echo waiting for calico-node to stop; done'
ExecStart=/usr/bin/systemctl start calico-node.service

[Install]
WantedBy=multi-user.target
```

When running the following command it shows that it takes around 4 minutes until the `tunl0` appears again. 

```
sudo systemctl start calico-node-restart; date; sleep 5; while ! route -n | grep tunl0; do sleep 1; done; date
```

Once calico restarted I also see some weird behaviour of one of my web services that runs within the calico network. I am running the following command. 

```
while :; do curl -sL -w "status code %{http_code} " http://<my web service> -o /dev/null; echo at $(date +"%T"); sleep 1; done
```

This is the output of the command above. As you see there are some glitches in the output which means that the service is partially unavailable due to interruptions in the networking setup which is caused by the restart and the following magic that I have no insides about at the moment. 

```
status code 200 at 19:57:03
status code 200 at 19:57:11
...
status code 200 at 19:57:14
status code 200 at 19:57:26
...
status code 200 at 20:03:01
status code 200 at 20:03:03
status code 200 at 20:03:04
...
status code 200 at 20:03:13
status code 200 at 20:03:24
status code 200 at 20:03:30
status code 200 at 20:03:41
```

**Comment by caseydavenport** [comment]
Hmm.. I wouldn't have expected the `tunl0` interface to be destroyed by restarting `calico/node`.  

@matthewdupre do you know of any cases where Felix / BIRD will do this?

**Comment by matthewdupre** [comment]
Yeah, I thought we never destroyed tunl0.

**Comment by caseydavenport** [comment]
@xh3b4sd any news on this guy?

**Comment by xh3b4sd** [comment]
I did not check further on this one because I also need to work in other directions. Is this issue fixed? Can somebody else confirm it? Not sure what feedback I can give here now. All I know is in the PR description.

**Comment by hectorj2f** [comment]
@caseydavenport The problem remains there, we have to restart calico (etcd TLS) and other components of our cluster nodes whenever we perform a certificate renewal operation. So the node is there, but in terms of calico networking, it takes around 4min to become operative :/.

**Comment by caseydavenport** [comment]
Assigning to myself + marking as a bug.  Will aim to repro and hopefully fix in v1.0.1.  Thanks for your patience!

**Comment by hectorj2f** [comment]
Thanks @caseydavenport! 👍

**Comment by tomdee** [comment]
Looks like we're still needing to find a simple repro for this? Does anyone have a simple way to demonstrate this problem?

**Comment by xh3b4sd** [comment]
@tomdee I was under the impression the issue description contains all relevant information to reproduce the problem. What do you miss?

**Comment by fasaxc** [comment]
@caseydavenport @tomdee I think it's only the tunl0 routes that are going away, @xh3b4sd's test was `! route -n | grep tunl0`.

**Comment by fasaxc** [comment]
@xh3b4sd @hectorj2f Do you still see this with the latest pre-release: https://github.com/projectcalico/calicoctl/releases/tag/v1.1.0-rc2

In that release, we fixed a bug (in Felix) where the tunl0 IP was flapped over restart.

**Comment by lwr20** [comment]
A lot of similarities here with https://github.com/projectcalico/calicoctl/issues/1419.  Are we still seeing this with the latest release?

**Comment by hectorj2f** [comment]
@fasaxc We didn't upgrade calico to the latest version. We still use v1.4.2 but @xh3b4sd can confirm that.

**Comment by fasaxc** [comment]
@hectorj2f The fix isn't in the 1.4.x series, you need at least `calico/node:v1.0.2` / felix `v2.0.2`

**Comment by xh3b4sd** [comment]
We will upgrade calico at some point. Have to check with the team for priorities. Will come back on that eventually.

**Comment by fasaxc** [comment]
@lwr20 is planning to manually re-test this for 2.1; adding the ST shouldn't block the release.

**Comment by caseydavenport** [comment]
My understanding is that this has been fixed in recent releases, please shout if you think otherwise!
