### ISSUE TITLE
missing support for hot reloading configuration

### ISSUE THREAD

**Issue by xh3b4sd** [projectcalico/calicoctl#1210]
We want to run calico within an end-to-end encrypted Kubernetes cluster. Therefore we need to renew certificates frequently. This requires all components involved, including calico, to be provided with new certificates after a specific amount of time. Our current approach is to restart calico which results in several issues as I already pointed out in https://github.com/projectcalico/calico-containers/issues/1177, https://github.com/projectcalico/calico-containers/issues/1178 and https://github.com/projectcalico/calico-containers/issues/1209. Since I think these issues should be fixed at some point I would also like to get in touch with you guys to have a discussion about an option to hot reload configuration. This would hopefully prevent the necessity of completely restarting the calico container which would hopefully prevent availability glitches in the network infrastructure. Is there something similar on the roadmap? What do you guys think about this? Sorry in advance for bugging you with lots of issues recently.

**Comment by tomdee** [comment]
This sounds like a really useful feature but is probably best fixed in the etcd client library. Did you try raising it upstream?

**Comment by xh3b4sd** [comment]
I cannot completely comprehend your thinking. Why is this a feature for the etcd client? It is the calico node that has to be configured. Can you elaborate a bit more on your idea?

**Comment by tomdee** [comment]
I was thinking that the etcd client library could be passed a file name for the certificates. If the certs change on disk then the client just starts using the new cert.

I'm not against the idea of it being handled from the calico side though - it's just not currently on our roadmap.

**Comment by caseydavenport** [comment]
@xh3b4sd are you still seeing issues with `calico/node` restart?

**Comment by caseydavenport** [comment]
https://github.com/coreos/etcd/commit/4e21f87e3d014d606bb3ba2a89731a7d24806611

Not sure if this change impacts clients as well, but it seems like it might. Haven't tried it myself.

**Comment by rafaelvanoni** [comment]
@xh3b4sd It's been a while :-) But would be interested to hear if this is still an issue or if you worked around it somehow. Closing this issue for now, please add comment if you'd like us to re-open it.
