### ISSUE TITLE
Docker hub page has strange comment blocks at top

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calicoctl#1237]
https://hub.docker.com/r/calico/node/

![screen shot 2016-11-01 at 15 08 32](https://cloud.githubusercontent.com/assets/469264/19894512/310c3a24-a045-11e6-9489-a87ddee79d69.png)

**Comment by robbrockbank** [comment]
The text in the calico/node repo was from a very old README.

I've removed it and replaced it to just contain a link to the calico/node architecture.  I think that should suffice for now.
