### ISSUE TITLE
calico-node container doesn't fail when a missing module prevents iptables manipulation

### ISSUE THREAD

**Issue by marun** [projectcalico/calicoctl#1242]
Running on kubernetes, on a host that hadn't loaded the ``ip6_tables`` module, a ``calico-node`` container failed to install the global rules as per the following log output:

```
2016-11-01 22:09:14,574 [INFO][146/3] calico.felix.felix 211: Installing global rules.
2016-11-01 22:09:14,575 [ERROR][146/18] calico.felix.actor 321: Exception processing M42e8748f68a642ab (_load_chain_names_from_iptables)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/calico/felix/actor.py", line 319, in _step
    result = msg.method()
  File "/usr/lib/python2.7/site-packages/calico/felix/fiptables.py", line 213, in _load_chain_names_from_iptables
    self.table])
  File "/usr/lib/python2.7/site-packages/gevent/subprocess.py", line 327, in check_output
    raise ex
CalledProcessError: Command '['ip6tables-save', '--table', 'nat']' returned non-zero exit status 1
2016-11-01 22:09:14,576 [INFO][146/18] calico.felix.fiptables 529: IptablesUpdater<v6-nat,queue_len=0,live=True,msg=None> no updates in this batch.
TrackedAsyncResult ('<disabled>', '<disabled>', 'IptablesUpdater(v6-nat)', '_load_chain_names_from_iptables') was leaked with exception CalledProcessError().  Dying.
```

Nothing in the pod status indicated an error condition, despite the problem preventing networking  connectivity of subsequently launched pods.  The only indication of the problem was in the container logs.   It may make sense to have the pod fail if it can't ensure connectivity so that the error is more obvious to a kube administrator.  

In this specific case, @caseydavenport suggested that calico should not require the ip6_tables module when running in kube since ipv6 isn't supported.

**Comment by caseydavenport** [comment]
@marun thanks for raising.

We should probably be setting this option to false for the k8s installs: https://github.com/projectcalico/felix/blob/master/go/felix/config/config_params.go#L101

I _think_ we should also be failing hard when Felix falls over, as you suggest.

**Comment by caseydavenport** [comment]
I've raised this guy for disabling ipv6 on k8s: https://github.com/projectcalico/calico/pull/135

**Comment by caseydavenport** [comment]
@fasaxc what do you think the right way to fix this would be?

**Comment by fasaxc** [comment]
@caseydavenport Can/do we map the kernel module directories `/lib/` IIRC into the container so that they can be loaded?  Obviously we can't ship modules inside the container because they wouldn't match the running kernel.

**Comment by marun** [comment]
@fasaxc That might be fine for development, but I think that's inadvisable in any production scenario due to the security implications.

**Comment by fasaxc** [comment]
Files this issue in Felix to cover improving our IPv6/module detection: https://github.com/projectcalico/felix/issues/1411

I think this issue should remain open to cover improving the tie between felix status and calico/node status.  Shouldn't calico/node fail if Felix is cyclicly crashing?  (Note, felix does restart from time to time to reload config so it's not 100% trivial.)

**Comment by caseydavenport** [comment]
Calico v2.4.0 now supports Felix readiness / liveness probes, which will trigger a restart of Felix in this scenario and provide some feedback to the user that the Pod isn't healthy.
