### ISSUE TITLE
calicoctl edit command

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/calicoctl#1259]
a command to edit a specific resource field

**Comment by caseydavenport** [comment]
Yep.  See `kubectl edit` for inspiration :)

It's pretty cool.

**Comment by robbrockbank** [comment]
I've prototyped this (by nabbing a bunch of the kubenetes code :-)

https://github.com/robbrockbank/calicoctl/tree/edit-command

Probably a good starting point.

**Comment by caseydavenport** [comment]
PR was here if anyone wants to pick it up: https://github.com/projectcalico/calicoctl/pull/1564
