### ISSUE TITLE
Calico/node image still has some dependencies on Python libcalico

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calicoctl#1265]
For the startup.py script and the allocate-ipip-addr.py script

- [x] startup.py
- [x] allocate-ipip-addr.py

**Comment by caseydavenport** [comment]
We can take this in chunks. 

I've done the first bit here: #1381.

We can also take this opportunity to do #873

**Comment by caseydavenport** [comment]
This is fixed in master.
