### ISSUE TITLE
Use Docker client for calicoctl node run command

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calicoctl#1280]
Currently the command shells out to run the container - we should be using the Docker client to do this.

Also:
-  Should handle a stopped container with the same name being present
-  Have options for generating systemd config (should remove the -d from the docker incantation)

**Comment by djosborne** [comment]
Would be nice to also fix #1287 while work's being done in the same ballpark

**Comment by djosborne** [comment]
@robbrockbank for the first bullet point, I found that if `calico/node` is already running, `calicoctl node run` quits with a 125 exit code.

**Comment by caseydavenport** [comment]
I don't think switching to using the Go library is high priority at all, unless there are clear, important benefits.

One nice thing about shelling out is that the command we print for `--dry-run` is easier to make accurate.

**Comment by robbrockbank** [comment]
When we do switch over to using the Docker client, we should split out the docker pull so that we are able to display a sensible message to the user when we need to do a pull.

**Comment by robbrockbank** [comment]
When moving away from shelling out, we should undo the additions of #1430 which are working around requirements for running the docker CLI within the calico/ctl container.
