### ISSUE TITLE
Add merge command to calicoctl

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calicoctl#1309]
Add a merge command to calicoctl which will merge in only the fields supplied in a YAML document.

See k8s for best practices wrt to slices etc.

**Comment by caseydavenport** [comment]
@robbrockbank can we punt this from 2.0?  It's useful but I don't think it's mandatory.

**Comment by robbrockbank** [comment]
Yes this was in planning for post v2.0.0 anyways
