### ISSUE TITLE
Confd Errors about getting ipv6 keys

### ISSUE THREAD

**Issue by alfred-huangjian** [projectcalico/calicoctl#1340]
I'm trying to build up an kubernetes environment with calico, and follow the guide below. 
http://docs.projectcalico.org/v1.6/getting-started/kubernetes/installation/

kubernetes version:  1.3.0
OS: Suse12sp1
Calico: 1.6
```
2016-11-25T03:30:25Z host-9-92-19-26 confd[81]: ERROR 100: Key not found (/calico/ipam/v2/host/host-9-92-19-26/ipv6) [9419]
2016-11-25T03:30:27Z host-9-92-19-26 confd[81]: ERROR 100: Key not found (/calico/ipam/v2/host/host-9-92-19-26/ipv6) [9419]
2016-11-25T03:30:29Z host-9-92-19-26 confd[81]: ERROR 100: Key not found (/calico/ipam/v2/host/host-9-92-19-26/ipv6) [9419]
```
And the route between hosts is not generated
```
host-9-92-19-27:~ # route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         9.92.16.1       0.0.0.0         UG    0      0        0 eth0
9.92.16.0       0.0.0.0         255.255.252.0   U     0      0        0 eth0
169.254.169.254 -               255.255.255.255 !H    0      -        0 -
169.254.169.254 9.92.19.11      255.255.255.255 UGH   0      0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.48.0    0.0.0.0         255.255.255.255 UH    0      0        0 cali63aa00d6316
192.168.48.1    0.0.0.0         255.255.255.255 UH    0      0        0 cali40759ecfb67
```
Can anyone help or give some ideas?

**Comment by alfred-huangjian** [comment]
By the way, I have meet the same problem with the lastest beta version.

**Comment by caseydavenport** [comment]
I can't quite remember who is supposed to populate that data at startup.  @robbrockbank?

**Comment by tmjd** [comment]
@alfred-huangjian, is this still an issue for you? If it is, could you try again with the v1.0.2 release or the release candidate that is out, v1.1.0-rc6. Thanks

**Comment by tmjd** [comment]
I'm going to close this for now.  @alfred-huangjian if you can try this again with the latest release Calico v2.1 http://docs.projectcalico.org/v2.1/releases/ and the problem still persists please feel free to reopen this issue.  For other problems please open a new issue or feel free to reach out to the calico team at https://calicousers.slack.com.  Thanks.
