### ISSUE TITLE
calicoctl apply could flag up repeated names in input yaml

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calicoctl#1345]
I imported a yaml file containing multiple policies; I'd made a noob error by copy and pasting a policy and failing to update its name.  calicoctl happily processed the file with the two policies in it but presumably the later one clobbered the first.  Output said `Successfully applied 2 'policy' resource(s)`, which was a bit misleading.

**Comment by robbrockbank** [comment]
This might come out quite easily from something I'm doing for the libcalico-go refactor: ability to covert a key to an ordered set of strings - should make general key comparison easy.

**Comment by lxpollitt** [comment]
What does kubectl do in equivalent scenarios?

**Comment by bcreane** [comment]
@mgleung - flag for your attention. Related to your help w/multiple yaml docs in same file/input: https://github.com/projectcalico/go-yaml-wrapper/pull/2 and https://github.com/projectcalico/libcalico-go/issues/47.

**Comment by caseydavenport** [comment]
```
$ kubectl apply -f ns.yaml
namespace "myns" configured
namespace "myns" configured
```

This is the kubernetes behavior ^

One solution to this problem would be to stop logging `Successfully applied 2 'policy' resource(s)` and instead log for each resource that was created / modified / etc.

**Comment by robbrockbank** [comment]
I like the idea of printing out the resources we updated - and should be trivial now that the resources have a descriptive String() method.

**Comment by bcreane** [comment]
@mgleung - was this fixed?

**Comment by mgleung** [comment]
@bcreane It does not look like this has changed.  We do need to use the resource's descriptive `String()` method in order to filter our overridden duplicates.  Was it decided whether to keep the number of applied resources or print out a string of each resource for the new result?

**Comment by caseydavenport** [comment]
I think we close this as `wontfix`
