### ISSUE TITLE
1.6 OpenStack docs refer to 1.4 PPA

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calicoctl#1347]
I didn't know we had a 1.6 PPA, but the docs appear to refer to the 1.4 PPA: http://docs.projectcalico.org/v1.6/getting-started/openstack/installation/ubuntu

**Comment by neiljerram** [comment]
We don't have a 1.6 PPA.  Is there an issue here?

**Comment by neiljerram** [comment]
Oh I'm sorry, actually we do.  (I created it and have already forgotten.)

**Comment by caseydavenport** [comment]
@neiljerram - could this be knocked off quickly?

Otherwise we should just close this issue.
