### ISSUE TITLE
host can't ping container when adding some profiles rules

### ISSUE THREAD

**Issue by wupeaking** [projectcalico/calicoctl#1348]
sorry my english is poor.

there are my env:
calico-node v0.22.0
calio-libnetwork v0.9.0
docker 1.12
vmware centos 7.2

mesos-slave1: 172.24.6.166 
mesos-slave2: 172.24.4.167
mesos-master,marathon: 172.24.6.174

mesos-slave1 and mesos-slave2 are not in same subnet, so i use ipip.

I create three networks:
```
name      ip  pool           opt
db  | 192.19.19.0/24  |  ipip, nat-outgoing
web | 18.8.8.0/24      |   ipip, nat-outgoing
app |111.12.0.0/16    |  ipip, nat-outgoing
```

I create three application using marathon.

web11  has two containers:
```
	container1 ip: 18.8.8.2  in mesos-slave2
	container2 ip: 18.8.8.3  in mesos-slave1
```

app11 has two containers：
```
	container1 ip: 111.12.0.2  in mesos-slave1
	container2 ip: 111.12.0.3  in mesos-slave1
```

db11 has one container：
```
	container1 ip: 192.19.19.0 in mesos-slave2
```

I want mesos-master(172.24.6.174) to ping app. so I set app profile as follows:
```
Inbound rules:
   1 allow from cidr 172.24.6.174/32 
   2 allow from tag app
   3 allow from tag web
Outbound rules:
   1 allow
```
but mesos-master can't ping app, web can ping app.

I set  app profile as follows:

```
Inbound rules:
   1 allow
Outbound rules:
   1 allow
```

all containers or hosts can ping app. 

but I want some hosts I set to ping the app . what should i do?

**Comment by caseydavenport** [comment]
Sorry that you didn't get any response here.  This is for a really old version of Calico, so I'm going to close this issue.

If you see the same behavior on recent Calico versions, please re-open and tag me and I'll help figure out what's going on.
