### ISSUE TITLE
Its easy to end up writing to the wrong etcd with calicoctl

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calicoctl#1363]
As summary.  For example, you may end up manipulating the k8s etcd instead of the calico one.

Perhaps we should check for the existence of the `/calico` directory in etcd before writing a key into it - and error if there isn't one found.  Maybe with a `-f` flag to do it anyway (e.g. to set the Ready flag on a baremetal system at start of day).  And error if we don't find a `/calico` directory when reading a key? 

With those two behaviours, it should become obvious to a user quickly if they're in this situation.

**Comment by robbrockbank** [comment]
I think the real issue was that there was a local etcd running and calicoctl defaults to using localhost:2379.

Maybe we should just warn the user if they have not explicitly specified an etcd datastore and are using the default "localhost:2379".  

@lwr20 - would that have sorted this out for you??

**Comment by lwr20** [comment]
This was on a k8s system (on the master) - so it's not surprising that
there was an etcd there. And if I didn't know better, why would I know that
the local etcd was the wrong one?  If probably ignore any warning like
that...

On Wed, 30 Nov 2016, 20:10 Rob Brockbank, <notifications@github.com> wrote:

I think the real issue was that there was a local etcd running and
calicoctl defaults to using localhost:2379.

Maybe we should just warn the user if they have not explicitly specified an
etcd datastore and are using the default "localhost:2379".

@lwr20 <https://github.com/lwr20> - would that have sorted this out for
you??

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/projectcalico/calico-containers/issues/1363#issuecomment-263981356>,
or mute the thread

**Comment by caseydavenport** [comment]
> Maybe we should just warn the user if they have not explicitly specified an
etcd datastore and are using the default "localhost:2379"

Feels like warning if `ETCD_ENDPOINTS=` would be fine behavior.  We could add a configuration option to disable warnings if they're annoying.

**Comment by caseydavenport** [comment]
We probably want to warn if people use ETCD_AUTHORITY=... if we don't already.

**Comment by caseydavenport** [comment]
I don't think there's anything we can do about this.

**Comment by lwr20** [comment]
What's wrong with the suggestion in the original comment?
"Perhaps we should check for the existence of the /calico directory in etcd before writing a key into it - and error if there isn't one found."

**Comment by caseydavenport** [comment]
```
$ ./dist/calicoctl-linux-amd64 version
Client Version:    v1.6.0-rc1-1-g72757629
Build date:        2017-09-25T01:36:28+0000
Git commit:        72757629
Cluster Version:   unknown
Cluster Type:      unknown
```

FWIW for modern Calico releases, if you point calicoctl at an etcd that doesn't have Calico data in it you'll get output like this where the Cluster Version is "unknown" since `calico/node` hasn't run against this etcd cluster.

Not a 100% solution, but in most cases it's a good way to check if you've got it calicoctl pointing at the right place.

**Comment by caseydavenport** [comment]
calicoctl now requires `ETCD_AUTHORITY` to be set and won't default to a value.

**Comment by caseydavenport** [comment]
Give the above, this can be marked closed. 

We've seen a dramatic drop off in users who are misconfiguring this since the time this issue was raised.
