### ISSUE TITLE
Make the PR testing faster

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calicoctl#1364]
For PR check-ins we should run a small subset of the tests.
For overnight we should run the full suite of tests.

**Comment by tomdee** [comment]
@robbrockbank Can you share some ideas for which subset of tests should be run?

**Comment by robbrockbank** [comment]
All of the UTs (since they don't take long)
For the STs, I'd suggest:

- test_bgp_backends
- test_autodetection
- test_crud
- test_ipam
- test_labelling
- test_felix_gateway

That covers a bunch of different areas, but to some degree is a little arbitrary based on what I perceive to be areas that change more often that others.

**Comment by tomdee** [comment]
Who should own making this happen? @lwr20

**Comment by lwr20** [comment]
I can do this if you like, but trouble is, as a tester, I'm inclined to think we should run them all every time - then there are no arguments over who broke it, and you don't need someone to keep an eye on them and figure out who gets the blame the next morning when no one else claims the breakage.

According to Semaphore, build and test only takes 38 minutes at present.

Another approach might be to kick off 2 jobs with every PR - one which completes quickly (a smoke test) and one which runs them all.  If we can do those sequentially on Semaphore, that'd be great.  If not, we'd be increasing our Semaphore usage.

**Comment by caseydavenport** [comment]
I think we should be aiming to have at _most_ 15 minutes of tests run against each PR / push.

This could be done through parallel jobs, or by limiting the number of tests that get run against each commit and delegating others to nightly jobs, but we should definitely be able to get high-confidence testing within that amount of time, and it will greatly improve development cycles.

**Comment by caseydavenport** [comment]
I'm going to close this now that the STs for calico/node have been moved to the Calico repo.

We can re-open an issue there to discuss if still needed.
