### ISSUE TITLE
calicoctl output command line arguments are inconsistent

### ISSUE THREAD

**Issue by matthewdupre** [projectcalico/calicoctl#1399]
`calicoctl get policy -o yaml` works
`calicoctl get policy --output=yaml` works
`calicoctl get policy --output yaml` works
`calicoctl get policy -o=yaml` fails with `unrecognized output format '=yaml'.

The help text describes the format as `-o --output=<OUTPUT FORMAT>`.

The fourth of these should work: it's perfectly reasonable to expect it to be valid given the help text.

**Comment by caseydavenport** [comment]
@gunjan5 If this is easy to fix, we should just fix it.  If it's not, then let's close this issue for now as `wontfix`.
