### ISSUE TITLE
Release process hiccups

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calicoctl#1401]
First time I've tried to do a calico-containers release today; hit a few snags as a set of fresh eyes:

- [x] `make release` "what to do next" help doesn't mention mac/windows calicoctl binaries.
- [x] `make release` "what to do next" help doesn't mention the list of sub-component versions to embed in the release note or how to collect that.
- [x] RELEASING.md implies you can release from a non-master branch, but that messes up the automatic version numbers assigned by subsequent releases (if the branch isn't merged back to master before the next release).
- [x] What are the pre-reqs for being able to push to quay and dockerhub?
- [ ] `make clean` deletes the `calico/felix` docker image; this caught me out when I was trying to do an end-to-end build on my system without pushing anything.  Feels wrong to delete an artefact that you didn't `make`.
- [x] If build fails have to delete the tag again before rebuild.
- [x] Final check of version number detected a dirty build and failed the build.  Please can we add a dirty check at the beginning?

**Comment by tomdee** [comment]
Sorry, I can't take this. Assigning to Casey as he did the last release.

**Comment by gunjan5** [comment]
@fasaxc I created a PR #1449 with your suggestions. One thing I'm not sure about is the `make clean` step. Seems like it is backing up 3 container images `felix`, `libcalico` and `test` images that it (makefile) doesn't make. Do you think we should not remove any of those? 

On the other hand, I'm also thinking what if there is a "dirty" local image. Person doing the release can also end up using a local image without knowing. 

Don't have strong feeling either way, just putting it on the table.

**Comment by fasaxc** [comment]
@gunjan5 Yeah, the backup saved me last time.  Maybe we just live with but I'm not 100% sure why we are removing those images at all; if you can find that out from Casey or Tom then it might help us come up with something better.
