### ISSUE TITLE
Pass DOCKER_HOST to calico/node 

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/calicoctl#1404]
See https://github.com/projectcalico/libnetwork-plugin/issues/90#issuecomment-266078037 for detail

**Comment by gunjan5** [comment]
I'm thinking of one of the two approaches here:
1. calicoctl node run command checks if ENV var `DOCKER_HOST` is set, if it is, then pass it to calico/node as `-e DOCKER_HOST` 
2. add a flag for calicoctl node run `--docker-host=<DOCKER_HOST>` 

I'm leaning more towards the first option. 
WDYT? @tomdee @robbrockbank

**Comment by robbrockbank** [comment]
I prefer to have things that we think are permanent features as command line options - they are easier to use and easier to document IMHO.   This feels like a permanent feature to me, so I'd err on having it as an option rather than an env
