### ISSUE TITLE
Don't print ETCD_AUTHORITY in `node start` output if possible

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calicoctl#1422]
To further help phase out the deprecated `$ETCD_AUTHORITY`, we should avoid printing it in the `calicoctl node run` output when possible, i.e. when user has specified `$ETCD_ENDPOINTS` instead.

For example, I ran 

`[vagrant@calico-mesos-03 ~]$ sudo ETCD_ENDPOINTS=http://172.24.197.101:2379 calicoctl node run --dryrun --init-system`

and I get:

`docker run --net=host --privileged --name=calico-node --rm -e CALICO_NETWORKING_BACKEND=bird -e NO_DEFAULT_POOLS= -e CALICO_LIBNETWORK_ENABLED=true -e CALICO_LIBNETWORK_IFPREFIX=cali -e ETCD_ENDPOINTS=http://172.24.197.101:2379 -e ETCD_AUTHORITY= -e ETCD_SCHEME= -e NODENAME=calico-mesos-03 -v /var/run/calico:/var/run/calico -v /lib/modules:/lib/modules -v /var/log/calico:/var/log/calico -v /run/docker/plugins:/run/docker/plugins -v /var/run/docker.sock:/var/run/docker.sock calico/node:v1.0.0`

No need to point ETCD_AUTHORITY here.

**Comment by gunjan5** [comment]
@djosborne I think the reason for passing that is because we have a `--config` option to specify calico config file and it can still have `ETCD_AUTHORITY`. 

Are you suggesting we convert `ETCD_SCHEME` + `ETCD_AUTHORITY` to `ETCD_ENDPOINTS` and pass that?

**Comment by djosborne** [comment]
No, I'm just suggesting that before we output that command string, if `-e ETCD_AUTHORITY=` is blank (as it is in my output), we should redact it.

I don't think this is affected by `calicoctl.cfg`, but maybe we should chat if you think it is.

**Comment by robbrockbank** [comment]
Actually, if someone is still explicitly using ETCD_AUTHORITY then we should just convert that to ETCD_ENDPOINTS.

**Comment by caseydavenport** [comment]
Agreed with @robbrockbank.  Let's _never_ show ETCD_AUTHORITY.

**Comment by djosborne** [comment]
I don't like converting environment variables for Users. Users would pass `ETCD_AUTHORITY` when they call `calicoctl`, but see `ETCD_ENDPOINTS` get set in `calico/node`.

I'd much prefer just continuing to phase out ETCD_AUTHORITY by redacting references to it, as my original issue suggested...

**Comment by caseydavenport** [comment]
@djosborne hmm, I get what you're saying, but ETCD_AUTHORITY has been deprecated for a while now.  I'd be really happy to just drop it entirely in Calico v2.1.0.  The conversion to ETCD_ENDPOINTS is just once last nicety before that if we want to.

**Comment by gunjan5** [comment]
So do we agree to just drop `ETCD_AUTHORITY` in v2.2? @caseydavenport @robbrockbank @djosborne

**Comment by tmjd** [comment]
With dropping ETCD_AUTHORITY, does that also include dropping ETCD_SCHEME?  One does not seem useful without the other.  @gunjan5 @robbrockbank @djosborne

**Comment by robbrockbank** [comment]
@tmjd:  Yes it does include dropping ETCD_SCHEME.  The two are only useful together since the ETCD_ENDPOINTS combines both scheme and address.

**Comment by tmjd** [comment]
To clarify what is desired.  By 'drop' we mean to never display/show ETCD_AUTHORITY or ETCD_SCHEME.  If those are set they will be combined to create an ETCD_ENDPOINTS (assuming it is not already set).

**Comment by robbrockbank** [comment]
Yup that's correct.

It's just the output from `calicoctl node run` where we want to suppress showing ETC_AUTHORITY and ETCD_SCHEME.  This command displays the underlying docker command to execute if you want to add calico to your own init system etc - so we should display the preferred incantation.

We still need to handle ETCD_AUTHORITY and ETCD_SCHEME for back-compatibility with existing deployments that might just want to update the container image.
