### ISSUE TITLE
Default MTU for CNI plugin is not right

### ISSUE THREAD

**Issue by MikeSpreitzer** [projectcalico/calicoctl#1425]
I am using Kubernetes, and my worker nodes have MTU=1446.  The network interface that the CNI plugin puts in the container has an MTU of 1500.  That is too high.  When I make a Calico IP pool with ip-in-ip encapsulation, and the container sends a long reply to an HTTP request, the long packets are dropped in the plumbing outside the worker node.  When I add `"mtu": 1416` into the Calico CNI plugin config file, then resulting network interfaces inside containers have MTU of 1416 and no packets are dropped.

**Comment by MikeSpreitzer** [comment]
The ip-in-ip encapsulation overhead is 20 bytes, and an MTU of 1426 inside the container works too.  I also tested a client inside a pod fetching a long file from outside the cluster, and that worked too (I suppose due to the client setting its max segment size TCP option based on the local MTU).  I have _not_ tested external peers sending large UDP packets into a pod, but I worry that might fail.

**Comment by fasaxc** [comment]
CC @lxpollitt

**Comment by tomdee** [comment]
Is this a bug or an enhancement? We don't try to autodetect the MTU - but we do allow the user to set it.

Is the solution here better documentation around MTUs (esp when used with IPIP) or should the CNI plugin  be gaining an understanding of whether the container could end up using IPIP and what the MTU of the external interface is.

**Comment by MikeSpreitzer** [comment]
I suppose whether it is a bug or an enhancement is a matter that could be debated.  I currently can and do work around the issue, because my automation that deploys Calico can detect the MTU on the relevant host interface, knows whether IPIP is being used, and puts an explicit MTU field in the CNI config.  I was a little surprised that I had to do this.

**Comment by caseydavenport** [comment]
I think to close this we need to update manifests to use the smallest MTU across public clouds.

From this doc (http://docs.projectcalico.org/v2.4/usage/configuration/mtu) that looks like GCE is the target, and our default CNI MTU should be 1440.

Auto-configuration is a potential feature on top of this, but probably should be a separate issue.

**Comment by tmjd** [comment]
The current default MTU is set to 1440, see https://docs.projectcalico.org/v3.10/manifests/calico-typha.yaml and https://docs.projectcalico.org/v3.10/manifests/calico.yaml, so I'm going to close this issue.
