### ISSUE TITLE
Can not use same file for `etcdKeyFile` & `etcdCertFile`

### ISSUE THREAD

**Issue by lsm** [projectcalico/calicoctl#1433]
## Version

`1.0.0`

## Example `/etc/calico/calicoctl.yml` file

```
apiVersion: v1
kind: calicoApiConfig
metadata:
spec:
  datastoreType: etcdv2
  etcdEndpoints: https://etcd1:2379,https://etcd2:2379,https://etcd3:2379
  etcdKeyFile: /etc/tls/etcdclientpem
  etcdCertFile: /etc/tls/etcdclientpem
  etcdCACertFile: /etc/tls/etcdca
```
Where `/etc/tls/etcdclientpem` contains both tls `key` and `cert`.

## Command to reproduce
`sudo calicoctl node run --config /etc/calico/calicoctl.yml`

## Actual docker command triggered

`docker run --net=host --privileged --name=calico-node -d --restart=always -e ETCD_AUTHORITY= -e ETCD_CA_CERT_FILE=/etc/calico/certs/ca_cert.crt -e CALICO_NETWORKING_BACKEND=bird -e CALICO_LIBNETWORK_ENABLED=true -e CALICO_LIBNETWORK_IFPREFIX=cali -e ETCD_SCHEME= -e ETCD_KEY_FILE=/etc/calico/certs/key.pem -e ETCD_CERT_FILE=/etc/calico/certs/cert.crt -e NODENAME=swarm-node-0 -e NO_DEFAULT_POOLS= -e ETCD_ENDPOINTS=https://etcd1:2379,https://etcd2:2379,https://etcd3:2379 -v /etc/tls/etcdclientpem:/etc/calico/certs/cert.crt -v /var/run/calico:/var/run/calico -v /lib/modules:/lib/modules -v /var/log/calico:/var/log/calico -v /run/docker/plugins:/run/docker/plugins -v /var/run/docker.sock:/var/run/docker.sock -v /etc/tls/etcdca:/etc/calico/certs/ca_cert.crt calico/node:v1.0.0`

## Expected docker command

`docker run --net=host --privileged --name=calico-node -d --restart=always -e NO_DEFAULT_POOLS= -e CALICO_LIBNETWORK_ENABLED=true -e CALICO_LIBNETWORK_IFPREFIX=cali -e ETCD_ENDPOINTS=https://etcd1:2379,https://etcd2:2379,https://etcd3:2379 -e ETCD_AUTHORITY= -e ETCD_CA_CERT_FILE=/etc/calico/certs/ca_cert.crt -e NODENAME=swarm-node-0 -e CALICO_NETWORKING_BACKEND=bird -e ETCD_CERT_FILE=/etc/calico/certs/cert.crt -e ETCD_SCHEME= -e ETCD_KEY_FILE=/etc/calico/certs/key.pem -v /etc/tls/etcdca:/etc/calico/certs/ca_cert.crt -v /etc/tls/etcdclientpem:/etc/calico/certs/key.pem -v /etc/tls/etcdclientpem:/etc/calico/certs/cert.crt -v /var/run/calico:/var/run/calico -v /lib/modules:/lib/modules -v /var/log/calico:/var/log/calico -v /run/docker/plugins:/run/docker/plugins -v /var/run/docker.sock:/var/run/docker.sock calico/node:v1.0.0`

What we missed is: `-v /etc/tls/etcdclientpem:/etc/calico/certs/key.pem`

## Error log
```
goroutine 1 [running]:
panic(0x12f08c0, 0xc4203fb1b0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main()
	/go/src/github.com/projectcalico/calico-containers/calico_node/startup.go:42 +0x50b
Calico node failed to start
time="2016-12-30T08:21:54Z" level=info msg="Creating Calico client" 
time="2016-12-30T08:21:54Z" level=info msg="Loading config from environment" 
panic: Error creating client: open /etc/calico/certs/key.pem: no such file or directory
```

**Comment by caseydavenport** [comment]
@gunjan5 looks like there's a bug in the mounts generated by `calicoctl`.

**Comment by gunjan5** [comment]
@lsm so seems like the config file isn't correct. after talking to @robbrockbank turns out it is suppose to be a full path to the files for all 3 of those. See the example below:
```
 etcdKeyFile: /etc/calico/key.pem
  etcdCertFile: /etc/calico/cert.pem
  etcdCACertFile: /etc/calico/ca.pem
```
http://docs.projectcalico.org/v2.0/reference/calicoctl/setup/etcdv2

**Comment by lsm** [comment]
@gunjan5 Yes.  That's the setup when you have **separate** key and cert files.  Sometimes you can put both `key` and `cert` in **one** file, let's say:

`/etc/calico/key-cert.pem`

then use the same file path for `etcdKeyFile` and `etcdCertFile` like this:
```
etcdKeyFile: /etc/calico/key-cert.pem
etcdCertFile: /etc/calico/key-cert.pem
```
This works for a lot of programs AFAK (`mongo`, `etcd`, `docker` etc.) but not for `calicoctl`@1.0.0. Seems the patch you pushed 2 days ago should have this fixed. Thanks!

**Comment by gunjan5** [comment]
@lsm you're right, we should support that. The only concern is some old python libraries didn't support having them all in one file. We have one last bit of python code in Calico which should be replaced by Go soon (hopefully within a week) then we could test this out and merge the PR. 

Re-opening this issue and the PR.

**Comment by gunjan5** [comment]
Just tested this again since all the python code (startup) is replaced by Go.
I created all separate files for key, cert and CA first, that seemed to work, then I had a combined file for key and cert into a single file and that seemed to work as well:

``` sudo ./dist/calicoctl -l debug node run --config=cfg.yaml
INFO[0000] Log level set to debug
INFO[0000] Loading config from JSON or YAML data
INFO[0000] Datastore type: etcdv2
INFO[0000] Include docker networking volume mounts
INFO[0000] Running in container

Running the following command to start calico-node:

docker run --net=host --privileged --name=calico-node -d --restart=always -e NODENAME=node-01 -e NO_DEFAULT_POOLS= -e CALICO_LIBNETWORK_ENABLED=true -e ETCD_SCHEME= -e ETCD_KEY_FILE=/etc/calico/certs/key.pem -e CALICO_NETWORKING_BACKEND=bird -e CALICO_LIBNETWORK_IFPREFIX=cali -e ETCD_ENDPOINTS=https://127.0.0.1:2379 -e ETCD_AUTHORITY= -e ETCD_CA_CERT_FILE=/etc/calico/certs/ca_cert.crt -e ETCD_CERT_FILE=/etc/calico/certs/cert.crt -v /var/log/calico:/var/log/calico -v /var/run/calico:/var/run/calico -v /lib/modules:/lib/modules -v /run/docker/plugins:/run/docker/plugins -v /var/run/docker.sock:/var/run/docker.sock -v /home/vagrant/go/src/github.com/projectcalico/calicoctl/certs/ca.pem:/etc/calico/certs/ca_cert.crt -v /home/vagrant/go/src/github.com/projectcalico/calicoctl/certs/client-key-cert.pem:/etc/calico/certs/key.pem -v /home/vagrant/go/src/github.com/projectcalico/calicoctl/certs/client-key-cert.pem:/etc/calico/certs/cert.crt quay.io/calico/node:latest
```

**Comment by lsm** [comment]
Thank you @gunjan5 you are the best.  I'm wondering when this can be merged to master.

**Comment by gunjan5** [comment]
@lsm I'm hoping it would be merged in next 2 days since @robbrockbank who is the reviewer for the PR is on vacation

**Comment by gunjan5** [comment]
@lsm sorry it took us so long. It's in master now. Let me know if you still see the issue.

**Comment by lsm** [comment]
@gunjan5 No worries.  It's a minor issue which could be solved by using two separate files.  Thanks a lot for fix it!
