### ISSUE TITLE
display valid resource types as list in `calicoctl get --help`

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calicoctl#1436]
I always find it difficult to locate the valid resource types in `calicoctl get --help` output.

Can we move them into a bulleted list instead of a comma-separated list?

**Comment by caseydavenport** [comment]
Yes, I think this would be better.

**Comment by djosborne** [comment]
@robbrockbank Can we bump priority on this? I think it's an easy fix and would make a big impact on usability.
