### ISSUE TITLE
system test container should be versioned

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/calicoctl#1440]
calico/test container is used without a tag at the moment which always pulls the latest container, this is a problem specifically when there's a hotfix patch (for example in one of the python stable versions).
Hotfix patch shouldn';t have to change that part of the makefile.

We need some release process to make sure we tag the calico/test container and use that tag in the Makefile for testing just like how we specify other container image versions

**Comment by gunjan5** [comment]
After talking to @lwr20 it seems like this may not be a problem moving forward since STs have moved into the same repo (calicoctl) now, so won't need to pull the calico/test container. 
However, I would still want to keep the calico/node image on Dockerhub since it will be required whenever we do a hotfix release (like 1.6.2 or 2.0.2 for example)

I think it's ok to close this issue now.

**Comment by tomdee** [comment]
@gunjan5 Do you mean calico/node image or calico/test image?

**Comment by gunjan5** [comment]
@tomdee I meant calico/test, oops
