### ISSUE TITLE
Expand calico.cfg support

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calicoctl#1441]
This is a request to expand support for `/etc/calico/calicoctl.cfg` to other components, namely `calico/node` and Calico-CNI.

@caseydavenport @robbrockbank

**Comment by robbrockbank** [comment]
@tmjd  - is this what you're currently working on?

**Comment by tmjd** [comment]
Yes though I didn't know this issue existed.  I've been working 'under' https://github.com/projectcalico/calico/issues/563

**Comment by caseydavenport** [comment]
Yep, this is a duplicate
