### ISSUE TITLE
calicoctl node checksystem should check ALL the kernel modules required

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/calicoctl#1444]
Right now it only checks for the kernel version (required for network namespace), and `xt_set` and `ip6_tables` kernel modules, but it needs more kernel modules that we just assume are present in the kernel, but not always the case. 
See: https://github.com/kubernetes/minikube/issues/973
& https://github.com/kubernetes/minikube/pull/972

- [ ] update calicoctl node checksystem code to check all the required modules
- [ ] update calico docs to add a pre-requisite list

**Comment by gunjan5** [comment]
Related issue https://github.com/projectcalico/calicoctl/issues/905
- [ ] update calico docs to add a pre-requisite list

**Comment by gunjan5** [comment]
Another related issue (but for felix) https://github.com/projectcalico/calicoctl/issues/1242

**Comment by tmjd** [comment]
Reviewed. This still seems like a valid request and is at the correct priority.

**Comment by mhmxs** [comment]
> Related issue #905

This issue is closed because the module is not used any more.

**Comment by mhmxs** [comment]
I would like to fix this issue (it looks good for newbies) and as I followed the attached tickets it seems today `ip_set` module is the only one to add to checks. Am i right? I also want to ask that `calicoctl` loads the module [here](https://github.com/projectcalico/calicoctl/blob/5f53743a7214ea5193a788c1ed9f93d89c731c0e/calicoctl/commands/node/run.go#L425). Have i also add the new module(s) to load? I guess yes :)

**Comment by tmjd** [comment]
Yeah I think adding to the modules to load is correct.

I'm not sure if that is the only one to add or how to figure out which ones we depend on.
@fasaxc or @caseydavenport would either of you have any suggestions on how to figure out the modules felix depends on.

**Comment by fasaxc** [comment]
There's a list here; that'd be a good starting point. https://docs.projectcalico.org/v3.9/getting-started/bare-metal/requirements#kernel-dependencies

In addition, there are the `xt_XXX` modules for each match and action that we use.  Everywhere that there's a `-m <some match type>` in [this file](https://github.com/projectcalico/felix/blob/master/iptables/match_builder.go), there'll be an `xt_<some match type>` module that's required.  Those modules are loaded on demand by the `iptables` command.

One thing that makes this difficult is that it's also possible for all fo these modules to be compiled into the kernel.  In that case, loading them will fail but they're still there.

**Comment by mhmxs** [comment]
Thanks @fasaxc,

seems many of the modules are not checked/loaded yet. Can i ask what does it mean "ipip (if using Calico networking)"? Is there any existing logic to check this behavior?

**Comment by mhmxs** [comment]
@fasaxc I was researching in the topic of loading build in modules with modprobe. And i found this documentation. https://www.kernel.org/doc/Documentation/kbuild/kbuild.txt.
```
modules.builtin
--------------------------------------------------
This file lists all modules that are built into the kernel. This is used
by modprobe to not fail when trying to load something builtin.
```

I tried to load a module with `modprobe` and it didn't fail at all.
```
root@ubuntu-bionic:/home/vagrant# cat /lib/modules/$(uname -r)/modules.builtin | grep sha512_generic
kernel/crypto/sha512_generic.ko
root@ubuntu-bionic:/home/vagrant# modprobe sha512_generic
root@ubuntu-bionic:/home/vagrant# echo $?
0
```
Do you remember where did you face with the modul lode fail or any advice how to reproduce it?

**Comment by mhmxs** [comment]
@fasaxc Could you please answer my question? Seems i will have some time next week and would be nice to done this :) Thanks

**Comment by fasaxc** [comment]
One issue is that we run things inside containers where the modprobe that is inside the container may not have access to the modules.build.  Also possible that I've been confused by modules being added and removed form the kernel entirely.  For example, we used to need some nf_conntrack_XYZ modules but some of those can no longer be built as modules, I think.

**Comment by mhmxs** [comment]
Hi @ozdanborne,

You closed this issue but i think there is one more open question. So in the documentation i found an optional kernel [module](https://github.com/mhmxs/calico/blame/7609d8952c9ec8493e63365cdaf3f45bca18b5bc/_includes/master/reqs-kernel.md#L24). That modul is not counted in the list of [checks](https://github.com/projectcalico/calicoctl/pull/2090/files#diff-1270cc1a1b5c264917b10bdbdc71e6edR36). I'm not sure how to check the `if using calico networking` in code level. What is your advice?

Thanks.
