### ISSUE TITLE
Allow default pool configuration to be configurable

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calicoctl#1445]
It might be useful if we allow the default pool configuration to be configurable when starting up the calico/node.

I'm not 100% convinced about this, but raising issue for discussion.

For example, we could add additional envs that specify the pool CIDRs and IPIP config for the default IP pools - so if an IP pool does not exist create it with the specific config.

**Comment by gunjan5** [comment]
+1. Sounds like a good idea. Besides being an env var we could also add it as a flag for calicoctl node run so it's well documented. `--initial-ippool=<CIDR>` something like that

**Comment by caseydavenport** [comment]
I think this would be pretty useful.  Currently in k8s we need to run a Job to configure the desired Pool.  This would mean we don't have to do this.

An environment variable would work.  We could also consider creating a Pool based on a file in the container's filesystem.  You could then mount in the pool you want to create to override the default.

**Comment by caseydavenport** [comment]
I think for starters we can support (with defaults as shown)

```
CALICO_IPPOOL_CIDR="192.168.0.0/16"
CALICO_IPIP_ENABLED=false
```

**Comment by tmjd** [comment]
A few points of clarification after discussing with @caseydavenport:
* There will be two env variables for the IP pools.  CALICO_IPV4POOL_CIDR and CALICO_IPV6POOL_CIDR
 * If one of the above env variables is set and NO_DEFAULT_POOLS is set then terminate as an invalid configuration.

**Comment by robbrockbank** [comment]
@tmjd Can this be closed now?  I think so, but just want to check.

**Comment by tmjd** [comment]
I was leaving this to cover adding a setting for NAT configuration on the default pool but #1580 exists.  So yep, time to close.
