### ISSUE TITLE
Kubernetes - Selectable IPPool

### ISSUE THREAD

**Issue by rikatz** [projectcalico/calicoctl#1452]
Don't know if is there some other issue opened here, so here's a feature request/suggestion:

It would be great if I could select, in Kubernetes, which ippool my container is going to use, according to some annotation on the POD spec.

Some other solutions does implement this (I've seen this operational in contiv -> https://github.com/contiv/netplugin/tree/b5fd3d3dc4bd8fefff3f51d8229953650cdc67db/mgmtfn/k8splugin#example-2-use-network-labels-to-specify-a-network-and-epg-for-the-pod), where you put an annotation and POD becames a part of the selected network.

This is not the same as issue #1445 

So here would be the workflow:

- Sys Admin configures additional ip pools (like 10.111.0.0/16)
- Developer does a deployment, and makes an annotation like 'calico.network: 10.111.0.0/16'
- Container is started with something like '10.111.222.23'

If the POD doesn't have the desired network, container should be created on some default defined network (maybe on CNI config?)

Thanks!

**Comment by caseydavenport** [comment]
@rikatz thanks for raising!

I think you're actually looking for pretty much exactly this issue:
https://github.com/projectcalico/cni-plugin/issues/213

And a similar, related issue: https://github.com/projectcalico/cni-plugin/issues/212

There is a WIP PR from the community to add this feature, so it should be in the next release: https://github.com/projectcalico/cni-plugin/pull/223
