### ISSUE TITLE
Need a single command to report all Calico sub-component versions

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/calicoctl#1454]
It's difficult to debug user environments where there might be version mismatches.
A single command to report all the Calico component versions would be _**really**_ useful.

See a request from a user in our slack channel:
https://calicousers.slack.com/archives/kubernetes/p1484233079002139

Something like:
```
calicoctl calico versions
Felix                   vX.X.X
CNI                    vX.X.X
libnetwork         vX.X.X
BIRD                  vX.X.X
GoBGP              vX.X.X
k8s-policy-ctrl  vX.X.X
```

**Comment by tomdee** [comment]
I've added `docker run calico/node versions`.

It might be good to add a `calicoctl node versions` command or something which calls this.
