### ISSUE TITLE
startup-go fails with etcdless k8s backend 

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/calicoctl#1457]
```
$ kubectl logs calico-node-sp4bb -c calico-node -n kube-system
time="2017-01-20T19:06:31Z" level=info msg="NODENAME environment not specified - check HOSTNAME"
time="2017-01-20T19:06:31Z" level=info msg="Loading config from environment"
Skipping datastore connection test
Calico is using a Kubernetes datastore
time="2017-01-20T19:06:31Z" level=info msg="Ensuring ThirdPartyResources exist"
time="2017-01-20T19:06:31Z" level=info msg="ThirdPartyResources exist"
time="2017-01-20T19:06:31Z" level=info msg="Ensuring ClusterType is set"
time="2017-01-20T19:06:31Z" level=info msg="ClusterType is set"
time="2017-01-20T19:06:31Z" level=info msg="Using previously configured cluster GUID"
time="2017-01-20T19:06:31Z" level=info msg="Kubernetes is initialized as a Calico datastore"
time="2017-01-20T19:06:31Z" level=info msg="Loading config from environment"
time="2017-01-20T19:06:31Z" level=fatal msg="Unable to retrieve IPIP tunnel address for cleanup" error="Get for HostConfig not supported in kubernetes backend"
Calico node failed to start
```

**Comment by spothanis** [comment]
I too am hitting this, anyway to work around till the actual fix lands?

**Comment by caseydavenport** [comment]
Hm.  Looks like this is the line causing the problem: https://github.com/projectcalico/libcalico-go/blob/master/lib/backend/k8s/k8s.go#L684

We can probably change that line to return a nil value for all host config.  The code that allocates / removes IPIP tunnel addresses should handle that case correctly.

https://github.com/projectcalico/calicoctl/blob/master/calico_node/allocateipip/allocate_ipip_addr.go#L80

**Comment by caseydavenport** [comment]
This should be fixed in libcalico-go v1.0.2, but needs to be re-tested, so leaving open for now.

**Comment by fasaxc** [comment]
I just tried to spin up a k8s cluster with `calico/node:2.1.0-rc1` and I hit the above error.

**Comment by fasaxc** [comment]
I checked the 2.1.0-rc1 tag in this repo, its glide.yaml is pinned to an older commit, not v1.0.2.

**Comment by fasaxc** [comment]
Fixed in rc3 after resolving another issue.
