### ISSUE TITLE
Automatically detect Kubernetes pod CIDR, create IP Pool

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calicoctl#1464]
It would be great if we could detect what the cluster CIDR being used by a given Kubernetes cluster is and ensure that the necessary IP Pool exits automatically.

At the moment, this is configurable in the Calico self-hosted manifests and is run as a "Job" to perform one time configuration.

I'd like to be able to remove that requirement, and have the `calico/node` Pod do that automatically based on the k8s API.

This probably needs changes to the k8s API in order to get the cluster CIDR (if one is configured).

Alternatively, we could create a lot of different IP Pools (one per-node), since the node.PodCIDR is actually in the API for us to consume.

**Comment by jayunit100** [comment]
So, It seems like the *simplest thing that could possibly work* would be to use PODCidr.  Should we just go with that? 

(some bikeshedding below)

- why would we use the parsing down apiserver stuff,  if we get PODCidr for free ?  

PODCidr is more likely to be correct, and less likely to be interpretted the wrong way, and requires no information about global state.

- If we go the route of using the apiserver ...  doesnt `kubectl cluster-info` give us this stuff nowadays ?

**Comment by caseydavenport** [comment]
There isn't a 100% guaranteed "this will work everywhere" sort of solution, since the full cluster CIDR isn't a part of the k8s API. However, there are a few things we can leverage:

- kubeadm config map (for kubeadm systems)
- kube-proxy config map (for systems which use it)

Might also be worth considering if there are any other similar mechanisms we could latch on to in addition to those, but I think the two above are a good start.

**Comment by caseydavenport** [comment]
We do actually have logic for this for kubeadm clusters now. 

Let's track any additional environments as separate issues, given there are a large number of potential ways to install a cluster and each may have different ways this needs to be done.

**Comment by rkamudhan** [comment]
@caseydavenport Could you please explain the logic how the calico find the pod-cidr from kubeadm init command ?

**Comment by rkamudhan** [comment]
@caseydavenport this information available inside the kubeadm-config. I got my answer.
