### ISSUE TITLE
Calicoctl should pass through some environment variables automatically when starting node

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calicoctl#1501]
IIUC, `calicoctl node run` already passes through environment variables prefixed with `FELIX_` when running the `calico/node` image. Libnetwork-plugin uses environment variables prefixed with `CALICO_` so `calicoctl` should pass those through too.

**Comment by caseydavenport** [comment]
This is confusing with the existing flags that we've already got.  I think we should close this, especially since we're not really recommending `calicoctl node run` for prod clusters.
