### ISSUE TITLE
docker run command printed by calicoctl node run is longer than it needs to be

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calicoctl#1520]
`calicoctl node run` prints a `docker run` command that's longer than it needs to be e.g. 
```docker run --net=host --privileged --name=calico-node -d --restart=always -e NO_DEFAULT_POOLS= -e CALICO_LIBNETWORK_ENABLED=true -e CALICO_LIBNETWORK_IFPREFIX=cali -e ETCD_AUTHORITY=127.0.0.1:2379 -e ETCD_SCHEME=http -e ETCD_ENDPOINTS= -e NODENAME=xeon -e CALICO_NETWORKING_BACKEND=bird -v /var/log/calico:/var/log/calico -v /var/run/calico:/var/run/calico -v /lib/modules:/lib/modules -v /run/docker/plugins:/run/docker/plugins -v /var/run/docker.sock:/var/run/docker.sock quay.io/calico/node:v1.1.0-rc3```

I'm not sure that we really need to pass in `-e NO_DEFAULT_POOLS=` `-e CALICO_LIBNETWORK_IFPREFIX=cali` and all of those ETCD_ ones (let's just use ETCD_ENDPOINTS)

**Comment by matthewdupre** [comment]
Aren't a bunch of those values the default anyway?  We could just try and squelch defaulted environment variables.

**Comment by tomdee** [comment]
I'm going to reopen this as I think the docker run command is still longer than it needs to be. Current output is now:
```
docker run --net=host --privileged --name=calico-node -d --restart=always -e CALICO_LIBNETWORK_IFPREFIX=cali -e ETCD_ENDPOINTS=http://127.0.0.1:2379 -e NODENAME=xeon -e CALICO_NETWORKING_BACKEND=bird -e CALICO_LIBNETWORK_ENABLED=true -e CALICO_LIBNETWORK_CREATE_PROFILES=true -e CALICO_LIBNETWORK_LABEL_ENDPOINTS=false -v /var/log/calico:/var/log/calico -v /var/run/calico:/var/run/calico -v /lib/modules:/lib/modules -v /run/docker/plugins:/run/docker/plugins -v /var/run/docker.sock:/var/run/docker.sock quay.io/calico/node:latest```

The libnetwork ones aren't going to be used by lots of people and they are all just being set to the defaults (I think) so would be good to get rid of.

**Comment by bcreane** [comment]
I'll take another pass through the CALICO_LIBNETWORK variables.

**Comment by bcreane** [comment]
Hey @tomdee, with the latest PR, the default "node run" output is:

```docker run --net=host --privileged --name=calico-node -d --restart=always -e CALICO_NETWORKING_BACKEND=bird -e CALICO_LIBNETWORK_ENABLED=true -e ETCD_ENDPOINTS=http://127.0.0.1:2379 -e NODENAME=bcreane-vm-dev -v /var/log/calico:/var/log/calico -v /var/run/calico:/var/run/calico -v /lib/modules:/lib/modules -v /run/docker/plugins:/run/docker/plugins -v /var/run/docker.sock:/var/run/docker.sock quay.io/calico/node:latest```

I think this is as spare as we can get without changing the default settings in other repos.
I'm going to close the bug, but please re-open if you see some additional settings I missed.
