### ISSUE TITLE
IP autodetection tests don't go far enough

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calicoctl#1528]
While the tests of interface autodetection in: https://github.com/projectcalico/calicoctl/blob/master/tests/st/calicoctl/test_autodetection.py are great, they don't actually test the logic of the selection algorithm.

For example, I think they wouldn't spot if (for example):
- the flag was being ignored and the first-found algorithm was being used for all the settings.
- the algorithm was always selecting the last interface

I would suggest enhancing the tests to create a host with multiple interfaces in it.  See https://github.com/projectcalico/calicoctl/blob/master/tests/st/policy/test_felix_gateway.py for an example.  You can then run the various algorithms and grep the calico-node logs to check that the IP corresponding to the expected interface was selected.  For interface regex testing, the interfaces could be renamed (using an `ip link` command).

I think we need to do this to avoid building up technical debt and having to test that this feature has not regressed every time we do a release in future.

**Comment by tomdee** [comment]
Discussed with Rob and given the amount of manual testing, we're OK to slip this till after v2.1

**Comment by lwr20** [comment]
Really needs to be in v2.2.0 then to avoid increasing our testing backlog.
