### ISSUE TITLE
Default IPv6 pool gets NAT outgoing

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calicoctl#1536]
I run calico-node with:
`$ docker run --net=host --privileged --name=calico-node -d --restart=always -e IP_AUTODETECT_METHOD=first-found -e CALICO_LIBNETWORK_CREATE_PROFILES=true -e CALICO_LIBNETWORK_LABEL_ENDPOINTS=false -e CALICO_LIBNETWORK_IFPREFIX=cali -e NODENAME=drogon -e CALICO_NETWORKING_BACKEND=bird -e CALICO_IPV6POOL_CIDR=fd00::1:0/120 -e CALICO_LIBNETWORK_ENABLED=true -e IP6_AUTODETECT_METHOD=first-found -e ETCD_AUTHORITY=127.0.0.1:2379 -e ETCD_SCHEME=http -e ETCD_ENDPOINTS= -v /var/log/calico:/var/log/calico -v /var/run/calico:/var/run/calico -v /lib/modules:/lib/modules -v /run/docker/plugins:/run/docker/plugins -v /var/run/docker.sock:/var/run/docker.sock quay.io/calico/node:v1.1.0-rc5`

This causes the creation of 2 pools:
```
$ ./calicoctl get ippools -o yaml
- apiVersion: v1
  kind: ipPool
  metadata:
    cidr: 192.168.0.0/16
  spec:
    nat-outgoing: true
- apiVersion: v1
  kind: ipPool
  metadata:
    cidr: fd00::1:0/120
  spec:
    nat-outgoing: true
```
But should the IPv6 pool be getting `nat-outgoing: true`?  With IPv6 there should be enough addresses to make NAT unnecessary?

**Comment by tmjd** [comment]
There are enough addresses but wouldn't the reason for having `nat-outgoing: true` so that the "router" doesn't have to be peered with the cluster for outgoing traffic to make it back to the container that it originated from?

**Comment by lwr20** [comment]
Yep - makes sense.  

@fasaxc says that in the 'real world' you ought to be assigning an IPv6 range to a host and then assigning IPs to containers on that host out of that range.  Apparently that works without peering.  Or they could just BGP peer with external routers. 

But regardless of the 'good' ways to handle this, there will be those who cannot configure anything about their system, and for them this is a safe default.  Closing.
