### ISSUE TITLE
Can not set FailsafeInboundHostPorts to nothing using calicoctl

### ISSUE THREAD

**Issue by bradbehle** [projectcalico/calicoctl#1559]
I don't want any inbound ports open by default for my host endpoint policies.  I am following the following instructions:
http://docs.projectcalico.org/v2.0/getting-started/bare-metal/bare-metal#failsafe-rules
and
http://docs.projectcalico.org/v2.0/usage/configuration/

This shows how to change the ports that are open for failsafe inbound and outbound, but I haven't found a way to remove all the ports from the list.  I've tried setting the FailsafeInboundHostPorts to empty string, but that doesn't work.  I tried doing unset, but that just ends up putting port 22 back in the iptables rules.

If there is not a way, I think this is an important thing to make available.  If there is a way, please document it in one of the links above.

**Comment by tomdee** [comment]
@fasaxc I think you added this feature - can you comment on this issue?

**Comment by fasaxc** [comment]
@bradbehle You need to set the value to the string "none";  empty string means "use the default". I'll update the docs.
