### ISSUE TITLE
Using calicoctl it should be possible to add additional IP addresses to a container

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calicoctl#1561]
It would be useful to be able to add multiple IP Addresses to a container using calicoctl with different policies applied.  Using Calico with OpenStack this is allowed and it existed previously but the functionality was dropped so it is obviously possible.

For reference, this support issue #1116 spawned creation of this feature request.

Since the feature previously existed and was dropped when the UI changed I understand this may be a `wontfix` request.

**Comment by tomdee** [comment]
I don't really understand the use case for having different policies applied from the same container. Having multiple interfaces in the container is pretty difficult for app developers to work with so something that we probably want to avoid.

**Comment by tmjd** [comment]
I guess the part about having different policies applied for the different IP Addresses could be dropped from this feature but I think it would be nice for the use case laid out in #1116.

If you could add multiple IP Addresses but the same policy was applied to all of them then each new app that the load balancer handled could require updating the one common policy.
Whereas if each IP Address added used a different policy then there could be a policy for each app and that would apply to only that IP Address.  Again, not necessary, because you would probably want to duplicate those same restrictions on the LB's access to the app.

> Having multiple interfaces in the container is pretty difficult for app developers to work with so something that we probably want to avoid.

I think someone writing/using a load balancer as described in the issue would have to be aware of and tackle the difficulties that come with multiple interfaces.

**Comment by caseydavenport** [comment]
I'm going to close this as wontfix for now.  We can always re-open if we find a need.
