### ISSUE TITLE
calicoctl launches a different image than the one created by `make calico/node`

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calicoctl#1566]
- `make calico/node` produces a docker image tagged as `calico/node`
- `make dist/calicoctl` produces a binary of calicoctl which launches `quay.io/calico/node`.

Therefore running `make dist/calicoctl calico/node; dist/calicoctl node run` will pull and run a separate calico/node image than the one just created.

I found this unintuitive. It looks like `make semaphore` compensates for this by retagging images. but locally this compensation does not automatically happen.

**Comment by robbrockbank** [comment]
Yup,

I originally checked in a change that tagged calico/node as quay.io/calico/node in #1490 
 
But was asked to undo it in #1499 - however, after a little more discussion we decided it would bo ok to go in, so we probably just need to redo the original checkin.  It's a little odd to tag an image as quay.io when it isn't, but then this only affects local builds and (IMHO) I think it is perfectly reasonable for that purpose.

**Comment by djosborne** [comment]
Yeah I think that if `calicoctl node run` launches `quay.io/calico/node`, then our build scripts should be using that same image name.

**Comment by caseydavenport** [comment]
Closing now since we've removed the dependency on calico/node from calicoctl.
