### ISSUE TITLE
contributor agreement text

### ISSUE THREAD

**Issue by jlovejoy** [projectcalico/calicoctl#1573]
There doesn't not seem to be a way to review your contributor license agreement before actually submitting a pull request.  Can you provide a copy somewhere or link?  These pages just note that there is now a single CLA and how the process has changed, but also don't indicate what the new CLA is.
thanks!

**Comment by tmjd** [comment]
I believe this is what you are looking for.
https://cla-assistant.io/projectcalico/calicoctl
