### ISSUE TITLE
calico/node:v1.1 changes FELIX_DEFAULTENDPOINTTOHOSTACTION default from RETURN to DENY

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calicoctl#1575]
I've found that in both an openshift (k8s 1.4) a kubeadm cluster (k8s 1.5),  FELIX_DEFAULTENDPOINTTOHOSTACTION=ACCEPT must be explicitly set. Otherwise, pods started on the master are unable to speak to the Kubernetes API. 

In both environments, this flag did not need to be specified when using calico/node:v1.0.0. It was only upon upgrading to calico/node:v1.1.0 that the value needed to be explicitly set.

I think the connectivity issue that this causes will be tricky for newer users to diagnose as it took me awhile to narrow down that it was k8s-master only, and furthermore is commonly diagnosed by reading iptables chain packet counts, which can be a bit tricky for newer users. Furthermore, users performing a simple calico/node version bump upgrade could see their connectivity impacted unless they add this variable.

cc: @fasaxc

**Comment by caseydavenport** [comment]
@djosborne I believe all of our k8s manifests set this field to ACCEPT.

What is your desired outcome for this issue?

**Comment by djosborne** [comment]
The Canal manifest currently does not. Sure, we should update it. But I also worry about users rolling their own Calico deployments themselves and may not include this variable, or users on other orchestrators where clean installation instructions are not provided. For example, Mesos users will hit this as well since Tasks in mesos make a network connection to the agent to register.

**Comment by djosborne** [comment]
@fasaxc do you have any insight on why this changed?

**Comment by lusche** [comment]
+1 this problem should be addressed, I run into it as new user and struggle to find the solution

**Comment by djosborne** [comment]
Calico v2.1 switched from a python startup script using the python libcalico, to a golang one using the golang libcalico-go.

Seems this bit of code was left out of the libcalico-go port: https://github.com/projectcalico/libcalico/blob/2bf36b33dd5a754fec10d3d96dce16ec79ed2a39/calico_containers/pycalico/datastore.py#L406-L408

**Comment by caseydavenport** [comment]
> Remove FELIX_DEFAULTENDPOINTTOHOSTACTION=ACCEPT from k8s install yamls as the restored default value should be sufficient.

I think ACCEPT is the correct value for k8s, provided it can easily be changed (which it can).

Fixing the default in startup.go to be RETURN is still the right thing to do though.

> Enhance Felix documentation to explain the impact of this variable to users and how they could go about modifiying it depending on their deployment.

I think there's already reference docs (which may need to be updated with more context).

**Comment by fasaxc** [comment]
I added some more context to the docs under this PR: https://github.com/projectcalico/calico/pull/639

**Comment by libby** [comment]
+1 this confused me for a day+ until I stumbled on a slack discussion that pointed this out.  For this kind of situation it would be nice to have the ability to pass arbitrary env vars to calicoctl for the docker calico-node container.

**Comment by tmjd** [comment]
@libby There is this work https://github.com/projectcalico/calicoctl/pull/1511 in progress.  Not arbitrary env vars but would work in this case.

**Comment by djosborne** [comment]
Default has been restored in current master. Fix coming in `calico/node:v1.1.1` which will be included in Calico v2.1.2.

**Comment by djosborne** [comment]
Fix has been released in `calico/node:v1.1.1` and install instructions on docs.projectcalico.org/v2.1 have been updated to use it :shipit:
