### ISSUE TITLE
Support disabling NAT in default ip pool

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calicoctl#1580]
NATOutgoing is hard-coded to be enabled in the default pool: https://github.com/projectcalico/calicoctl/blob/master/calico_node/startup/startup.go#L564

This is the right default, but some users may want to disable it.

I think we should have a `CALICO_NAT_OUTGOING` variable or similar to control this.

@tmjd WDYT? Was there a reason we didn't add this in v2.1?

**Comment by tmjd** [comment]
No specific reason, I was just keeping the changes to the minimum I needed to do at the time.  I totally agree we should have it.

**Comment by tmjd** [comment]
There is a docs issue for this too https://github.com/projectcalico/calico/issues/516

**Comment by VincentS** [comment]
Should it be possible to be able to differentiate between ipv4 and ipv6 pool? Meaning  that we have an CALICO_NAT_OUTGOING_IPV6 and CALICO_NAT_OUTGOING_IPV4 variable or is one CALICO_NAT_OUTGOING for both pools enough?

**Comment by tmjd** [comment]
Yes I would imagine NAT_OUTGOING should have an IPV4 and IPV6 variable like the other CALICO_IPV*POOL_* variables for configuring default pools.  @caseydavenport is there any reason you would expect otherwise?

**Comment by VincentS** [comment]
My current pull request only introduces the parameter CALICO_NAT_OUTGOING which sets `nat-outgoing`for both IPv4 and IPv6 default IPPools.

**Comment by VincentS** [comment]
This issue should be solved by https://github.com/projectcalico/calico/pull/861
