### ISSUE TITLE
Alpha GoBGP support for v2.2.0

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/calicoctl#1589]
This issue is to track STs/QA and docs changes needed for GoBGP support in **v2.2.0**:

**STs**:
- https://github.com/projectcalico/calicoctl/issues/1581
- https://github.com/projectcalico/calicoctl/pull/1553
- https://github.com/projectcalico/calicoctl/pull/1359
- #1601 
- Some resilience STs WIP by @frnkdny 

**QA**:
- full mesh
- IPIP
- Route summarization
- playtime to see if the correct routes get exported with different IP Pools

**Scale testing**
- likely just running the scale tests with `CALICO_NETWORKING_BACKEND=gobgp`

**Docs**:
- Mention GoBGP at least where BIRD is mentioned
- Any special config options specific to GoBGP? 
- See https://github.com/projectcalico/calico/issues/234 for more details

/CC @tomdee @robbrockbank @ishidawataru

**Comment by ishidawataru** [comment]
@gunjan5 Please add https://github.com/projectcalico/calicoctl/pull/1601 to the list

**Comment by ishidawataru** [comment]
@caseydavenport Why is this closed?

**Comment by caseydavenport** [comment]
@ishidawataru IIUC all of the things being discussed in this issue have been fixed?

If there's more to do here, we should open individual issues for each feature rather than cramming them all into this one - that will make it easier to manage the project.

**Comment by ishidawataru** [comment]
@caseydavenport I see. Thanks.
