### ISSUE TITLE
Can we speed up STs by creating a local DIND image with the uploaded tar files.

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calicoctl#1590]
At the moment, a big chunk of the ST time is taken up by copying in a few tar files and loading in the docker images they contain.

Could we instead, as part of creating the tar file, create a new local DIND image that contains those images pre-loaded?

**Comment by robbrockbank** [comment]
@tomdee - does this sound like a sensible thing to do?  would be nice to get your opinion -- of course may be that we need to just do it and see how much time it saves.

**Comment by tomdee** [comment]
No, it's not possible. Chat to me sometime if you want to understand why it can't be done.
