### ISSUE TITLE
calicoctl as a pod: Calico process is not running

### ISSUE THREAD

**Issue by gaelL** [projectcalico/calicoctl#1594]
Following https://github.com/projectcalico/calicoctl/issues/1418

I have the same kind of issue running a specific pod to run calicoctl.

I'm sharing `/var/run/calico` and `/var/run/bird` volumes but when I try to run a node status I have this result

```
calicoctl node status
Calico process is not running.
```

Looking with `strace` it seems that calicoctl trying to look if we have locally felix and backend (bird in my case) running locally.

```
[pid   934] openat(AT_FDCWD, "/proc/84/stat", O_RDONLY|O_CLOEXEC) = 4
[pid   934] fstat(4, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
[pid   934] read(4, "84 (calico-felix) S 77 77 77 0 -"..., 512) = 311
```
Going inside my container again, I tried to create fake process with those name and run calicoctl again

```
/ # perl -e '$0="calico-felix"; sleep 60' &
/ # perl -e '$0="bird"; sleep 60' &
/ # ./calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 10.1.1.35    | node-to-node mesh | up    | 13:58:37 | Established |
| 10.1.3.208   | node-to-node mesh | up    | 13:58:41 | Established |
+--------------+-------------------+-------+----------+-------------+

INFO: BIRDv6 process: 'bird6' is not running.
```

And it's working.

My quesiton : is calicoctl checking locally to have process like felix is something that we expect ?

My thought is that it should just look for things like `/var/run/calico/bird.ctl` and try to run the command. I don't need local run of that process.

WDYT ?

**Comment by caseydavenport** [comment]
@gaelL looks like calicoctl does an explicit check for the bird or bird6 processes

https://github.com/projectcalico/calicoctl/blob/master/calicoctl/commands/node/status.go#L75

My guess is that you need to share a process namespace with the calicoctl Pod in order for that to work (and is why once you make the fake process it seems to work)

**Comment by gaelL** [comment]
Is it the expected behavior ? I think it could be create that `calicoctl` tend to be a client command like `kubectl`  that you can run outside of your calico node.

Is this check is still required ? Maybe we could also have a `--standalone` to bypasse those checks if calicoctl work as expected without them ?

**Comment by caseydavenport** [comment]
@robbrockbank @gunjan5 do we really need to check if there is a BIRD process running?  Can it be a soft check instead?

>  and tend to be a client command like kubectl who can run outside of your calico node

Yeah, most of the `calicoctl` commands are capable of running from anywhere. It's just the `calicoctl node` commands that currently need to be run on the same node as `calico/node`.

**Comment by tmjd** [comment]
I would think that the communication done with `/var/run/calico/bird.ctl` should be enough for checking on BIRD but I'm not sure what could replace the check for `calico-felix`.  If we can't check on these things there is not really a point to the `calicoctl node status` command though.

**Comment by gunjan5** [comment]
As @caseydavenport said, you'll need to share PID namespace if you want to run any calicoctl node commands inside a container. Yes the process check is to make sure the processes are running before we connect to the socket to get the data and translate it, the main reason being we need to check which BGP daemon is running (BIRD or GoBGP) and we find that by checking which process is running so we can query the appropriate backend  (BIRD or GOBGP). (this is also to avoid adding a `--backend=<something>` everytime you run a calicoctl node status command)

**Comment by tmjd** [comment]
I think there is understanding on what and why the mounts are needed at this time so I'm going to close this issue.  @gaelL if this solution is not satisfactory perhaps you could create a feature request of what you are looking for specifically with your suggested `--standalone` option and the use case for it.  Thanks.

**Comment by kpichardie** [comment]
Hello guys,

I have the same issue here, but there is one thing I don't understand. 

If calico-cli (calicoctl) is checking that the process are running, why did you create docker image for this cli (as it will not work) moreover when this cli isn't on calico-node image.

BTW it's on documentation : https://docs.projectcalico.org/v2.5/getting-started/kubernetes/tutorials/using-calicoctl

Maybe the process check isn't really required for a cli. 

Thanks in advance.

**Comment by tmjd** [comment]
The reason a docker image was created is because there are many other things that calicoctl can be used for other than the `node` commands, like creating/updating/deleting policy and changing many other configuration parameters and none of those do the process check.  See https://docs.projectcalico.org/v2.5/reference/calicoctl/commands/
