### ISSUE TITLE
Don't populate IP / AS in policy-only mode

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calicoctl#1597]
When using policy-only mode (CALICO_NETWORKING_BACKEND=none) we don't need to populate the IP / AS on the Node resource.

**Comment by gunjan5** [comment]
just throwing this out there. What happens if a user who was using policy only mode and now decides to move their network to calico networking? Would it just work?

**Comment by heschlie** [comment]
calico/node would need to be restarted I believe, but I don't think that case is any different than now?  As you would need to get all of the components to start watching the relevant resources for BGP.

**Comment by gunjan5** [comment]
ah ok right, I misunderstood what this change is proposing. Makes sense now
