### ISSUE TITLE
AS number changes on first calicoctl node run

### ISSUE THREAD

**Issue by jdfless** [projectcalico/calicoctl#1609]
calicoctl version 1.0.2 (calico/node version 1.0.2) - calico version 2.0.2

I am seeing my AS number magically change on a fresh build from 64512 to 64511 when I start running calico on my nodes when using a bgp global setup.

Steps to reproduce:
1.) start a routereflector image with bird at 0.2.1
2.) add a global bgp peer with the default AS number (which at this point is 64512)
3.) turn nodeToNodeMesh to off
4.) confirmed the AS number is still 64512
5.) start calico with "calicoctl node run"
6.) the AS number is now 64511 (as seen by calicoctl config get asNumber and calicoctl get nodes -o wide)
7.) calicoctl node status shows the connection as "Active Socket: Connection Refused"

Some notes; if I fix the AS number (calicoctl config set asNumber 64512) or delete and reapply the bgp peer (with the AS number as 64511), the issue resolves itself and does not manifest again, however on freshly built nodes, it is reproducing 100% of the time.

We run on a mix of ubuntu 12.04 and 16.04 VMs without a cloud provider.

**Comment by tmjd** [comment]
Could you try the latest calico version 2.1.2 and see if this problem still exists?  I'm not sure if there has been anything that would fix this but it would be good to know if the latest still has this issue.  Thanks for the report.

**Comment by jdfless** [comment]
I'm not able to check the latest version right now, but I did some more leg work to track down the issue. It looks like when we run "calicoctl config get asNumber" the first time to set the value for our global bgp peer (it returns 64512), that value is not yet set in etcd. Then when the calico nodes try and start, they use the older default value (64511) and set that in etcd.

I fixed this issue by running an explicit set after running the first get. This pushes the value to etcd, and then the calico nodes get that value properly.

**Comment by tmjd** [comment]
@jdfless I'm glad you found a work around for this and thank your for reporting what you did.
I'm going to flag this as a bug because we might want to check on this behavior and if nothing else document it.

**Comment by caseydavenport** [comment]
This is a result of using calico/node:v1.0.2, which still uses some old startup.py code to write the global AS number to the datastore, whereas newer version of Calico don't write the value to the datastore and assume an empty value means "use the default".  

This will be fixed by upgrading calico/node 1.1.0+

* Python code: https://github.com/projectcalico/libcalico/blob/2bf36b33dd5a754fec10d3d96dce16ec79ed2a39/calico_containers/pycalico/datastore.py#L280
