### ISSUE TITLE
Released calico/node image may be being rebuilt

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calicoctl#1615]
I noticed that the `calico/node:v1.1.2-rc2` image on DockerHub was “Last updated” 4 hours ago, but I thought we built it last week; is there a script mis-firing somewhere?

https://hub.docker.com/r/calico/node/tags/

Looks like master is currently at that tag; maybe our periodic rebuild of master is re-pushing that tag too?  (Or maybe it's just a quirk of the docker UI.)

**Comment by tmjd** [comment]
Right now master and v1.1.2-rc2 are at the same commit hash.  So maybe the rebuilding & pushing of master updates the 'Last updated' on the tag too.

**Comment by tomdee** [comment]
Yep, I can't see that there's an actual issues so closing (but thanks for raising @fasaxc). Let's reopen if we see a tag being rebuilt when it's not at the same hash commit as master.
