### ISSUE TITLE
Change working directory for calico/ctl container

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calicoctl#1617]
I find that I often run an interactive shell in the calico/ctl container, and manipulate yaml for calico objects. I have two gripes when I do this:

1. ~~Calicoctl is not in `$PATH`, so I must use the full path name~~
2. The default working directory for `calico/ctl` is `/`, so unless I `cd` into `$HOME` , When I save and manipulate yamls, I'm doing it in root alongside important files.

I think it'd be nice if we put `calicoctl` in `PATH`, and make the working directory be `$HOME` (`/root`)

**Comment by tmjd** [comment]
Duplicate #1525 as far as adding it to path, fixed in #1606.

**Comment by caseydavenport** [comment]
Fix is in #1673
