### ISSUE TITLE
Access to pod from external system in same VNET of Kubernetes cluster

### ISSUE THREAD

**Issue by carlosmkb** [projectcalico/calicoctl#1618]
Hi,
I have a Kubernetes cluster with calico and created an ippool with pods address CIDR.
With this configuration I can access to external systems from the pods, but cannot access directly to pods (10.244.x.x) from an external system in the same vnet.
There is any solution for this requirement?

**Comment by tmjd** [comment]
This might help http://docs.projectcalico.org/v2.1/usage/external-connectivity#inbound-connectivity

**Comment by tmjd** [comment]
Closing in favor of https://github.com/projectcalico/calico/issues/730
