### ISSUE TITLE
can't modify loglevel for startup.go

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calicoctl#1624]
startup.go logs beautiful debug messages that can never see the light of day because loglevel is hardcoded as info. :cry:

**Comment by bcreane** [comment]
Hey @ozdanborne  - is this still an issue? Looks like the first thing calicoctl does after parsing flags is to set the logging level. Is there another project I should look at?

**Comment by bcreane** [comment]
Oops, never mind @ozdanborne - looks like I'm not able to checkout out calico_node in calico repo for some reason, so didn't see startup.go in my local copy.

**Comment by caseydavenport** [comment]
Yep, this issue is in the wrong place now that we've moved `calico/node` into the Calico repo.

**Comment by bcreane** [comment]
dup'ed this issue into projectcalico/calico, closing this one.
