### ISSUE TITLE
Intermittent failures in the IPIP STs.

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calicoctl#1630]
Current suspicion is that etcd is in the same subnet as the IPIP IP pool and therefore routing to etcd will be out of whack (attempt to go over tunnel)

**Comment by tomdee** [comment]
@robbrockbank Can this be closed now?

**Comment by robbrockbank** [comment]
I think we can close - I haven't actually seen this issue for quite some time, although the issue was never explicitly resolved.
