### ISSUE TITLE
Unify Logging Story

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calicoctl#1633]
I have noticed a few things missing from Calico's logging story:

- Log messages don't include component identifier (from calico/node, from calico/cni, etc.)
- Name for "LOG_LEVEL" parameter of each component is different. e.g.
   - `calicoctl -l debug`
   - `log_level` for cni-plugin
   - `LogSeveritySys` or `FELIX_LOG_SEVERITY_SYS` for Felix
- Difficult to configure the log level for some components. There is no way (besides custom builds) to configure logs for:
   - calico/node
   - bird
   - confd
- Components don't agree on log message format. Need something like `<datetime> <components> <msg>`, etc.

There are some issues opened for some of these, I will do my best to find and connect them here.

**Comment by caseydavenport** [comment]
> There is no way (besides custom builds) to configure logs for:
> calico/node
> bird

I thought this was configurable through calicoctl, and in some cases environment variables.

**Comment by caseydavenport** [comment]
We should probably standardize around the current felix log format for all components.

**Comment by caseydavenport** [comment]
We've split this out into its component issues since they're not really related and can be closed out independently.
