### ISSUE TITLE
How to resolve issue with creating network

### ISSUE THREAD

**Issue by salamaniibm** [projectcalico/calicoctl#1653]
Hi,

I create the docker network using command:

`$docker network create --driver calico --ipam-driver calico-ipam net1`
resulted in following error:
`Error response from daemon: failed to update store for object type *libnetwork.endpointCnt: client: etcd cluster is unavailable or misconfigured`

Environment:
* etcd cluster as follow:
e7ebfe94fbe7ce5: name=etcd0 peerURLs=http://10.20.39.2:2380 clientURLs=http://10.20.39.2:2379,http://10.20.39.2:4001 isLeader=true
121212e634cb4b06: name=etcd1 peerURLs=http://10.20.36.7:2380 clientURLs=http://10.20.36.7:2379,http://10.20.36.7:4001 isLeader=false
* docker version:1.12.6 (configured it with cluster store using docker option --cluster-store etcd://10.20.36.7:2379 )
* calicoctl version :v1.2.1
* calico/node version:
confd 0.12.0-dev
BIRD version 1.6.3
libnetwork-plugin: v1.1.0
calico-bgp-daemon: v0.2.1-dirty
Felix:
Version:            2.2.2
Full git commit ID: 9c92a9624d11d2ed68484d488c42a0b0d67d88aa
Build date:         2017-05-31T09:16:09+0000

* Operating System and version:Ubuntu 16.10

**Comment by tmjd** [comment]
What is the ETCD_ENDPOINT you specified for calico/node? I'm wondering if maybe you passed it 'etcd://10.20.36.7:2379' instead of 'http://10.20.36.7:2379'.

If that doesn't help then you should take a look at the logs from the calico/node container and see if those help identify the problem.

**Comment by salamaniibm** [comment]
I was using etcd version v3.0.3, now changed it to etcd v3.1.7,working fine for me.

**Comment by tmjd** [comment]
Oh there was an issue with the early versions of etcd v3, though I forgot specifically what it was that was changed/fixed.  Thanks for reporting back.  Hopefully it helps someone else.
