### ISSUE TITLE
Allow calico/node container to access iptables-restore lockfile

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calicoctl#1655]
## Expected Behavior
The calico/node container should mount the /run directory and ensure that iptables-restore is using the same lock file as kube-proxy

## Current Behavior
The lockfile directory isn't mounted so the lockfile doesn't get used/shared

## Possible Solution
See expected behaviour

## Context
See https://github.com/kubernetes/kubernetes/pull/46259

**Comment by fasaxc** [comment]
This depends on adding the relevant support to Felix: https://github.com/projectcalico/felix/issues/1470

**Comment by caseydavenport** [comment]
Fixed by https://github.com/projectcalico/calicoctl/pull/1684
