### ISSUE TITLE
Calico does not use the TLS secure setting

### ISSUE THREAD

**Issue by bg1szd** [projectcalico/calicoctl#1661]
I enabled SSL setting for both etcd and calico. However, when creating the calico container, it shows a lot of issues in docker log (I enabled debug level of log output.). 
## Expected Behavior

The expected behavior is that there is no error in the docker log when creating a new calico container via cmd like calicoctl node run --ip=10.146.89.21 --config=/etc/calico/calicoctl.cfg

## Current Behavior

There errors like 
DEBU[8767] Calling POST /v1.27/containers/9999a31c9939721a18914a277792f262e69d666b99535767416f4cfb2efa7f25/start
DEBU[8767] container mounted via layerStore: /var/lib/docker/overlay/893bb7a373165ad8310689b3336d0d96dd2054e6bde1bc65a7a643b2ae2fe258/merged
DEBU[8767] failed to get networks for scope global: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

DEBU[8767] failed to get endpoints for network host scope global: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

DEBU[8767] could not find network 5fac214771d5ec113b606257881cc102c0931476a16873b4082ac6dcbab14e64: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

DEBU[8767] could not find network 5fac214771d5ec113b606257881cc102c0931476a16873b4082ac6dcbab14e64: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

DEBU[8767] could not find endpoint e18a3a1786ba225196a1c19f43ec2c5883eef6d9f260fd967237ed0a3efa7444 in global: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

DEBU[8767] could not find network 5fac214771d5ec113b606257881cc102c0931476a16873b4082ac6dcbab14e64: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

DEBU[8767] could not find endpoint e18a3a1786ba225196a1c19f43ec2c5883eef6d9f260fd967237ed0a3efa7444 in global: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

DEBU[8767] could not find network 5fac214771d5ec113b606257881cc102c0931476a16873b4082ac6dcbab14e64: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

DEBU[8767] could not find endpoint e18a3a1786ba225196a1c19f43ec2c5883eef6d9f260fd967237ed0a3efa7444 in global: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

DEBU[8767] could not find network 5fac214771d5ec113b606257881cc102c0931476a16873b4082ac6dcbab14e64: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

## Steps to Reproduce (for bugs)

1. Install and configure the etcd.
2. Enable the SSL with etcd. Make sure etcd is working fine as
2017-06-08 07:53:35.228521 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
2017-06-08 07:53:35.229457 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
member 920f214c622bc956 is healthy: got healthy result from https://10.146.89.62:2379
member a9ed1d764e614fbc is healthy: got healthy result from https://10.146.89.21:2379
member d6002a6c6860d652 is healthy: got healthy result from https://10.146.89.16:2379
cluster is healthy

3. Create the /etc/calico／calicoctl.cfg  file 
input the following
apiVersion: v1
kind: calicoApiConfig
metadata:
spec:
  etcdEndpoints: "https://10.146.89.21:2379,https://10.146.89.16:2379,https://10.146.89.62:2379"
  etcdKeyFile: "/etc/etcd/ssl/etcd-key.pem"
  etcdCertFile: "/etc/etcd/ssl/etcd.pem"
  etcdCACertFile: "/etc/etcd/ssl/ca.pem"	
4.
Then execute the command calicoctl node run --ip=10.146.89.21 --config=/etc/calico/calicoctl.cfg

THen error will shown in the docker server log. You can enable docker debug log mode and view the log via service docker status -l
## Your Environment

* calicoctl version (e.g. `calicoctl version`):
calicoctl version
Version:      v1.2.1-16-gf344e54
Build date:
Git commit:   f344e54

* calico/node version (e.g. `docker run --rm calico/node versions`)
Status: Downloaded newer image for calico/node:latest
confd v0.12.1-calico-0.1.0
BIRD version 1.6.3
libnetwork-plugin: v1.1.0
calico-bgp-daemon: v0.2.1

Felix:
Version:            2.3.0-rc3
Full git commit ID: f6dd5dd5b558594425cc06269903b98224209cd1
Build date:         2017-06-07T15:54:32+0000

* Orchestrator type and version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
Linux dockerhost02.cloud.com 3.10.0-514.21.1.el7.x86_64 #1 
* Link to your project (optional):

**Comment by tmjd** [comment]
After trying to start calico-node, did you look at the etcd logs again?  Someone reported the same type of error ` etcd cluster is unavailable or misconfigured` and then determined that the certs they were using were old/wrong after looking at what etcd reported in its logs.

**Comment by bg1szd** [comment]
I checked the etcd log via journalctl -u etcd since etcd service is started
I did not find any error.



Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: a9ed1d764e614fbc became follower at term 108
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: newRaft a9ed1d764e614fbc [peers: [], term: 108, commit: 1978, applied: 0, lastindex: 1978, lastterm: 108]
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: starting server... [version: 3.1.8, cluster version: to_be_decided]
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: ClientTLS: cert = /etc/etcd/ssl/etcd.pem, key = /etc/etcd/ssl/etcd-key.pem, ca = , trusted-ca = /etc/etcd/ssl/ca.
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: added member 920f214c622bc956 [https://10.146.89.62:2380] to cluster 81f5b4c0c14cd3eb
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: starting peer 920f214c622bc956...
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: started HTTP pipelining with peer 920f214c622bc956
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: started streaming with peer 920f214c622bc956 (writer)
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: started peer 920f214c622bc956
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: added peer 920f214c622bc956
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: added member a9ed1d764e614fbc [https://10.146.89.21:2380] to cluster 81f5b4c0c14cd3eb
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: added member d6002a6c6860d652 [https://10.146.89.16:2380] to cluster 81f5b4c0c14cd3eb
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: starting peer d6002a6c6860d652...
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: started HTTP pipelining with peer d6002a6c6860d652
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: started streaming with peer 920f214c622bc956 (writer)
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: started streaming with peer d6002a6c6860d652 (writer)
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: started streaming with peer 920f214c622bc956 (stream MsgApp v2 reader)
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: started streaming with peer 920f214c622bc956 (stream Message reader)
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: started streaming with peer d6002a6c6860d652 (writer)
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: started peer d6002a6c6860d652
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: added peer d6002a6c6860d652
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: set the initial cluster version to 3.0
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: enabled capabilities for version 3.0
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: updated the cluster version from 3.0 to 3.1
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: enabled capabilities for version 3.1
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: started streaming with peer d6002a6c6860d652 (stream Message reader)
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: started streaming with peer d6002a6c6860d652 (stream MsgApp v2 reader)
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: peer d6002a6c6860d652 became active
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: established a TCP streaming connection with peer d6002a6c6860d652 (stream Message writer)
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: established a TCP streaming connection with peer d6002a6c6860d652 (stream Message reader)
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: established a TCP streaming connection with peer d6002a6c6860d652 (stream MsgApp v2 reader)
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: peer 920f214c622bc956 became active
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: established a TCP streaming connection with peer 920f214c622bc956 (stream Message reader)
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: established a TCP streaming connection with peer d6002a6c6860d652 (stream MsgApp v2 writer)
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: established a TCP streaming connection with peer 920f214c622bc956 (stream MsgApp v2 writer)
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: established a TCP streaming connection with peer 920f214c622bc956 (stream Message writer)
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: established a TCP streaming connection with peer 920f214c622bc956 (stream MsgApp v2 reader)
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: raft.node: a9ed1d764e614fbc elected leader d6002a6c6860d652 at term 108
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: published {Name:dockerhost01 ClientURLs:[https://10.146.89.21:2379]} to cluster 81f5b4c0c14cd3eb
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: ready to serve client requests
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: serving client requests on 10.146.89.21:2379
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: ready to serve client requests
Jun 08 10:35:43 dockerhost01.cloud.com etcd[4222]: serving client requests on 127.0.0.1:2379
Jun 08 10:35:43 dockerhost01.cloud.com systemd[1]: Started etcd server.


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Via the web browser,  when accessing the url as https://10.146.89.21:2379/v2/members
I could got the json format member data. 
And I checked the certification, it is the one I generated for testing.
However, if I tried to access the url as http://10.146.89.21:2379/v2/members  
I will get the return code  like  "\x15\x03\x01\x00\x02\x02"

**Comment by tmjd** [comment]
If you run `calicoctl get nodes --config=/etc/calico/calicoctl.cfg` on one of your hosts does it return a list of the nodes?  I'm curious if the problem is with the config or the config in the calico/node.

You checked the etcd logs, did you check them for each of your etcd members?

You could also `docker exec -it <calico/node docker container ID> /bin/sh` and then do `export` and see that you have environment variables for the ETCD_(ENDPOINTS|CERT_FILE|CA_CERT_FILE|KEY_FILE) and then check that the correct files are found at those locations.

FYI it does look like you are running the release candidate.  I wouldn't expect any problems particularly but you may want to use the v2.2 release so you know you are using a tested release.

**Comment by bg1szd** [comment]
I ran the calicoctl get nodes --config=/etc/calico/calicoctl.cfg on any of the hosts, each of them will return a list of the nodes, as 
[root@dockerhost03 ~]# calicoctl get nodes --config=/etc/calico/calicoctl.cfg
NAME
dockerhost01.cloud.com
dockerhost02.cloud.com
dockerhost03.cloud.com

I checked the environment variables in each calico container, they are correct. And the *.crt and *.pem files are there.
export ETCD_CA_CERT_FILE='/etc/calico/certs/ca_cert.crt'
export ETCD_CERT_FILE='/etc/calico/certs/cert.crt'
export ETCD_ENDPOINTS='https://10.146.89.21:2379,https://10.146.89.16:2379,https://10.146.89.62:2379'
export ETCD_KEY_FILE='/etc/calico/certs/key.pem'

/ # ls -l /etc/calico/certs/
total 12
-rw-r--r--    1 root     root          1310 Jun  7 05:44 ca_cert.crt
-rw-r--r--    1 root     root          1456 Jun  7 05:44 cert.crt
-rw-------    1 root     root          1675 Jun  7 05:44 key.pem

I compared the *.crt and *.pem file content with what I described in the /etc/calico/calicoctl.cfg, they are the same.

**Comment by bg1szd** [comment]
I downloaded the 2.2.1 version calicoctl. It revised the calico image/container automatically. However, the issue is still there. When starting the calico container, I found the following error from the docker log with debug mode enabled.

DEBU[3024] form data: {"AttachStderr":false,"AttachStdin":false,"AttachStdout":false,"Cmd":null,"Domainname":"","Entrypoint":null,"Env":["CALICO_LIBNETWORK_IFPREFIX=cali","NODENAME=dockerhost01.smartercitiescloud.com","CALICO_LIBNETWORK_LABEL_ENDPOINTS=false","CALICO_LIBNETWORK_ENABLED=true","IP_AUTODETECTION_METHOD=first-found","IP6_AUTODETECTION_METHOD=first-found","CALICO_LIBNETWORK_CREATE_PROFILES=true","IP=10.146.89.21","ETCD_CERT_FILE=/etc/calico/certs/cert.crt","CALICO_NETWORKING_BACKEND=bird","NO_DEFAULT_POOLS=","ETCD_KEY_FILE=/etc/calico/certs/key.pem","ETCD_ENDPOINTS=https://10.146.89.21:2379,https://10.146.89.16:2379,https://10.146.89.62:2379","ETCD_CA_CERT_FILE=/etc/calico/certs/ca_cert.crt"],"HostConfig":{"AutoRemove":false,"Binds":["/var/run/calico:/var/run/calico","/lib/modules:/lib/modules","/run/docker/plugins:/run/docker/plugins","/var/run/docker.sock:/var/run/docker.sock","/etc/etcd/ssl/ca.pem:/etc/calico/certs/ca_cert.crt","/etc/etcd/ssl/etcd-key.pem:/etc/calico/certs/key.pem","/etc/etcd/ssl/etcd.pem:/etc/calico/certs/cert.crt","/var/log/calico:/var/log/calico"],"BlkioDeviceReadBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceWriteIOps":null,"BlkioWeight":0,"BlkioWeightDevice":null,"CapAdd":null,"CapDrop":null,"Cgroup":"","CgroupParent":"","ConsoleSize":[0,0],"ContainerIDFile":"","CpuCount":0,"CpuPercent":0,"CpuPeriod":0,"CpuQuota":0,"CpuRealtimePeriod":0,"CpuRealtimeRuntime":0,"CpuShares":0,"CpusetCpus":"","CpusetMems":"","Devices":[],"DiskQuota":0,"Dns":[],"DnsOptions":[],"DnsSearch":[],"ExtraHosts":null,"GroupAdd":null,"IOMaximumBandwidth":0,"IOMaximumIOps":0,"IpcMode":"","Isolation":"","KernelMemory":0,"Links":null,"LogConfig":{"Config":{},"Type":""},"Memory":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":-1,"NanoCpus":0,"NetworkMode":"host","OomKillDisable":false,"OomScoreAdj":0,"PidMode":"","PidsLimit":0,"PortBindings":{},"Privileged":true,"PublishAllPorts":false,"ReadonlyRootfs":false,"RestartPolicy":{"MaximumRetryCount":0,"Name":"always"},"SecurityOpt":null,"ShmSize":0,"UTSMode":"","Ulimits":null,"UsernsMode":"","VolumeDriver":"","VolumesFrom":null},"Hostname":"","Image":"quay.io/calico/node:v1.2.1","Labels":{},"NetworkingConfig":{"EndpointsConfig":{}},"OnBuild":null,"OpenStdin":false,"StdinOnce":false,"Tty":false,"User":"","Volumes":{},"WorkingDir":""}
DEBU[3024] container mounted via layerStore: /var/lib/docker/overlay/5f0f926770cdc3a8aae77149b3c198a21bf80d8f3f4232ed7b70a39aa07c613a/merged
DEBU[3024] Calling GET /v1.27/events?filters=%7B%22container%22%3A%7B%22e4d6d0537ec90113221db681fc4e420ef9bf7a52b8bcd13d45196545c917a754%22%3Atrue%7D%2C%22type%22%3A%7B%22container%22%3Atrue%7D%7D
DEBU[3024] Calling POST /v1.27/containers/e4d6d0537ec90113221db681fc4e420ef9bf7a52b8bcd13d45196545c917a754/start
DEBU[3024] container mounted via layerStore: /var/lib/docker/overlay/5f0f926770cdc3a8aae77149b3c198a21bf80d8f3f4232ed7b70a39aa07c613a/merged
DEBU[3024] failed to get networks for scope global: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

DEBU[3024] failed to get endpoints for network host scope global: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

DEBU[3024] could not find network 5fac214771d5ec113b606257881cc102c0931476a16873b4082ac6dcbab14e64: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

DEBU[3024] could not find network 5fac214771d5ec113b606257881cc102c0931476a16873b4082ac6dcbab14e64: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

**Comment by bg1szd** [comment]
I followed the following guide to create the SSL certification and key, which are used for etcd and calico
https://github.com/coreos/etcd/tree/master/hack/tls-setup

**Comment by bg1szd** [comment]
@tmjd , do you have any comment or suggestion about this issue? I was blocked by this issue so far. Thank you!

**Comment by bg1szd** [comment]
I tried the following command, And it could return the expected result

etcdctl --peers=https://10.146.89.16:2379 --ca-file=/etc/etcd/ssl/ca.pem --cert-file=/etc/etcd/ssl/etcd.pem --key-file=/etc/etcd/ssl/etcd-key.pem ls

2017-06-12 06:22:52.279965 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
/message
/calico

So the key + certification file used here are working fine.

Then what is the root cause of the issue?

**Comment by tmjd** [comment]
@bg1szd sorry for the silence.  It looks like everything is configured correctly from what you've done.  I am not familiar with the internals of using etcd with certs so I pinged the team I work with if anyone could help and everybody is very busy so I am going to try to dig in and see if I can figure out what is going on.

I just had the thought could you run tcpdump and filter on port 2379 and see if calico/node is attempting to connect without ssl?  From your tests earlier it sounds like it is.  Could you please attach the output from from the capture?

**Comment by tmjd** [comment]
I was just reading the `hack/tls-setup` readme and noticed `won't require client certs for non-peer clients`.  Have you tried using just `http` for your ETCD_ENDPOINTS?

**Comment by bg1szd** [comment]
@tmjd , Thanks for your reply.
I just tried to modify the  cat /etc/calico/calicoctl.cfg to the following:
apiVersion: v1
kind: calicoApiConfig
metadata:
spec:
    datastoreType: "etcdv2"
    etcdEndpoints: "http://10.146.89.21:2379,http://10.146.89.16:2379,http://10.146.89.62:2379"
    etcdKeyFile: "/etc/etcd/ssl/etcd-key.pem"
    etcdCertFile: "/etc/etcd/ssl/etcd.pem"
    etcdCACertFile: "/etc/etcd/ssl/ca.pem"

Then when to create a new calico container, it will report the error:
[root@dockerhost01 calico]# calicoctl node run --ip=10.146.89.21 --config=/etc/calico/calicoctl.cfg
Running command to load modules: modprobe -a xt_set ip6_tables
Enabling IPv4 forwarding
Enabling IPv6 forwarding
Increasing conntrack limit
Removing old calico-node container (if running).
Running the following command to start calico-node:

docker run --net=host --privileged --name=calico-node -d --restart=always -e IP6_AUTODETECTION_METHOD=first-found -e NODENAME=dockerhost01.smartercitiescloud.com -e NO_DEFAULT_POOLS= -e IP_AUTODETECTION_METHOD=first-found -e CALICO_LIBNETWORK_CREATE_PROFILES=true -e CALICO_LIBNETWORK_IFPREFIX=cali -e ETCD_ENDPOINTS=http://10.146.89.21:2379,http://10.146.89.16:2379,http://10.146.89.62:2379 -e IP=10.146.89.21 -e ETCD_CA_CERT_FILE=/etc/calico/certs/ca_cert.crt -e CALICO_NETWORKING_BACKEND=bird -e CALICO_LIBNETWORK_ENABLED=true -e CALICO_LIBNETWORK_LABEL_ENDPOINTS=false -e ETCD_KEY_FILE=/etc/calico/certs/key.pem -e ETCD_CERT_FILE=/etc/calico/certs/cert.crt -v /var/log/calico:/var/log/calico -v /var/run/calico:/var/run/calico -v /lib/modules:/lib/modules -v /run/docker/plugins:/run/docker/plugins -v /var/run/docker.sock:/var/run/docker.sock -v /etc/etcd/ssl/ca.pem:/etc/calico/certs/ca_cert.crt -v /etc/etcd/ssl/etcd-key.pem:/etc/calico/certs/key.pem -v /etc/etcd/ssl/etcd.pem:/etc/calico/certs/cert.crt quay.io/calico/node:v1.2.1

Image may take a short time to download if it is not available locally.
Container started, checking progress logs.

Skipping datastore connection test
ERROR: Unable to access datastore to query node configuration
Terminating
Error executing command: calico/node has terminated, check logs for details

So I believe it is necessary to configure the endpoints as https. And via the key&cert set in the calicoctl.cfg, it could access the datastore.

**Comment by bg1szd** [comment]
I guess after the calico container is started, when calico wants to access the network or endpoint info, it uses the http instead of https.

Jun 12 21:19:03 dockerhost01 dockerd: time="2017-06-12T21:19:03.460748631-05:00" level=debug msg="failed to get networks for scope global: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\"\n"
Jun 12 21:19:03 dockerhost01 dockerd: time="2017-06-12T21:19:03.461606135-05:00" level=debug msg="failed to get endpoints for network host scope global: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\"\n"
Jun 12 21:19:03 dockerhost01 dockerd: time="2017-06-12T21:19:03.462071301-05:00" level=debug msg="could not find network 5fac214771d5ec113b606257881cc102c0931476a16873b4082ac6dcbab14e64: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\"\n"
Jun 12 21:19:03 dockerhost01 dockerd: time="2017-06-12T21:19:03.465416844-05:00" level=debug msg="could not find network 5fac214771d5ec113b606257881cc102c0931476a16873b4082ac6dcbab14e64: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\"\n"
Jun 12 21:19:03 dockerhost01 dockerd: time="2017-06-12T21:19:03.465910242-05:00" level=debug msg="could not find endpoint 31afd47e00ab3672d699a4030ed2170740a4e5d8f4fed4285685e5685b56855a in global: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\"\n"
Jun 12 21:19:03 dockerhost01 dockerd: time="2017-06-12T21:19:03.468122445-05:00" level=debug msg="could not find network 5fac214771d5ec113b606257881cc102c0931476a16873b4082ac6dcbab14e64: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\"\n"
Jun 12 21:19:03 dockerhost01 dockerd: time="2017-06-12T21:19:03.468651950-05:00" level=debug msg="could not find endpoint 31afd47e00ab3672d699a4030ed2170740a4e5d8f4fed4285685e5685b56855a in global: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\"\n"
Jun 12 21:19:03 dockerhost01 dockerd: time="2017-06-12T21:19:03.472058787-05:00" level=debug msg="could not find network 5fac214771d5ec113b606257881cc102c0931476a16873b4082ac6dcbab14e64: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\"\n"
Jun 12 21:19:03 dockerhost01 dockerd: time="2017-06-12T21:19:03.472628380-05:00" level=debug msg="could not find endpoint 31afd47e00ab3672d699a4030ed2170740a4e5d8f4fed4285685e5685b56855a in global: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\"\n"
Jun 12 21:19:03 dockerhost01 dockerd: time="2017-06-12T21:19:03.473102243-05:00" level=debug msg="could not find network 5fac214771d5ec113b606257881cc102c0931476a16873b4082ac6dcbab14e64: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\"\n"
Jun 12 21:19:03 dockerhost01 dockerd: time="2017-06-12T21:19:03.473477154-05:00" level=debug msg="could not find network 5fac214771d5ec113b606257881cc102c0931476a16873b4082ac6dcbab14e64: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\"\n"
Jun 12 21:19:03 dockerhost01 dockerd: time="2017-06-12T21:19:03.473900162-05:00" level=debug msg="could not find endpoint 31afd47e00ab3672d699a4030ed2170740a4e5d8f4fed4285685e5685b56855a in global: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\"\n"
Jun 12 21:19:03 dockerhost01 dockerd: time="2017-06-12T21:19:03.474357448-05:00" level=debug msg="could not find network 5fac214771d5ec113b606257881cc102c0931476a16873b4082ac6dcbab14e64: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\"\n"
Jun 12 21:19:03 dockerhost01 dockerd: time="2017-06-12T21:19:03.474804849-05:00" level=debug msg="could not find endpoint 31afd47e00ab3672d699a4030ed2170740a4e5d8f4fed4285685e5685b56855a in global: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\"\n"
Jun 12 21:19:03 dockerhost01 dockerd: time="2017-06-12T21:19:03.475262212-05:00" level=debug msg="could not find network 5fac214771d5ec113b606257881cc102c0931476a16873b4082ac6dcbab14e64: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\"\n"

**Comment by bg1szd** [comment]
I get the tcpdump data via the following steps:
1. Run the tcpdump cmd on the 10.146.89.21
tcpdump  -vv host 10.146.89.21  and port 2379 -w /tmp/port_2379_calico.cap
2. Run the calicoctl cmd to create the calico node again.
 calicoctl node run --ip=10.146.89.21 --config=/etc/calico/calicoctl.cfg
3. Once the calico container is created, stop the tcpdump.
   
I used wireshark to analyze the cap file. However, when filtering the src ip = 10.146.89.21 and dst ip = 10.146.89.21, there is no record.

**Comment by tmjd** [comment]
Could you show your etcd server configuration?  I'd like to see what you have since there are several pieces to configure for it.  Then I can match up what I'm trying with what you have.
Thanks.

**Comment by bg1szd** [comment]
The etcd version is 3.1.8. 
The docker version is 
[root@dockerhost01 ~]# docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64

This is the cmd I used to start the etcd service.
[root@dockerhost01 ~]# vim /usr/lib/systemd/system/etcd.service
[Unit]
Description=etcd server
After=network.target
After=network-online.target
Wants=network-online.target

[Service]
Type=notify
WorkingDirectory=/var/lib/etcd/
EnvironmentFile=-/etc/etcd/etcd.conf
ExecStart=/usr/local/bin/etcd   --name dockerhost01   --cert-file=/etc/etcd/ssl/etcd.pem   --key-file=/etc/etcd/ssl/etcd-key.pem   --peer-cert-file=/etc/etcd/ssl/etcd.pem   --peer-key-file=/etc/etcd/ssl/etcd-key.pem   --trusted-ca-file=/etc/etcd/ssl/ca.pem   --peer-trusted-ca-file=/etc/etcd/ssl/ca.pem   --initial-advertise-peer-urls https://10.146.89.21:2380   --listen-peer-urls https://10.146.89.21:2380   --listen-client-urls https://10.146.89.21:2379,https://127.0.0.1:2379   --advertise-client-urls https://10.146.89.21:2379   --initial-cluster-token etcd-cluster-1   --initial-cluster dockerhost01=https://10.146.89.21:2380,dockerhost02=https://10.146.89.16:2380,dockerhost03=https://10.146.89.62:2380   --initial-cluster-state new   --data-dir=/var/lib/etcd
Restart=on-failure
RestartSec=5
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target

**Comment by tmjd** [comment]
I just picked up that the logs you are referring to are the docker logs.  Have you configured your docker daemon to start with

```
--cluster-store=etcd://<ip1>:2379,<ip2>:2379,<ip3>:2379 --cluster-store-opt kv.cacertfile=/vagrant/certs/ca.pem --cluster-store-opt kv.certfile=/vagrant/certs/etcd.pem --cluster-store-opt kv.keyfile=/vagrant/certs/etcd-key.pem
```

Perhaps you could share your docker configuration also.

**Comment by bg1szd** [comment]
@tmjd , Thanks!With your help, the issue was finally resolved. 
Here is what I did
1. Update the  /usr/lib/systemd/system/docker.service file
ExecStart=/usr/bin/dockerd  --cluster-store=etcd://10.146.89.21:2379  --cluster-advertise=eth0:2376 --cluster-store-opt kv.cacertfile=/etc/etcd/ssl/ca.pem --cluster-store-opt kv.certfile=/etc/etcd/ssl/etcd.pem --cluster-store-opt kv.keyfile=/etc/etcd/ssl/etcd-key.pem
2. Run systemctl daemon-reload
3. Restart docker service, etcd servcie on each node
4. Run calico node run on each node.
5. Run docker network create --driver=calico --ipam-driver=calico-ipam --subnet=9.9.9.0/26 vnet1  to create the network
6. Run docker network list, the global network has been created.

**Comment by tmjd** [comment]
Great.  Thanks for reporting back.

I'm curious would a comment about adding the certificates to the docker daemon on http://docs.projectcalico.org/v2.3/getting-started/docker/installation/requirements have helped when you were originally setting up for calico?  That seems like the logical place to put that info but I'm just curious if it would have helped you.

**Comment by bg1szd** [comment]
It is better to provide an sample about how to configure the docker daemon with --cluster-store, --cluster-advertise and --cluster-store-opt. Then when user dig into the docker help url, he could find more detailed reference info.

**Comment by tmjd** [comment]
Thank you for the feedback.
