### ISSUE TITLE
Failed to create 'ipPool' resource: resource does not exist: IPPool(cidr=100.64.0.0/10)

### ISSUE THREAD

**Issue by felipejfc** [projectcalico/calicoctl#1667]
get show no ipp
```
$ calicoctl get ipp -o yaml
[]
```

cant create ipp
```
$ calicoctl create -f - << EOF
apiVersion: v1
kind: ipPool
metadata:
  cidr: 100.64.0.0/10
spec:
  ipip:
    enabled: true
    mode: cross-subnet
  nat-outgoing: true
EOF
Failed to create 'ipPool' resource: resource does not exist: IPPool(cidr=100.64.0.0/10)
```
already has workloadEndpoints:
```
$ calicoctl get workloadEndpoint
NODE                             ORCHESTRATOR   WORKLOAD                                                                NAME
ip-172-21-112-37.ec2.internal    k8s            appsites.appsites-cmd-2670552481-t2t7q                                  eth0
```

this is on a kubernetes 1.6.2 setup.

daemonset is configured like that:

```
$ kstag get daemonset calico-node -o yaml -n kube-system
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
  generation: 3
  labels:
    k8s-app: calico-node
    role.kubernetes.io/networking: "1"
  name: calico-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: calico-node
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      creationTimestamp: null
      labels:
        k8s-app: calico-node
        role.kubernetes.io/networking: "1"
    spec:
      containers:
      - env:
        - name: ETCD_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: etcd_endpoints
              name: calico-config
        - name: CALICO_NETWORKING
          valueFrom:
            configMapKeyRef:
              key: enable_bgp
              name: calico-config
        - name: CALICO_DISABLE_FILE_LOGGING
          value: "true"
        - name: IP
        - name: CALICO_IPV4POOL_CIDR
          value: 100.64.0.0/10
        - name: CALICO_IPV4POOL_IPIP
          value: cross-subnet
        image: calico/node:v1.2.1
        imagePullPolicy: IfNotPresent
        name: calico-node
        resources:
          requests:
            cpu: 10m
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /var/run/calico
          name: var-run-calico
      - command:
        - /install-cni.sh
        env:
        - name: ETCD_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: etcd_endpoints
              name: calico-config
        - name: CNI_NETWORK_CONFIG
          valueFrom:
            configMapKeyRef:
              key: cni_network_config
              name: calico-config
        image: calico/cni:v1.8.3
        imagePullPolicy: Always
        name: install-cni
        resources:
          requests:
            cpu: 10m
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          name: cni-bin-dir
        - mountPath: /host/etc/cni/net.d
          name: cni-net-dir
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - hostPath:
          path: /lib/modules
        name: lib-modules
      - hostPath:
          path: /var/run/calico
        name: var-run-calico
      - hostPath:
          path: /opt/cni/bin
        name: cni-bin-dir
      - hostPath:
          path: /etc/cni/net.d
        name: cni-net-dir
```

I'm using calicoctl version v1.3.0. CALICO_DATASTORE_TYPE is kubernetes

**Comment by tmjd** [comment]
I don't believe the create command works when using kubernetes as the datastore. @robbrockbank is that still true?

Have you created the proper environment variables for calicoctl to access kubernetes?  By default it will attempt to access an etcd datastore. See http://docs.projectcalico.org/v2.3/reference/calicoctl/setup/kubernetes for help with that.

**Comment by felipejfc** [comment]
this was indeed caused by kubernetes datastore, I moved to inside the cluster and used etcdv2 datastore then I got it to work :)

**Comment by caseydavenport** [comment]
@tmjd huh, this is supposed to work with KDD.

This is the bit of code: https://github.com/projectcalico/libcalico-go/blob/master/lib/backend/k8s/k8s.go#L324

If it's not working, that sounds like a bug.  Certainly `startup.go` is able to create IPPools - I wonder if there's a bug in calicoctl?

**Comment by tmjd** [comment]
Oh I had missed that calicoctl was hitting an active endpoint. I see now that `calicoctl get workloadendpoints` worked.  I had assumed calicoctl was hitting an empty (as far as calico) etcd and that was why the pool was empty.  My bad.

**Comment by caseydavenport** [comment]
Actually, looking at this is looks like the DaemonSet is configured to use etcd, and calicoctl was configured to use KDD, which is a misconfiguration and explains why create wasn't working.

I think we can close this, but it probably indicates a deficiency in our documentation around datastore type configuration.

**Comment by bj2k61** [comment]
> this was indeed caused by kubernetes datastore, I moved to inside the cluster and used etcdv2 datastore then I got it to work :)

I am having the same issue as Felipe ... I am struggling to create ippool resource and getting same errors as it is on the initial config by Felipe.  How do I " I moved to inside the cluster and used etcdv2 datastore then I got it to work :)"..... I made changes on my .bash_profile and followed the docs suggested by @tmjd  I  am not sure on which other config I need to make the amendments to get a resolve.

below is my bash_profile

[root@ip-172-17-11-236 ~]# cat .bash_profile
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin

export PATH
export CALICO_DATASTORE_TYPE=kubernetes
export CALICO_KUBECONFIG=~/.kube/config
export ETCD_ENDPOINTS=https://etcd1:2379,https://etcd2:2379,https://etcd3:2379

**Comment by caseydavenport** [comment]
```
export CALICO_DATASTORE_TYPE=kubernetes
export CALICO_KUBECONFIG=~/.kube/config
export ETCD_ENDPOINTS=https://etcd1:2379,https://etcd2:2379,https://etcd3:2379
```

This looks like a potential misconfiguration to me - you're setting etcd endpoints, but also telling Calico that it's running using the kubernetes datastore. You probably want to set `DATASTORE_TYPE=etcdv3` instead.

**Comment by bj2k61** [comment]
thanks for your quick response I made the amendments as recommended but I still get the error below :( ...

[root@ip-172-17-11-236 ~]# cat new_calico_pool.ymal-bk
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: dev-pool
spec:
  cidr: 172.17.0.0/16
  ipipMode: Always
  natOutgoing: true
[root@ip-172-17-11-236 ~]# calicoctl create -f new_calico_pool.ymal-bk
Failed to execute command: Unknown resource type (IPPool) and/or version (projectcalico.org/v3)
[root@ip-172-17-11-236 ~]#

**Comment by bj2k61** [comment]
[root@ip-172-17-11-236 ~]# calicoctl get workloadEndpoint
Failed to create Calico API client: Unknown datastore type: etcdv3
[root@ip-172-17-11-236 ~]# calicoctl get workloadEndpoint

**Comment by tmjd** [comment]
What version of Calico have you installed and what version of calicoctl are you using? The OP was using an older version of Calico and `etcdv3` would not have been correct, it would have been `etcd`. That might be your problem too @bj2k61 .
