### ISSUE TITLE
calicoctl node diags should attempt to collect calico/node startup logs when started by Kubernetes

### ISSUE THREAD

**Issue by matthewdupre** [projectcalico/calicoctl#1690]
`calico node diags` fails to capture the calico/node startup logs when calico/node is running under (self-hosted) Kubernetes.  These logs are really important.

If possible, we should try and grab them (although invoking kubectl might not always work).

If not, documentation should be updated to encourage people to get kubectl logs for calico/node as well.

**Comment by heschlie** [comment]
We could probably go through `k8s.io/client-go` to grab the logs, We could use it to grab the previous failed run of logs I believe, and then include it with the rest of the diags.
