### ISSUE TITLE
calicoctl doesn't warn me if I use deprecated "Net" in policy

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calicoctl#1694]
I apply this:
```
- $ cat allow-nodeport-except.yaml 
apiVersion: v1
  kind: policy
  metadata:
    name: disallow-conts
  spec:
    ingress:
    - action: deny 
      destination:
        ports:
        - 30080
      protocol: tcp
      source: 
        net: 10.240.0.11/32
    order: 9 
    preDNAT: true
    selector: has(host-endpoint)
$ calicoctl apply -f allow-nodeport-except.yaml 
Successfully applied 1 'policy' resource(s)
```
and read it back:
```
$ calicoctl get pol disallow-conts -o yaml
- apiVersion: v1
  kind: policy
  metadata:
    name: disallow-conts
  spec:
    ingress:
    - action: deny
      destination:
        ports:
        - 30080
      protocol: tcp
      source:
        nets:
        - 10.240.0.11/32
    order: 9
    preDNAT: true
    selector: has(host-endpoint)
```
This is all correct. But since `Net` has been deprecated, I'd have expected calicoctl to warn me that I was using a deprecated field.

**Comment by caseydavenport** [comment]
Closing this because I don't think we actually want calicoctl to spew logs at users.

If logging is enabled (e.g. `calicoctl -l debug`) then you should see a warning.

**Comment by lwr20** [comment]
So perhaps we don't want calicoctl to spew logs at users, but IMO calicoctl *should* warn you if you're using deprecated fields in your manifests, which is the original subject of this Issue.  

By closing this, are you saying that it should *not* warn you (and that that is an acceptable UX)?

**Comment by caseydavenport** [comment]
The Net field no longer exists in v3.0, so I'm going to close this.
