### ISSUE TITLE
Feature request: Ability to modify felix configuration when running calico via "calicoctl node run"

### ISSUE THREAD

**Issue by DreadPirateShawn** [projectcalico/calicoctl#1698]
## Expected Behavior

According to Calico documentation for bare metal policies, there are failsafe rules in place to prevent accidentally cutting off a host completely. https://docs.projectcalico.org/v2.0/getting-started/bare-metal/bare-metal#failsafe-rules

It then provides a link for disabling these failsure rules via the Calico configuration guide. https://docs.projectcalico.org/v2.0/usage/configuration/

I'm attempting to modify FailsafeOutboundHostPorts, and I'd expect a means to accomplish felix config modifications when launching a calico node via `calicoctl node run`.

## Current Behavior

Felix config modifications can't be provided to `calicoctl node run` -- neither felix.cfg modification nor FELIX_FAILSAFEOUTBOUNDHOSTPORTS env variable specification is possible.

There's no option in `calicoctl node run --help` for specifying the felix config, just the calico config, so that's not an option.

And passing the desired env variable to `calicoctl node run` doesn't appear to work either. (Repro below.)

## Possible Solution

Additional flag for felix.cfg would be useful, and (more broadly) a flag for "pass env variable FOO=bar to the resulting docker run" could be extremely useful.

## Steps to Reproduce

As a baseline reference, my calico nodes are started like so:

```
sudo calicoctl node run --ip=192.168.0.48 --node-image=calico/node:v0.18.0 --no-default-ippools
```

Note that felix config is default, and no special env variable FELIX_FAILSAFEOUTBOUNDHOSTPORTS exists:

```
$ docker exec -it calico-node cat /etc/calico/felix.cfg
[global]
MetadataAddr = None
LogFilePath = None
LogSeverityFile   = None
```
```
$ docker exec -it calico-node env | sort
CALICO_LIBNETWORK_CREATE_PROFILES=true
CALICO_LIBNETWORK_ENABLED=true
CALICO_LIBNETWORK_IFPREFIX=cali
CALICO_LIBNETWORK_LABEL_ENDPOINTS=false
CALICO_NETWORKING_BACKEND=bird
ETCD_ENDPOINTS=http://127.0.0.1:4001
GLIBC_VERSION=2.23-r1
HOME=/root
HOSTNAME=r1etcd1
IP=192.168.0.48
IP6_AUTODETECTION_METHOD=first-found
IP_AUTODETECTION_METHOD=first-found
NO_DEFAULT_POOLS=true
NODENAME=r1etcd1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

There's no option in `calicoctl node run --help` for specifying the felix config, just the calico config, so that's not an option.

And experimentally, passing the desired env variable to `calicoctl node run` doesn't appear to work either, eg:

```
$ sudo FELIX_FAILSAFEOUTBOUNDHOSTPORTS=none ./calicoctl node run --ip=192.168.0.48 --node-image=calico/node:v0.18.0 --no-default-ippools 
Running command to load modules: modprobe -a xt_set ip6_tables
Enabling IPv4 forwarding
Enabling IPv6 forwarding
Increasing conntrack limit
Removing old calico-node container (if running).
Running the following command to start calico-node:

docker run --net=host --privileged --name=calico-node -d --restart=always -e NODENAME=etcd1 -e CALICO_NETWORKING_BACKEND=bird -e CALICO_LIBNETWORK_ENABLED=true -e NO_DEFAULT_POOLS=true -e IP=192.168.0.48 -e ETCD_ENDPOINTS=http://127.0.0.1:4001 -v /var/log/calico:/var/log/calico -v /var/run/calico:/var/run/calico -v /lib/modules:/lib/modules -v /run:/run -v /run/docker/plugins:/run/docker/plugins -v /var/run/docker.sock:/var/run/docker.sock calico/node:v0.18.0

Image may take a short time to download if it is not available locally.
Container started, checking progress logs.

Calico node started successfully

$ docker exec -it calico-node env | sort
CALICO_LIBNETWORK_ENABLED=true
CALICO_NETWORKING_BACKEND=bird
ETCD_ENDPOINTS=http://127.0.0.1:4001
GLIBC_VERSION=2.23-r1
HOME=/root
HOSTNAME=etcd1
IP=192.168.0.48
NO_DEFAULT_POOLS=true
NODENAME=etcd1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

Note that the dynamically-crafted `docker run` doens't pass along the env variable. I mean, this makes sense -- I wouldn't expect it to pass along the whole host system's env -- but it means that passing felix config via env variables isn't an option either.

## Context

We're hardening our cluster, so I've set up calico policies to specifically allow etcd traffic between our etcd hosts and our Kubernetes cluster hosts. However, I'd also like to *deny* traffic between our etcd hosts and our non-Kubernetes hosts (eg mysql host, mq host, web servers, etc etc). As far as I can tell, this means disabling the failsafe rules that calico provides.

Note, I *was* able to experimentally accomplish the desired felix config modification by taking the raw `docker run` above and manually modifying it to add `-e FELIX_FAILSAFEOUTBOUNDHOSTPORTS=none` -- but I really don't want to ditch `calicoctl node run` to accomplish this, that would introduce its own maintenance overhead / risks.

## My Environment

Our calico image version is 0.18.0, which is admittedly growing old -- but I used the latest version of calicoctl, which drives the relevant config and env variables, so that should be appropriate for the scope of this ticket.

```
Client Version:    v1.4.0
Build date:        2017-07-31T20:45:05+0000
Git commit:        03574e5
```

**Kubernetes version:**
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.5", GitCommit:"490c6f13df1cb6612e0993c4c14f2ff90f8cdbf3", GitTreeState:"clean", BuildDate:"2017-06-14T20:15:53Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.5", GitCommit:"490c6f13df1cb6612e0993c4c14f2ff90f8cdbf3", GitTreeState:"clean", BuildDate:"2017-06-14T20:03:38Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

OS specifics vary between nodes, but all are Ubuntu 12.04 or 16.04.

**Comment by DreadPirateShawn** [comment]
As it turns out, there's a pretty straightfoward workaround, in the meanwhile:

```
FROM calico/node:v1.2.1
ENV FELIX_FAILSAFEOUTBOUNDHOSTPORTS=none
```

Build the above dockerfile and push to your registry, then use the following to run calico node with your custom image:
```
calicoctl node run --node-image=<your custom image here>
```

Hey presto! Custom flag is now provided to the Calico image without needing to recreate the internal docker run command.

**Comment by caseydavenport** [comment]
I think we'd be happy to accept a PR which adds support for mounting in a felix config file as part of `calicoctl node run`, or adding the ability to pass arbitrary env vars through.

**Comment by mhmxs** [comment]
> I think we'd be happy to accept a PR which adds support for mounting in a felix config file as part of `calicoctl node run`, or adding the ability to pass arbitrary env vars through.

@caseydavenport I created a small PR to make available to attach custom Felix config: https://github.com/projectcalico/calicoctl/pull/2107
