### ISSUE TITLE
`calicoctl get` on resource that does not exist gives successful return code

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calicoctl#1707]
`calicoctl get <resource> <name>` returns a successful error code, even when the resource does not exist. Example:

```
$ calicoctl get profile k8s_ns.test 
NAME   

turk@durk:~/tigera/docker-compose-kubernetes$ echo $?
0
```

This is not what I expected, and is the opposite of what happens when using the golang api. Example:
```
_, err := calicoClient.Profiles().Get(api.ProfileMetadata{Name: "k8s_ns.test"})
log.Info(err)
```
yields: `2017-09-19 15:56:01.286002 I | [INFO] ERRORERROR: resource does not exist: ProfileTags(name=k8s_ns.test)`

## Expected Behavior
I'd expect an error when I GET a resource that does not exist.

## Current Behavior
Currently I'm returned an empty list of resources.

**Comment by caseydavenport** [comment]
Should be an easy and useful fix.

Anyone want to do this?

**Comment by jpalardy** [comment]
@caseydavenport I wasn't able to reproduce this ~ it works and exits with code 1. Already fixed?

Here's the [supporting code](https://github.com/projectcalico/calicoctl/blob/master/calicoctl/commands/get.go#L187-L190).

**Comment by jpalardy** [comment]
For reference, my console output:

```
$ bin/calicoctl-linux-amd64 get profile k8s_ns.test
Failed to get resources: resource does not exist: Profile(k8s_ns.test) with error: <nil>
$ echo $?
1
$ bin/calicoctl-linux-amd64 version
Client Version:    v3.6.0-0.dev-26-g4fc795a
Git commit:        4fc795a
```
