### ISSUE TITLE
macos:'calicoctl node' commands are not available on this OS

### ISSUE THREAD

**Issue by forfuns** [projectcalico/calicoctl#1789]
running `calicoctl node run --ip=xxx.xxx.xxx.xxx` with macos 
output error message : `Error executing command: 'calicoctl node' commands are not available on this OS`

## Expected Behavior
work for Macos

## Steps to Reproduce (for bugs)

1. wget for release page binary file
2. exec command : calicoctl node run --ip=IP

## Your Environment

* calico/node version (e.g. `docker run --rm calico/node versions`)
`calicoctl version`
Client Version:    v1.6.2
Build date:        2017-11-22T22:41:52+0000
Git commit:        855392a8
Cluster Version:   v2.6.3
Cluster Type:      unknown
* Orchestrator type and version (e.g. kubernetes, mesos, rkt):
no kubernates,just etc
`etcd --version`
etcd Version: 3.2.11
Git SHA: GitNotFound
Go Version: go1.9.2
Go OS/Arch: darwin/amd64
* Operating System and version:
macOs 10.13.2
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@forfuns The `calicoctl node` suite of commands is not supported on mac because we do not support running `calico/node` on mac, so it doesn't really make sense.

I don't believe we intend to support macos in the near future, so I'm going to close this for now. Thank you for raising an issue.
