### ISSUE TITLE
Command help incorrectly uses camelCase resource kinds

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calicoctl#1800]
## Expected Behavior

Should use either the `alllowercase` format that people tend to type on the CLI, or the `UpperCamelCase` format taht we use for resource "kinds" in v3.

## Current Behavior

`camelCase`
## Possible Solution

Change it!
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* calicoctl version (e.g. `calicoctl version`):
* calico/node version (e.g. `docker run --rm calico/node versions`)
* Orchestrator type and version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Looks like calicoctl is case insensitive so this isn't really an issue.
