### ISSUE TITLE
Issue with Docker & Calico-IPAM cyclical dependency. 

### ISSUE THREAD

**Issue by kwatson** [projectcalico/calicoctl#1801]
I've been having issues using the default calicoctl node run method and docker daemon restarts. When docker daemon stops or starts, it first stops all the containers, and then attempts to cleanup and release IP's. However, since the calico container was already stopped, docker is unable to communicate with the ipam plugin. Docker will then hang for quite some time before finally giving up, and completing it's shutdown & start cycle. 

**Steps to reproduce on v2.6 (on our platform anyways, some steps may not be necessary):**

  - Create a local network for calico, and also in docker. 
  - Create a docker container and assign it a static ip from a predefined network within calico & docker.
  - issue a docker restart

**Resolution: Disable the libnetwork plugin in the calico container, and run it separately as a system service.**

It would be nice if we could run calico as a [docker plugin](https://docs.docker.com/engine/extend/plugin_api/). I would expect that to completely resolve this issue; I'm not sure what all would need to change in order to support that. 

**Bandaid procedure to resolve it:** 

Calicoctl node run does not appear to give an option to disable the libnetwork driver, so i use the `--dryrun` option to print out the full command, and set `CALICO_LIBNETWORK_ENABLED` to `false`

I then downloaded the libnetwork driver from https://github.com/projectcalico/libnetwork-plugin/releases/download/v1.1.2/libnetwork-plugin to /usr/local/bin & created a system service using the following systemd file: https://gist.github.com/kwatson/248b57d9f8fba7ff620cc3c2c7fe6bf2 

I'm leaving out a few steps for brevity, but if anyone would like the full step-by-step, let me know and I can write it up.

**Comment by caseydavenport** [comment]
Yeah, this sounds like a problem with the way we run the libnetwork-plugin as part of the `calico/node` container, managed by Docker.

I suspect running as a Docker plugin is the right longer term solution to this, but _for now_ I think running the libnetwork-plugin standalone should be the recommended way to do this.

**Comment by caseydavenport** [comment]
libnetwork is no longer a part of the calico/node container (and calico/node no longer lives in this repo!) So I'm going to close this.

I think any other enhancements related to this should be raised against https://github.com/projectcalico/libnetwork-plugin so that folks who are interested in developing that repo can find them.
