### ISSUE TITLE
[question] Does calico support custom kubernets resources?

### ISSUE THREAD

**Issue by etsangsplk** [projectcalico/calicoctl#1806]
Lets say I want to create further segregation under a namespace in kubernetes. E.g, I want to put customResource A and B under a namespace. 
* I want network visibility only within A and  B does not have network visibility to A and vice versa. 
then Able to allow  the policy to allow connection across A and B but not to outside.
Does calico support networking segregation for my customer resource?
Or do I have to apply network policy on pods based on labels?
Since labels are created by user, how can calico pick these label up dynamically?
Any example to show such? 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* calicoctl version (e.g. `calicoctl version`):
* calico/node version (e.g. `docker run --rm calico/node versions`)
* Orchestrator type and version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by tmjd** [comment]
I'm not sure what you mean by customResource.  Kubernetes has something called Custom Resource Definitions, which is basically a way to use the Kubernetes API as a datastore. If you are asking if Calico offers any capabilities to police access to those the answer is no, you can use K8s RBAC for that.

I think maybe you are just asking about namespace isolation, where pods in namespace A cannot access pods in namespace B and vice versa.  The answer to that is a definite yes, you should follow the Calico demo/tutorials like the [Simple Policy Demo](https://docs.projectcalico.org/v3.0/getting-started/kubernetes/tutorials/simple-policy) and [Stars Policy Demo](https://docs.projectcalico.org/v3.0/getting-started/kubernetes/tutorials/stars-policy/).  The 2nd demo specifically has multiple namespaces so may be of interest to you.

You also asked

> Since labels are created by user, how can calico pick these label up dynamically?

Calico watches the Kubernetes objects it needs (pods and network policy) and will see label changes and take action accordingly.

**Comment by ozdanborne** [comment]
@etsangsplk I'm going to close this issue as we haven't heard back from you in quite some time. Do reopen if @tmjd 's response does not satisfy your original issues.
