### ISSUE TITLE
YAML referenced on kubeadm cluster install page doesn't create CRDs

### ISSUE THREAD

**Issue by ebauman** [projectcalico/calicoctl#1830]
Check out https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#pod-network

The YAML referenced for Calico installation (https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubeadm/1.7/calico.yaml) contains no definitions of CRDs required for Calico operation.

## Expected Behavior
I would expect that after using `kubeadm` to initialize a cluster, and install Calico, that I could create resources such as BGPPeers or IPPools. 

## Current Behavior
The aforementioned operations fail as no CRDs have been installed into the kubernetes cluster. 

## Possible Solution
Update the YAML to include these CRDs.

## Context
I am setting up a small homelab that will be using calico and bgp.
I executed `kubeadm` according to the kubernetes.io instructions. I then used the YAML referenced on the `kubeadm` page to install calico. I also then installed `calicoctl` according to help docs on the calico project website.

I attempted to create bgpconfigurations, bgppeers, etc. Nothing seemed to work. That's when I discovered that the CRDs had not been created, and as I was using kubernetes as my data store, I could not create new resources. 

## Your Environment

* calicoctl version (e.g. `calicoctl version`):
```
Client Version:    v2.0.2
Build date:        2018-03-21T23:29:25+0000
Git commit:        6acca0a3
```
* calico/node version (e.g. `docker run --rm calico/node versions`): 
```
confd v1.0.3
libnetwork-plugin: BIRD version v0.3.2+birdv1.6.3
v1.1.0
calico-bgp-daemon: v0.2.1

Felix:
Version:            3.0.3
Full git commit ID: 21894138c411bafe8f7fa419fd5a5b9b4163d056
Build date:         2018-02-23T23:25:56+0000
```
* Orchestrator type and version (e.g. kubernetes, mesos, rkt): 
*kubernetes (using docker)*
* Operating System and version: 
*Ubuntu 16.0.4 LTS*
* Link to your project (optional): 
*n/a (homelab)*

**Comment by ebauman** [comment]
See also #1704 which seems to be in the same vein

**Comment by ebauman** [comment]
My apologies: I just discovered https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
which does contain the CRDs.

**Comment by ebauman** [comment]
That didn't work either.
It wasn't until digging through issues that I discovered #355.
Am I understanding correctly that bgp global peers are not supported when using a kubernetes datastore?

**Comment by tmjd** [comment]
I think it may be appropriate to close this issue again unless you believe the kubernetes-datastore yaml is not creating the CRDs needed and open a new issue with the information appropriate to your current issue.
That being said, what isn't specifically working for you? If you are receiving errors please could you include those too.  You should be able to create BGP global peers (see https://docs.projectcalico.org/v3.0/reference/calicoctl/resources/bgppeer, you need to omit the node field.)

**Comment by ebauman** [comment]
Right you are. I think this issue was a bit premature before I fully understood the solution. 

Sorry for the false alarm, etc.
