### ISSUE TITLE
Seamless OpenStack and Docker networking problem

### ISSUE THREAD

**Issue by huynhducbk95** [projectcalico/calicoctl#1843]
Hi, I am new with calico and my purpose is get connectivity between VM in openstack and container in docker.
and I found this document to help me:
[https://www.projectcalico.org/seamless-openstack-docker-networking/](https://www.projectcalico.org/seamless-openstack-docker-networking/)
This document seems quite detail, but it work for old calico version:
> Here’s what you have to do (with Calico) in more detail:
> - Install a Calico OpenStack deployment following the instructions. Unlike in a normal OpenStack cluster where the OpenStack database contains all the data, and so putting etcd on a RAM disk makes sense (as the etcd data can be rebuilt if it fails), it’s best to use an etcd cluster : if you have to reboot and lose all your Calico data it’s annoying to have to rebuild it all! After installing the OpenStack deployment, test that you can create and manage VMs as normal.
> - Install the Docker hosts, installing etcd on these hosts as a proxy to the etcd cluster you are using for OpenStack. Before you do anything with calicoctl on each of these hosts, you need to set the interface prefix correctly, as follows. `etcdctl set /calico/v1/host/<docker host>/config/InterfacePrefix cali`OpenStack hosts expect interface starting with “tap” while Docker hosts expect interfaces starting with “cali” – and this way you’ll be able to mix the two in the same deployment.
> - For each Docker host, download calicoctl and configure the node (`calicoctl node`).
Create the IP address pools (`calicoctl pool add`) on one of your Docker hosts as documented here. You should use separate IP pools for OpenStack and Docker (so that OpenStack does not select IPs that are in the Docker range), but provision both of them using calicoctl so that they are included in the BIRD BGP configuration.
> - Now, configure BGP for both Docker and OpenStack hosts. On the Docker hosts, BIRD configuration is automatically applied through etcd and confd – but that requires that the IPs of each OpenStack compute host is stored in etcd, so set them up as follows. `etcdctl set /calico/v1/host/<openstack host>/bird_ip <IP address of host>`
> - Once you’ve done that, you’ll need to configure the BIRD configuration in `/etc/bird/bird.conf` on the OpenStack compute hosts, and restart BIRD. A good trick is to dump the config on one of the Docker hosts and use that as the basis for the OpenStack configuration, to reduce the amount of manual editing required.`docker exec calico-node cat /config/bird.cfg`

For now, I have completed building a openstack cluster (2 compute node) and a docker container cluster (2 host). both cluster have etcd proxy to the same etcd cluster.
at the last step,run command `docker exec calico-node cat /config/bird.cfg` I get an error:
```
# docker exec calico-node cat /config/bird.cfg
cat: can't open '/config/bird.cfg': No such file or directory

```
why `bird.cfg` no such file? how can I confige bgp on my compute nodes and docker nodes?

## Your Environment

* calicoctl version (e.g. `calicoctl version`): v1.6.3
* calico/node version (e.g. `docker run --rm calico/node versions`)
```
confd v3.1.0
BIRD version v0.3.2+birdv1.6.3
libnetwork-plugin: v1.1.0
calico-bgp-daemon: v0.2.1

Felix:
Version:            3.1.0
Full git commit ID: dba3279377fd6ec7baf0ee560bcaec685f25fa86
Build date:         2018-04-06T17:25:36+0000

```
* Orchestrator type and version (e.g. kubernetes, mesos, rkt): openstack and docker
* Operating System and version: 16.04
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@huynhducbk95 yes, those steps are from a blog post that's _very_ old and I suspect are not appropriate any more with modern versions of Calico. 

The most recent documentation is at https://docs.projectcalico.org, though I'm not aware of it having an equivalent set of steps.

**Comment by huynhducbk95** [comment]
@caseydavenport sorry for delay.
I tried to deploy my deployment (calico based openstack and docker). It has similar steps with the link that I found.
Just a little difference from [that link](https://www.projectcalico.org/seamless-openstack-docker-networking/) about BGP configure on openstack host.

**Comment by huynhducbk95** [comment]
I will close this issue here. Thanks for your response
