### ISSUE TITLE
s390x/alpine image version should be changed in Dockerfile.calicoctl-s390x file.

### ISSUE THREAD

**Issue by chakravarthy392** [projectcalico/calicoctl#1846]
S390x support is added from the version v2.0.3 , but build failed as there is no such image named `s390x/alpine:3.4`. 

build has got successful d after I have made below change in `calicoctl/calicoctl/Dockerfile.calicoctl-s390x` file.

 changed `FROM s390x/alpine:3.4` to  `FROM s390x/alpine:3.6` .

Please change the alpine image version to `3.6` as mentioned in the [v3.1.0/master](https://github.com/projectcalico/calicoctl/blob/master/calicoctl/Dockerfile.calicoctl-s390x) branches. 

## Steps to Reproduce 
1. git clone https://github.com/projectcalico/calicoctl $work_dir/src/github.com/projectcalico/calicoctl
2. cd $work_dir/src/github.com/projectcalico/calicoctl
3. git checkout v2.0.3
4. cd $work_dir/src/github.com/projectcalico/calicoctl
5. ARCH=s390x make calico/ctl

##  Environment

* calicoctl version : v2.0.3
* calico/node version : v3.0.5
* Operating System and version: s390x - Ubuntu 16.04

**Comment by deitch** [comment]
There is an open issue that addresses several issues, including moving all alpine to 3.7. Please see #1848.

**Comment by deitch** [comment]
Sorry, that should have been “open PR”.  Hopefully @fasaxc or @caseydavenport can get it merged in soon. :-)
