### ISSUE TITLE
How to delete calico completely in kubernetes and reinstall it?

### ISSUE THREAD

**Issue by anjuls** [projectcalico/calicoctl#1858]
I am facing issue with the tunl0 device which has incorrect IP and not able to route it to the POD's IP. 
In my cluster, for some worker nodes, POD routing is working correctly and for other remaining, it is not. 
I am doing kubeadm reset on those workers and rejoining them. Rebooting the calico-node pod doesn't help. Also, manually i tried to delete tunl0 dev, it doesnt remove. 

kubectl get pods -n kube-system -o wide | grep xxxxx14031
calico-node-hdv58                          2/2       Running            1          3h        10.195.73.27     xxxxx14031
coredns-8459d9f654-dgjm6                   1/1       Running            2          5m        10.244.215.1     xxxxx14031
coredns-8459d9f654-zfhh4                   1/1       Running            2          5m        10.244.215.2     xxxxx14031
kube-proxy-nt9c2                           1/1       Running            0          1d        10.195.73.27     xxxxx14031

sudo ip route list  | grep 10.244.215.1 <---- pod i want to reach
10.244.215.1 via <IP of xxxxx14031> dev tunl0 proto bird onlink

but tunl0 has wrong IP address on the worker. 

Could you please let me know how to remove calico cleanly from the host?

**Comment by ozdanborne** [comment]
To answer your original question - calico stores some additional data in etcd, which `kubeadm reset` does not wipe. If you're using Calico's Kubeadm manifest which runs etcd as a pod on the master, you'll need to run `rm -rf /var/etcd/calico-data` on the master as well.

But I think the core issue may be something else. Tunl0 _is_ supposed to have an address from the pod cidr. Can you show the output of `ip addr show`?

**Comment by stpabhi** [comment]
@anjuls ```modprobe -r ipip``` should delete tunl0 iface
