### ISSUE TITLE
Calico sets up route to some pods on "eth0" device rather than "tunl0"

### ISSUE THREAD

**Issue by seh** [projectcalico/calicoctl#1859]
## Expected Behavior

In a Kubernetes cluster with Calico's "calico-node" pods running on each node, clients on all the nodes should be able to connect to servers running on any other node, given that there are no firewall rules blocking this pod network traffic among nodes. There shouldn't be any exclusions to this access between pairs of machines.

## Current Behavior

Per [this discussion in the "sig-networking" channel](https://kubernetes.slack.com/archives/C09QYUH5W/p1527191462000140) in the Kubernetes Slack team, I noticed that some clients in my Kubernetes clusters can't connect to servers in pods over the pod network.

I am running Calico (with Typha) in AWS. At present, my cluster has three masters and two workers.
I noticed that if I run a server via a _Deployment_ on the two workers, I can contact both of these servers via node port from any of the five cluster machines.
I can also contact both of them via their pod IP address from _some_ of the machines, but not all of them, per the following table:

 Machine address | Type   | Reach server 1? (_10.103.151_) | Reach server 2? (_10.103.0.184_)
----------------- | -------- | ----------------- | -----------------
_10.103.0.147_ | master | :no_entry_sign:               | :white_check_mark:
_10.103.0.151_ | worker | :white_check_mark:               | :white_check_mark:
_10.103.0.184_ | worker | :white_check_mark:               | :white_check_mark:
_10.103.0.188_ | master | :white_check_mark:              | :no_entry_sign: 
_10.103.0.205_ | master | :white_check_mark:               | :white_check_mark:

I’ve tried restarting the _calico-node_ pods on the machines hosting the servers, as well as the two where clients can’t connect (_10.103.0.147_ and _10.103.0.188_), to no avail.

I confirmed that via _iptables-save_ that the rules look correct from _kube-proxy_, so I think this is a matter with the pod network (Calico). I followed [the Calico troubleshooting instructions](https://docs.projectcalico.org/v3.1/usage/troubleshooting/), and the node names and BGP peer status looks normal.

Next I noticed this: Running _sudo calico node diags_ on machine _10.103.0.147_ (that can’t talk to _10.103.0.151_), I see the resulting _ipv4_route_ file has a difference for the target:
```
default via 10.103.0.129 dev eth0 proto dhcp src 10.103.0.147 metric 1024 
10.103.0.128/27 dev eth0 proto kernel scope link src 10.103.0.147 
10.103.0.129 dev eth0 proto dhcp scope link src 10.103.0.147 metric 1024 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
192.168.0.0/24 via 10.103.0.205 dev tunl0 proto bird onlink 
192.168.1.0/24 via 10.103.0.188 dev tunl0 proto bird onlink 
192.168.2.0/24 via 10.103.0.184 dev tunl0 proto bird onlink 
192.168.3.0/24 via 10.103.0.151 dev eth0 proto bird 
blackhole 192.168.4.0/24 proto bird
```
Note how the record for _192.168.3.0/24_ has a device “eth0” rather than “tunl0", and the “onlink” entry isn’t there.

On machine _10.103.0.88_—the one that can't talk to _10.103.0.184_ properly—I ran _route_, and in the output again you can see the "eth0" device in use for the entry for _ip-192-168-2-0_:
```
$ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         ip-10-103-0-161 0.0.0.0         UG    1024   0        0 eth0
ip-10-103-0-160 0.0.0.0         255.255.255.224 U     0      0        0 eth0
ip-10-103-0-161 0.0.0.0         255.255.255.255 UH    1024   0        0 eth0
ip-172-17-0-0.e 0.0.0.0         255.255.0.0     U     0      0        0 docker0
ip-192-168-0-0. ip-10-103-0-205 255.255.255.0   UG    0      0        0 tunl0
ip-192-168-1-0. 0.0.0.0         255.255.255.0   U     0      0        0 *
ip-192-168-1-2. 0.0.0.0         255.255.255.255 UH    0      0        0 califb3dbf7651f
ip-192-168-2-0. ip-10-103-0-184 255.255.255.0   UG    0      0        0 eth0
ip-192-168-3-0. ip-10-103-0-151 255.255.255.0   UG    0      0        0 tunl0
ip-192-168-4-0. ip-10-103-0-147 255.255.255.0   UG    0      0        0 tunl0
```

This sounds reminiscent of the symptoms several issues from 2016:
- #716
- projectcalico/bird#22
- apprenda/kismatic#206

## Possible Solution

I tried restarting all the "calico-node" and "calico-typha" pods and letting new ones start in their place, but that didn't heal the routes on the two bad machines. I also tried rebooting both machines, but when they came back up, they retained this bad route entry that still uses the "eth0" device.

## Steps to Reproduce (for bugs)

Well, this is not going to be easy.

1. Start three Kubernetes master servers running Calico with "calico-typha" enabled.  
  Note that I have Typha running on each of three master servers.
2. Start two Kubernetes workers and have them join the cluster as nodes.
3. Start a server (such as _nginx_) with two replicas on the two workers.
4. Try to connect to both servers from all five machines using their pod IP addresses.

## Context

I was trying to confirm that Kubernetes _Services_ work with _kube-proxy_ for routing connections to _Services_ of type "NodePort" and "ClusterIP." That's all working well enough, but then I discovered that trying to use the pod IP addresses found in the _Endpoints_ objects only work from some machines to servers running on some other machines.

## Your Environment
* calicoctl version (e.g. `calicoctl version`):  
```
Client Version:    v3.1.1
Build date:        2018-04-19T23:45:54+0000
Git commit:        86318310
no etcd endpoints specified
```
* calico/node version (e.g. `docker run --rm calico/node versions`):  
```
confd v3.1.2
BIRD version v0.3.2+birdv1.6.3
calico-bgp-daemon: v0.2.1

Felix:
Version:            3.1.2
Full git commit ID: c4f5a06e0ed82d484ba118b41b6e2ccb7c1145a6
Build date:         2018-05-18T13:02:12+0000
```
* Orchestrator type and version (e.g. kubernetes, mesos, rkt):  
  Kubernetes version 1.10.3, bootstrapped with _kubeadm_, running in AWS EC2

* Operating System and version:  
  _Linux ip-10-103-0-147 4.14.32-coreos #1 SMP Tue Apr 3 05:21:26 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux_

**Comment by seh** [comment]
Ah, here's a clue: The two offending pairs above (master _10.103.0.147_ and worker _10.103.0.151_, and master _10.103.0.188_ and worker _10.103.0.184_) are in the same subnet. I have the "CALICO_IPV4POOL_IPIP" environment variable set to "CrossSubnet," instead of "Always," which is the default. I do _not_ have the Kubernetes AWS Cloud Provider setting up routes for me. I set that after reading [Calico's AWS-related documentation](https://docs.projectcalico.org/v3.1/reference/public-cloud/aws#routing-traffic-across-different-vpc-subnets--vpcs).
> By default, Calico’s IPIP encapsulation applies to all container-to-container traffic. However, encapsulation is only required for container traffic that crosses a VPC subnet boundary. For better performance, you can configure Calico to perform IPIP encapsulation only across VPC subnet boundaries.

Assuming that this setting may be the cause here, it doesn't sound like I get better performance. What might I be doing wrong here that this documentation assumes would allow this all to work?

**Comment by seh** [comment]
I also tried disabling the source/destination checks on these machines, per [the Calico documentation](https://docs.projectcalico.org/v3.1/reference/public-cloud/aws#routing-traffic-within-a-single-vpc-subnet), but that didn't have any effect on the routes or my ability to get one machine to talk to another.

**Comment by seh** [comment]
I realized that I filed this report in the wrong repository. Can we move it over to _projectcalico/calico_?

**Comment by seh** [comment]
Thinking about thus problem more away from the computer, I think the problem may be a firewall rule after all: I recall allowing Ingress to all nodes from other nodes for IPIP (protocol 4) traffic, but I think I also need a rule allowing ingress into each node from the pod network CIDR block for all TCP traffic. That assumes that these packets going over the “eth0” device will retain their source addresses (of the pod IP address, that is).

I won’t be able to try that until tomorrow morning.

**Comment by cmluciano** [comment]
Cc @caseydavenport I can’t remember if Calico will allow you to block the pod network CIDR or not. I recall when developing CIDR blocks for NP that this came up a few times in regard to how CNI plugins could get hosed.

**Comment by seh** [comment]
I'm in the middle of trying out a revised configuration that admits TCP traffic ingress from the pod network CIDR block for pods in the same subnet. I suspect that Calico is obeying my directive to only use IPIP encapsulation when crossing a subnet boundary, and I'm blocking the resulting TCP traffic from entering the server.

**Comment by caseydavenport** [comment]
> I have the "CALICO_IPV4POOL_IPIP" environment variable set to "CrossSubnet," instead of "Always,"

Ah, right. yes, this sounds like it's doing the right thing then by sending that traffic over eth0. You could try setting it to "Always" and if it fixes the problem then we'll know for sure.

As for why that traffic is getting dropped, it does sound very much like an AWS security group issue - i.e. not allowing the pod traffic. Might want to try allowing to and from the pod CIDR in your node SG rules.

> I can’t remember if Calico will allow you to block the pod network CIDR or not.

@cmluciano yep, Calico will allow you to do write NP which has CIDR rules in the pod cidr.

**Comment by caseydavenport** [comment]
> I realized that I filed this report in the wrong repository. Can we move it over to projectcalico/calico?

No worries, we don't worry too much about where the issue is. Happy to discuss here.

**Comment by seh** [comment]
Here's something that surprised me, which tells me I'm confused. I opened an ingress firewall rule on these machines that allows TCP packets on any port in from the pod subnet CIDR block. That did not have the intended effect. Next I tried opening a similar rule that allows those same packets in from a particular AWS security group, of which all these machines are members. That _did_ work.

I thought the source address for these packets would be something on the pod network, but the security group match here tells me that the source address remains the instance's private IP address. Perhaps that's because I'm issuing these requests from a shell running on the host operating system, and not from a pod running on that same machine. I'll try that next.

**Comment by seh** [comment]
I launched _busybox_ pods on several nodes—including those on separate subnets from each server—and confirmed that I can also reach the destination pods with the firewall rule in place allowing ingress not from the pod subnet, but rather from a set of instances in a security group.

@caseydavenport, is Calico performing NAT here for intra-subnet traffic? I expected the source IP address for packets coming out of a pod to be within the pod subnet.

**Comment by caseydavenport** [comment]
> I expected the source IP address for packets coming out of a pod to be within the pod subnet.

Calico will, by default, perform NAT on traffic from a Calico IP pool to something not in a Calico IP pool (in essense, from a pod IP address to something that isn't another pod).

You should be able to tell pretty easily by doing a tcpdump on eth0 and looking at the source addr

**Comment by seh** [comment]
Using _tcpdump_, I see the outbound packets acquire the originating host IP address as their source address (with a wild-bound port), with the destination pod's IP address retained as their destination address. That explains why the ingress security group rule matches against the source security group, as opposed to the pod subnet CIDR block: the arriving packets don't claim to come from the pod subnet; they appear to come from another EC2 instance with an identifiable security group.

Solving this problem end-to-end required opening up that security group rule and deactivating the source/destination packet check on my EC2 instances, which is easy for those launched directly via, say, the Terraform _aws_instance_ resource, but for those launched in an autoscaling group, I went with a "oneshot" systemd unit invoking [_rubenv/ec2-disable-source-dest_](https://github.com/rubenv/ec2-disable-source-dest) in a container with _rkt_.

Thank you for tolerating my rambling investigation here, and thank you for Calico!

**Comment by caseydavenport** [comment]
> Using tcpdump, I see the outbound packets acquire the originating host IP address as their source address (with a wild-bound port), with the destination pod's IP address retained as their destination address. 

Hmm, if this is Pod->Pod traffic, I would not expect that UNLESS it was going over the IPIP tunnel, which  it doesn't sound like it is. I wonder if something else is NATing the traffic?

**Comment by caseydavenport** [comment]
@seh yep! that looks right to me :)
