### ISSUE TITLE
GOOS=linux GOARCH=arm64 go build calicoctl.go

### ISSUE THREAD

**Issue by lurenjia528** [projectcalico/calicoctl#1879]
/sig bug
2018-7-12
when I exec "GOOS=linux GOARCH=arm64 go build  #calicoctl.go"
calico-3.1.3
etcd-3.3.7
libcalico-go  master 

modify  /libcalico-go/lib/clientv3/client.go  218  250  line  uuid.NewV4()
![250](https://user-images.githubusercontent.com/37833630/42632542-1ba38af4-8610-11e8-8837-1c0aababb463.png)
![218](https://user-images.githubusercontent.com/37833630/42632543-1c02be34-8610-11e8-87a4-0feedc687d4c.png)

I success!

Is it bug?

**Comment by tmjd** [comment]
Please provide the error you were seeing before your fix and indicate more clearly what, if anything, you changed.

I haven't done any cross builds previously but I just tried with the latest calicocatl master branch and was able to:
1. <update my local checkout>
2. make vendor
3. cd calicoctl
4. GOOS=linux GOARCH=arm64 go build # with no errors

**Comment by lurenjia528** [comment]
oh,Maybe it's a dependent version of the problem，I'm in China,my glide always fail when 'glide install'
even though I set the ~/.glide/mirrors.yaml，So , some of the dependencies are manually installed，

glide install error
``` bash
[WARN]	Unable to checkout google.golang.org/appengine
[ERROR]	Update failed for google.golang.org/appengine: Cannot detect VCS
[WARN]	Unable to checkout golang.org/x/time
[ERROR]	Update failed for golang.org/x/time: Cannot detect VCS
[WARN]	Unable to checkout google.golang.org/grpc
[ERROR]	Update failed for google.golang.org/grpc: Cannot detect VCS
[WARN]	Unable to checkout google.golang.org/genproto
[ERROR]	Update failed for google.golang.org/genproto: Cannot detect VCS
[ERROR]	Failed to install: Cannot detect VCS
```

So,Where can I find some calico's component's binary or docker image for arm64? 
Thanks.

**Comment by tmjd** [comment]
The arm64 port is community supported and is not currently built so there are no official binaries or images for arm64.

I'm not familiar with using glide mirrors so I can't help with that.

**Comment by lurenjia528** [comment]
@tmjd thanks,I solved the problem of dependence and build success

@tomdee 
local file still use vcs?

![1](https://user-images.githubusercontent.com/37833630/42915565-325cf3f2-8b33-11e8-86a3-9c5b65ed965e.png)
![3](https://user-images.githubusercontent.com/37833630/42915562-31b4798e-8b33-11e8-8c82-bdfa0eb0d83d.png)

**Comment by lurenjia528** [comment]
@tmjd thanks,I solved the problem of dependence and build success.

@tomdee  thanks.
I try again,when mapping to github,the package 'golang.org/x/net' download success,but when I use local file ,it still failed.

![mirrors](https://user-images.githubusercontent.com/37833630/42916078-03c57ba6-8b36-11e8-8097-f28b11f5fe5c.png)

![yingshe](https://user-images.githubusercontent.com/37833630/42916076-031f4754-8b36-11e8-86b3-f169d787c0ed.png)

![localfile](https://user-images.githubusercontent.com/37833630/42916079-0427eb74-8b36-11e8-8af8-bb4ed886410f.png)
