### ISSUE TITLE
Error response from daemon: plugin "calico" not found

### ISSUE THREAD

**Issue by leecsai** [projectcalico/calicoctl#1896]
Hi, guys 
sorry for distrubing...
I met a question like this:
```
[root@docker1 ~]# docker network create --driver calico --ipam-driver calico-ipam cal_net1
Error response from daemon: plugin "calico" not found
```
my docker configuration:
`[root@docker1 ~]# cat /etc/systemd/system/docker.service.d/10-machine.conf
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver devicemapper --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=generic --cluster-store=etcd://192.168.205.134:2379
Environment=
`
my calico container:
```
[root@docker1 ~]# docker container ls
CONTAINER ID        IMAGE                        COMMAND             CREATED             STATUS              PORTS               NAMES
f2c1f1860256        quay.io/calico/node:latest   "start_runit"       25 minutes ago      Up 25 minutes                           calico-node
```

```
[root@docker1 ~]# calicoctl node status
Calico process is not running.
```

how can I solve this problem,thx~~~~

**Comment by nvidhub** [comment]
Error response from daemon: plugin "calico" not found -->cat /var/log/calico/libnetwork/current  可以查看日志。这个错误是因为calico/node镜像缺少libnetwork-plugin(一个二进制文件).
至于第二个错误，我也还在研究

**Comment by leecsai** [comment]
thx~~~~, nvidhub
I think because the calico process  cannot run on calico-node container, my container cannot start and report an error. But I don't know why the container process cannot start.

**Comment by caseydavenport** [comment]
The `latest` version of calico/node does not include docker libnetwork support.

You'll need to look at running the libnetwork plugin: https://github.com/projectcalico/libnetwork-plugin

Or, reverting to Calico v2.6.
