### ISSUE TITLE
calicoctl --unknown-flag wrongly returns 0

### ISSUE THREAD

**Issue by mirwan** [projectcalico/calicoctl#1910]
When calling `calicoctl` with an unknown flag, the return code is 0. For example, when wrongly placing a command flag before the command, the command is not executed and usage is displayed (partially as it seems) but the return code is 0.
NB: This does not occur when passing unknown flag to the command.

## Expected Behavior
The return code should not be 0 when an unknown flag is passed to calicoctl and the command fails (is not executed).

## Current Behavior
```console
mirwan$ docker run -it --rm quay.io/calico/ctl:v3.1.3 --unknown-flag
Usage:
  calicoctl [options] <command> [<args>...]
mirwan$ echo $?
0
mirwan$ echo '{}' | docker run -i --rm quay.io/calico/ctl:v3.1.3 --skip-exists create -f -
Usage:
  calicoctl [options] <command> [<args>...]
mirwan$ echo $?
0
mirwan$ echo '{}' | docker run -i --rm quay.io/calico/ctl:v3.1.3 create --skip-exists -f -
Failed to execute command: error parsing document: cannot parse object '{}' into value of type []unstructured.Unstructured
mirwan$ echo $?
1
mirwan$ echo '{}' | docker run -i --rm quay.io/calico/ctl:v3.1.3 create --unknown-flag -f -
Usage:
  calicoctl create --filename=<FILENAME> [--skip-exists] [--config=<CONFIG>] [--namespace=<NS>]
Invalid option: 'calicoctl create --unknown-flag -f -'. Use flag '--help' to read about a specific subcommand.
mirwan$ echo $?
1
```
As it not related to docker:
```console
mirwan$ docker run -it --rm --entrypoint=/bin/sh quay.io/calico/ctl:v3.1.3
~ # /calicoctl --unknown-flag
Usage:
  calicoctl [options] <command> [<args>...]
~ # echo $?
0
~ #
```
## Steps to Reproduce (for bugs)
1. docker run -it --rm quay.io/calico/ctl:v3.1.3 --unknown-flag
2. echo $?

## Context
When using calicoctl in a ansible playbook, the command/shell actually fails but is reported as OK which is a problem

## Your Environment

* calicoctl version (e.g. `calicoctl version`):
```
Client Version:    v3.1.3
Build date:        2018-05-30T17:15:59+0000
Git commit:        231083c2
no etcd endpoints specified
```
* calico/node version (e.g. `docker run --rm calico/node versions`): N/A
* Orchestrator type and version (e.g. kubernetes, mesos, rkt): k8s (but not relevant here I guess)
* Operating System and version: Ubuntu 16.04

**Comment by caseydavenport** [comment]
Yeah, it would be great to fix this. Not sure when I can get to it myself, but would be help get a PR through.
