### ISSUE TITLE
docker network create --driver calico --ipam-driver calico-ipam net1

### ISSUE THREAD

**Issue by jiangyoucai** [projectcalico/calicoctl#1944]
```
[andy@aliyun77 ~]$ docker network create --driver calico --ipam-driver calico-ipam net1
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
```

**Comment by caseydavenport** [comment]
This looks like an issue with docker.

In the future, please fill out the issue template. I'd also recommend opening issues against the libnetwork repository if you're using that integration: https://github.com/projectcalico/libnetwork-plugin

**Comment by mdzddl** [comment]
> ```
> [andy@aliyun77 ~]$ docker network create --driver calico --ipam-driver calico-ipam net1
> Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
> ```

hi，jiangyoucai;finally,did you resolve this problem,i face the same problem;thanks

**Comment by jiangyoucai** [comment]
remove openvpn from your server

this is my config 

# docker

install docker
    
    sudo yum install -y yum-utils \
    device-mapper-persistent-data \
    lvm2

    sudo yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo

    sudo yum install docker-ce

    sudo systemctl enable docker
    sudo systemctl start docker
    
    sudo groupadd docker
    sudo usermod -aG docker $USER

install docker-compose

    sudo yum install python-pip
    sudo pip install docker-compose

# etcd

set bashrc

    vim .bashrc

    add next:
    
    export ETCDCTL_API=3
    
    export ETCD1=10.25.210.244
    export ETCD2=10.169.100.209
    export ETCD3=10.169.215.6

    source .bashrc
    
set iptables

    vim /etc/sysconf/iptables
    
    add next:
    
    -A INPUT -s 10.25.210.0/24 -j ACCEPT  
    -A INPUT -s 10.169.100.0/24 -j ACCEPT
    -A INPUT -s 10.169.215.0/24 -j ACCEPT
    
    sudo systemctl restart iptables
    
get config

    git clone https://gitee.com/jiangyoucai/etcd.io
    
    #node1
    cd etcd.io/node1/
    docker-compose up -d
    
    #node2
    cd etcd.io/node2/
    docker-compose up -d
    
remark（if error）

    sudo route del -net 172.16.0.0 netmask 255.240.0.0 
    
check status

    docker ps
    docker exec -it hash sh
    etcdctl member list

# calico

set cluster-store

    sudo vim /usr/lib/systemd/system/docker.service

    set next:
    
    ExecStart=/usr/bin/dockerd -H unix:// --cluster-store=etcd://ETCD1_IP_ADDR:2379

    sudo systemctl daemon-reload
    sudo systemctl restart docker
    
get calicoctl

    sudo wget -O /usr/bin/calicoctl https://github.com/projectcalico/calicoctl/releases/download/v1.6.5/calicoctl
    sudo chmod +x /usr/bin/calicoctl
    
set ctl
    
    vim ctl.yaml
    
    set next:
    
    apiVersion: v1
    kind: calicoApiConfig
    metadata:
    spec:
        datastoreType: "etcdv2"
        etcdEndpoints: "http://NODE1_IP_ADDR:2379,http://NODE2_IP_ADDR:2379,http://NODE3_IP_ADDR:2379"

set ip(only node1)
    
    vim ip.yaml
    
    set next:
    
    apiVersion: v1
    kind: ipPool
    metadata:
        cidr: 10.0.0.0/24
    spec:
        ipip:
            enabled: true
            mode: cross-subnet
        nat-outgoing: true
        disabled: false   
     
    sudo calicoctl create -f ip.yaml
    
run node

    sudo calicoctl node run --node-image=quay.io/calico/node:v2.6.12 --config=ctl.yaml --ip=NODE IP ADDR
    sudo calicoctl node status

create network(only node1)

    docker network create --driver calico --ipam-driver calico-ipam  --subnet 172.18.22.0/24 net1
    docker network create --driver calico --ipam-driver calico-ipam  --subnet 172.18.22.0/24 net2
    docker network create --driver calico --ipam-driver calico-ipam  --subnet 172.18.22.0/24 net3
    
run container

    #node1
    docker run --net net1 --name workload-A -tid alpine
    docker run --net net2 --name workload-B -tid alpine
    docker run --net net1 --name workload-C -tid alpine
    
    #node2
    docker run --net net3 --name workload-D -tid alpine
    docker run --net net1 --name workload-E -tid alpine
    
ping container

    #同一网络内的容器（即使不在同一节点主机上）可以使用容器名来访问
    docker exec workload-A ping -c 4 workload-C.net1
    docker exec workload-A ping -c 4 workload-E.net1
    
    #不同网络内的容器需要使用容器ip来访问（使用容器名会报：bad address）
    docker exec workload-A ping -c 2  `docker inspect --format "{{ .NetworkSettings.Networks.net2.IPAddress }}" workload-B`

set policy

```
- apiVersion: v1
  kind: policy
  metadata:
    name: net1
  spec:
    ingress:
    - action: allow
      protocol: tcp
      source:
        nets:
        - 10.0.0.0/24
      destination:
        ports:
        - 80
```

set iptables (restart lost)

    iptables -t nat -N expose-ports
    iptables -t nat -A OUTPUT -j expose-ports
    iptables -t nat -A PREROUTING -j expose-ports
    
    iptables -t nat -A expose-ports -p tcp --destination host_ip --dport host_port -j DNAT --to docker_ip:docker_port
