### ISSUE TITLE
`Unable to build locally using make build`

### ISSUE THREAD

**Issue by maverickash8889** [projectcalico/calicoctl#1961]
Make build silently fails if the LOCAL_USER_ID overruns value of 256000

## Expected Behavior

`make build` command should create the bin folder and associated ./dist folder having executables for suitable environments. Same is not happening as of now. 

Exception handling to be done in make file. for example 
`Starting with UID : 713578628
adduser: number 713578628 is not in 0..256000 range` we should increase the range. 

## Current Behavior

"Makefile" located  /calicoctl/Makefile has shell command 
"`LOCAL_USER_ID?=$(shell id -u $$USER)`" which is referred in many places during the building of executables. If the `$ shell id` returns any value above 256000 the installation silently fails but continues no producing the required file/folders.  `./dist` folder is not getting created. 

## Possible Solution

`Starting with UID : 713578628
adduser: number 713578628 is not in 0..256000 range ` increase the range. Exception handling in the current situation. 

## Steps to Reproduce (for bugs)

1. git clone "project_url"
2. navigate to folder 
3. $make build (continues to download the dependencies and builds the repo but at the begining it would give a warning if the `LOCAL_USER_ID` value is > 256000 
4. silently fails in steps where the `LOCAL_USER_ID` is used, output expected is `./dist`  directory having binaries for current architecture. but the folder doesn't exit. the `bin` directory is empty. 

## Context

Not able to build the calicoctl commands and use while deployment of ibmcloud kubeclusters. 

## Your Environment

* calicoctl version (e.g. `calicoctl version`): unable to build and determine the build version. 
* calico/node version (e.g. `docker run --rm calico/node versions`) : version 3.5.0
* Orchestrator type and version (e.g. kubernetes, mesos, rkt):: kubernetes
* Operating System and version:: macOS Mojave v10.14.2
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Looks the same as https://github.com/projectcalico/go-build/issues/64
