### ISSUE TITLE
How to use calico network with docker swarm

### ISSUE THREAD

**Issue by hegphegp** [projectcalico/calicoctl#1996]
**Description**

<b>How to use calico network with docker swarm, I don't want to user overlay network. Could provide some blogs or some examples about calico network with docker swarm?</b>

**software info:**

```
Docker version 18.09.5-ce
Calicoctl Version 3.6.1
```

**Comment by caseydavenport** [comment]
Duplicate of https://github.com/projectcalico/calico/issues/2576
