### ISSUE TITLE
Compatibility between versions

### ISSUE THREAD

**Issue by chenrui333** [projectcalico/calicoctl#2008]
I am trying to support `calicoctl` formula, e.g. https://github.com/Homebrew/homebrew-core/pull/39892.

I wonder if we need to have multiple versions in homebrew side, like `calicoctl@3.5`, `calicoctl@3.6`, `calicoctl` (3.7 by default).

Thanks!

**Comment by caseydavenport** [comment]
First - that's awesome, really appreciate you doing that!

For the most part (like 90% of the time) calicoctl should work fine across different versions of Calico. However, there may be some cases where it won't, and so we'd typically recommend running a version of calicoctl that matches the version of Calico installed on the cluster.

**Comment by rata** [comment]
@caseydavenport Do you think it might be possible to support some versions skews? I'd really appreciate those are supported.

My use case is using calicoctl in a very simple kubernetes controller, but having to match the controller with the exact version of calico used makes it error prone for us (the controller needs to be updated on every calico change) and we would need to release tons of images just for that.

Also, while it should mostly work, when you say it is recommended to match the calico version installed in the cluster, do you mean the major and minor? Or also the patch release? (IOW 3.7.1 vs 3.7.2 too?)

Best,
Rodrigo
