### ISSUE TITLE
How to enable node again once calicoctl delete executed?

### ISSUE THREAD

**Issue by Ankur7890** [projectcalico/calicoctl#2018]
Deleted one of the node through calicoctl command line where reason of deletion "IP already allocated"  which as per our understanding deleted each reference from etcd data store and if we need to add the same node again what would be the approach in k8s ?

One way is to run calicoctl run node but same is libcontainer/CNM whereas we want CNI based approach of k8s. 

Our calico-node is running as daemon sets.

**Comment by caseydavenport** [comment]
@Ankur7890 you can just restart the Kubernetes pod - it will recreate the node object when it comes back up.
