### ISSUE TITLE
Bug, no bgp connectivity between master and node

### ISSUE THREAD

**Issue by Nurlan199206** [projectcalico/calicoctl#2027]
## Expected Behavior

I have two VirtualBox machines.  i can't setup bgp connection between them. I'm choosed CIDR `192.168.0.0/16` for pods in calico-typha.yaml. Also i don't know WHY BGP PEER ON MASTER NODE `172.21.0.1`. I think it's wrong address. Before `kubeadm reset`  I'm tried with CIDR `172.16.0.0/12` but same issue.

```
1) Master (IP: 192.168.0.105)
2) Node (IP: 192.168.0.106)
```

## Steps to Reproduce (for bugs)

1. kubeadm init --pod-network-cidr=192.168.0.0/16
2. curl https://docs.projectcalico.org/v3.7/manifests/calico-typha.yaml -O
3. kubectl apply -f calico-typha.yaml 
4. kubectl taint nodes --all node-role.kubernetes.io/master-

### No pings between pods on other node.
![Снимок экрана 2019-06-25 в 21 53 59](https://user-images.githubusercontent.com/22808731/60113559-d588a680-9793-11e9-9a2b-40ee44113797.png)

## Your Environment

* calicoctl version (e.g. `calicoctl version`):
```
Client Version:    v3.7.3
Git commit:        3be51cfc
no etcd endpoints specified
```
* calico/node version (e.g. `docker run --rm calico/node versions`)
```
v3.7.3
BIRD version v0.3.3+birdv1.6.3
```

* Orchestrator type and version (e.g. kubernetes, mesos, rkt):
```
NAME              STATUS   ROLES    AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION      CONTAINER-RUNTIME
node1.nurlan.kz   Ready    <none>   30m   v1.14.3   192.168.0.106   <none>        Ubuntu 18.10   4.18.0-22-generic   docker://18.9.6
nurlan.kz         Ready    master   40m   v1.14.3   192.168.0.105   <none>        Ubuntu 18.10   4.18.0-21-generic   docker://18.9.6
```

* Operating System and version:
```
NAME="Ubuntu"
VERSION="18.10 (Cosmic Cuttlefish)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.10"
VERSION_ID="18.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic
```
* Link to your project (optional):
`MASTER`
![Снимок экрана 2019-06-25 в 20 55 46](https://user-images.githubusercontent.com/22808731/60109587-6c516500-978c-11e9-8d0b-42ba38046593.png)
`NODE`
![Снимок экрана 2019-06-25 в 20 56 14](https://user-images.githubusercontent.com/22808731/60109609-75423680-978c-11e9-9021-89f41745b745.png)

**Comment by tmjd** [comment]
The Calico node on your `node1` host looks to have selected the wrong interface (based on the IP address your `nurlan` host is attempting to establish a BGP connection to).  You should take a look at https://docs.projectcalico.org/v3.7/reference/node/configuration#ip-autodetection-methods on the values that can be set for autodetection.
This is because there are multiple interfaces when you use VirtualBox and you need to ensure calico-node selects the correct one to use.

**Comment by Nurlan199206** [comment]
Wow, thank you.

![Снимок экрана 2019-06-25 в 22 16 37](https://user-images.githubusercontent.com/22808731/60115094-f272a900-9796-11e9-8c09-89059c170a42.png)

**Comment by tmjd** [comment]
Sounds like you're problem is solved, I'm going to close this. Thanks for reporting back.
