### ISSUE TITLE
 The CALICO_IPV4POOL_CIDR value entered when calico apply is different from the CIDR value in calicoctl ipam show command

### ISSUE THREAD

**Issue by hahapaul** [projectcalico/calicoctl#2032]
**[[ in calico yaml file ]]** 
```
- name: CALICO_IPV4POOL_CIDR
  value: "10.244.0.0/16"
```
_and CoreDNS / calico controller PODs allocated 10.244.x.x ip address as well_
**[POD ip]**
```
 ✘ ⚡ root@master  ~  kubectl get pods -o wide -n kube-system| grep 10.244
calico-kube-controllers-59f54d6bbc-sjk9q   1/1     Running   0          3h12m   10.244.219.66   master  
coredns-5c98db65d4-4ncx2                   1/1     Running   1          26h     10.244.219.67   master  
coredns-5c98db65d4-9jzg8                   1/1     Running   1          26h     10.244.219.65   master  
```

_but in "calicoctl ipam show", ippool looks calico's default CIDR range._
**[[ calicoctl ipam show ]]**
```
 ⚡ root@master  ~  calicoctl ipam show

+----------+---------------------+------------+------------+-------------------+
| GROUPING |        CIDR         | IPS TOTAL  | IPS IN USE |     IPS FREE      |
+----------+---------------------+------------+------------+-------------------+
| IP Pool  | **192.168.0.0/16**      |      65536 | 0 (0%)     | 65536 (100%)      |
| IP Pool  | fd53:c6e7:bfe9::/48 | 1.2089e+24 | 0 (0%)     | 1.2089e+24 (100%) |
+----------+---------------------+------------+------------+-------------------+
```

## Expected Behavior

When "calicoctl ipam show" is executed, IPPool (10.244.0.0/16)  should come out properly. 

## Current Behavior

explained. 

## Steps to Reproduce (for bugs)

1. Set a value other than default to CALICO_IPV4POOL_CIDR
2. install calico as well
3. setup calicoctl 
4. calicoctl ipam show

## Your Environment

* calicoctl version (e.g. `calicoctl version`):
* calico/node version (e.g. `docker run --rm calico/node versions`)
* Orchestrator type and version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

 ⚡ root@master  ~  calicoctl version
Client Version:    v3.8.0
Git commit:        c84e9f21
Cluster Version:   v3.8.0
Cluster Type:      unknown

 ✘ ⚡ root@master  ~  docker run --rm calico/node versions
Unable to find image 'calico/node:latest' locally
latest: Pulling from calico/node
Digest: sha256:6679ccc9f19dba3eb084db991c788dc9661ad3b5d5bafaa3379644229dca6b05
Status: Downloaded newer image for calico/node:latest
v3.8.0

BIRD version v0.3.3+birdv1.6.3

 ⚡ root@master  ~  kubectl version --short
Client Version: v1.15.0
Server Version: v1.15.0

 ⚡ root@master  ~  cat /etc/lsb-release | grep DES
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

**Comment by rafaelvanoni** [comment]
@neiljerram Could you take a look at this? I think it might be in an area you made some changes to recently.

**Comment by lwr20** [comment]
CALICO_IPV4POOL_CIDR only takes effect on the first install of calico.  If calico detects that the default IPpool has already been created, this value is ignored.  

@hahapaul:  Is there any chance that you applied the yaml with the default CALICO_IPV4POOL_CIDR set and then apply the version with the edited CALICO_IPV4POOL_CIDR over the top?

Alternatively, did you install calico with the default CALICO_IPV4POOL_CIDR set, then run `kubeadm reset`, then `kubeadm init`, and install with the edited calico.yaml over that?  (`kubeadm reset` is known to not clean up calico config)

**Comment by hahapaul** [comment]
@lwr20 ok, I will try with your comment

**Comment by caseydavenport** [comment]
Any update on this one, @hahapaul ?
