### ISSUE TITLE
Add calicoctl subcommand patch

### ISSUE THREAD

**Issue by mattymo** [projectcalico/calicoctl#2047]
Issue type: Feature request

As calicoctl evolves to work more and more like kubectl, adding the subcommand patch will improve end user experience. With kubectl patch, a user can quickly modify an object and not have to parse it. Without a patch function, the user needs to write some relatively sophisticated yaml/json parser and then replace the object.

Here is an example that is both unreadable and unpleasant to maintain:
https://github.com/kubernetes-sigs/kubespray/pull/5114/files#diff-68a99474f0a01df786a37dd82338e083R15

What would be much easier could be this:
```
calicoctl patch node mynode01 -p '{"spec":{"bgp": {"routeReflectorClusterID": "CLUSTER_ID"}}}' 
```

**Comment by mattymo** [comment]
@syscll 
Strategy: I'm not too particular, so long as the scenario I described initially is possible.
JSON and YAML: of course. Feature parity with kubectl patch should be the goal
I agree that calicoctl should reject the entire patch if it partially fails.

**Comment by syscll** [comment]
SGTM - I am actively working on this so I'll post a link to the PR when I have a base implementation ready.
