### ISSUE TITLE
using vxlanMode option

### ISSUE THREAD

**Issue by msherif4** [projectcalico/calicoctl#2056]
when I try to allocate VxLAN resource with the following I get an error
vagrant@master:~$ ./calicoctl apply -f - << EOF
> apiVersion: projectcalico.org/v3
> kind: IPPool
> metadata:
>   name: ippool-vxlan-1
> spec:
>   cidr: 192.168.0.0/16
>   vxlanMode: Always
>   natOutgoing: true
> EOF
Failed to execute command: error parsing document: field in document is not recognized or is in the wrong location: vxlanMode
## Expected Behavior
it should work based on the documentation https://docs.projectcalico.org/v3.7/networking/vxlan-ipip#configure-vxlan-encapsulation-for-all-inter-workload-traffic

## Current Behavior
I get the above error 
## Your Environment
agrant@master:~$ ./calicoctl version
Client Version:    v3.5.8
Git commit:        107e128
Cluster Version:   v3.7.5
Cluster Type:      k8s,bgp,kdd

orchestration: k8s

**Comment by lwr20** [comment]
VXLAN support is a feature in Calico v3.7 (as you can see from the docs path you referenced).  The calicoctl you are using is v3.5.8 and obviously does not recognise the VXLAN setting.

Please upgrade your calicoctl to v3.7.x

**Comment by msherif4** [comment]
Thanks!
