### ISSUE TITLE
v3.11.0 darwin release binary is not a Mach-O binary

### ISSUE THREAD

**Issue by teejaded** [projectcalico/calicoctl#2091]
## Expected Behavior
Expected Mach-O binary.  

## Current Behavior
Downloaded linux ELF binary after clicking the darwin link.

```
rm calicoctl && wget -q https://github.com/projectcalico/calicoctl/releases/download/v3.11.0/calicoctl-darwin-amd64 -O calicoctl && file calicoctl
calicoctl: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
```

**Comment by lmm** [comment]
Thanks for reporting this @teejaded. The v3.10.x series of releases have the right calicoctl darwin binaries. I'll try looking into this later today.

**Comment by lmm** [comment]
@teejaded fyi, the fixed binaries have been uploaded
