### ISSUE TITLE
v3.11.1 binaries are all the same x86-64 executables!

### ISSUE THREAD

**Issue by reneklomp** [projectcalico/calicoctl#2093]
I downloaded the v3.11.1 binary for ARM64 but it fails to execute:
-bash: /usr/local/bin/calicoctl: cannot execute binary file: Exec format error
Comparing with other v3.11.1 binaries it appears they are all the same x86-64 executables.

**Comment by tmjd** [comment]
Thank you for reporting this, it is a known issue and work has been started to fix this.
Fixed by #2092

**Comment by lmm** [comment]
@reneklomp the binaries are fixed now. Thanks for the report! 🙂
