### ISSUE TITLE
Latest version marking issue

### ISSUE THREAD

**Issue by admgolovin** [projectcalico/calicoctl#2104]
I have faced with the strange behavior of marking the latest version of calicoctl:
I believe that the version list should look like this:

 calicoctl v3.8.6
 calicoctl v3.9.5
 calicoctl v3.10.2
 calicoctl v3.10.3
 calicoctl v3.11.0
 calicoctl v3.11.1 -- latest

But currently, my script that installs the latest version of the calicoctl shows the following statistic of latest tags:

 calicoctl v3.10.2
 calicoctl v3.11.0
 calicoctl v3.11.1
 calicoctl v3.8.6
 calicoctl v3.9.5
 calicoctl v3.10.3
 calicoctl v3.9.5 -- latest

Is there some reason for those marking, or there is some issue with that?

**Comment by tmjd** [comment]
@lmm you've been doing the releases recently, do we need to adjust our processes to make sure we don't incorrectly mark the latest?

**Comment by lmm** [comment]
@admgolovin GitHub automatically marks the latest release (in terms of creation date) as the "latest". So when any release is published for a component, even a patch release like v3.9.5, it gets tagged as "latest". A quick google tells me that creating releases manually via the UI apparently gives you the option to mark a release as latest or not(?). But the API doesn't give us that option unfortunately: https://developer.github.com/v3/repos/releases/#edit-a-release

**Comment by lmm** [comment]
Another option is to use docker. All of the "latest" Calico component images should have the latest release version embedded. E.g.:
```
$ docker run --rm calico/ctl:latest version
no etcd endpoints specified
Client Version:    v3.11.1
Git commit:        6c04a83
```

**Comment by caseydavenport** [comment]
> A quick google tells me that creating releases manually via the UI apparently gives you the option to mark a release as latest or not

I'm not aware of any way to do this - could you share the link? I think GitHub just always marks the latest chronologically as the latest (it is not semantic version aware). I think this is just how GitHub is, unfortunately.
