### ISSUE TITLE
release v3.13.1 and v3.13.0 tagged the same commit

### ISSUE THREAD

**Issue by chenrui333** [projectcalico/calicoctl#2111]
Just want to make sure that is desired.

relates to https://github.com/Homebrew/homebrew-core/pull/51668

**Comment by spikecurtis** [comment]
@chenrui333 from context, I think you're talking about 3.13.x, not 3.1.x, but please correct me if I'm wrong!

**Comment by chenrui333** [comment]
@spikecurtis, yes, sorry for the typo. (the PR I linked basically tells the story 😄 )

**Comment by spikecurtis** [comment]
I've spoken to the release team, and yes, this is as expected. Only changes were in Felix / node.
