### ISSUE TITLE
release tag calicoctl 3.13.{0,1,2} are tagged against the same commit

### ISSUE THREAD

**Issue by chenrui333** [projectcalico/calicoctl#2115]
relates to https://github.com/Homebrew/homebrew-core/pull/52361
previously mentioned in this issue, https://github.com/projectcalico/calicoctl/issues/2111

@spikecurtis, just to check again, whether this is desired that all three release tags are tagged against the same commit, https://github.com/projectcalico/calicoctl/commit/eb796e31bcbfb42af3c2470bd23826f630d03ab5

**Comment by chenrui333** [comment]
The release process seems not quite ideal (I wonder if I can see the code and help with it).

**Comment by spikecurtis** [comment]
Calico operates with a single version number for an entire release, including all our components and tools.  These patch releases are often related to bug fixes on a limited number of components, so not all repos will get new commits; many components do not change.
