### ISSUE TITLE
Failed to make calicoctl

### ISSUE THREAD

**Issue by elgamal2020** [projectcalico/calicoctl#2118]
sudo make build
make build-calicoctl BUILDOS=linux ARCH=amd64
make[1]: Entering directory '/home/ubuntu/calicoctl'
mkdir -p bin
mkdir -p .go-pkg-cache bin /home/ubuntu/go/pkg/mod && docker run --rm --net=host --init -e GO111MODULE=on -v /home/ubuntu/go/pkg/mod:/go/pkg/mod:rw -e LOCAL_USER_ID=0 -e GOCACHE=/go-cache -e GOARCH=amd64 -e GOPATH=/go -e OS=linux -e GOOS=linux -e GOFLAGS= -v /home/ubuntu/calicoctl:/go/src/github.com/projectcalico/calicoctl:rw -v /home/ubuntu/calicoctl/.go-pkg-cache:/go-cache:rw -w /go/src/github.com/projectcalico/calicoctl \
  -e CALICOCTL_GIT_REVISION=31c11cc4 \
  -v /home/ubuntu/calicoctl/bin:/go/src/github.com/projectcalico/calicoctl/bin \
  calico/go-build:v0.37 \
  go build -v -o bin/calicoctl-linux-amd64 -ldflags "-X github.com/projectcalico/calicoctl/calicoctl/commands.VERSION=v3.14.0-0.dev-17-g31c11cc4 -X github.com/projectcalico/calicoctl/calicoctl/commands.GIT_REVISION=31c11cc4 -s -w" "./calicoctl/calicoctl.go"
Unable to find image 'calico/go-build:v0.37' locally
v0.37: Pulling from calico/go-build
dc65f448a2e2: Pull complete
346ffb2b67d7: Pull complete
dea4ecac934f: Pull complete
8ac92ddf84b3: Pull complete
7ca605383307: Pull complete
bd20b51e1705: Pull complete
844755650966: Pull complete
e0dfbc562a44: Pull complete
0a29b5bd0caa: Pull complete
408c32def1cf: Pull complete
ed121b046459: Pull complete
7252684114a2: Pull complete
06ff37e6958d: Pull complete
e5fea6172e11: Pull complete
de431733e571: Pull complete
7671056f9657: Pull complete
6d295e1fde9e: Pull complete
d19376eb77e9: Pull complete
ad042b68362c: Pull complete
Digest: sha256:5a2a3c88bcd52997ed4b58fc69ab77dc285d0fa12b3a87e25a1ccadb061f8237
Status: Downloaded newer image for calico/go-build:v0.37
Starting with UID : 0
useradd: UID 0 is not unique
su-exec: getpwnam(user): Success
Makefile:89: recipe for target 'build-calicoctl' failed
make[1]: *** [build-calicoctl] Error 1
make[1]: Leaving directory '/home/ubuntu/calicoctl'
Makefile:87: recipe for target 'bin/calicoctl-linux-amd64' failed
make: *** [bin/calicoctl-linux-amd64] Error 2
ubuntu@node11:~/calicoctl$ sudo make build^C
ubuntu@node11:~/calicoctl$ ll
total 236
drwxrwxr-x 12 ubuntu ubuntu  4096 Apr 21 02:31 ./
drwxr-xr-x  9 ubuntu ubuntu  4096 Apr 21 02:31 ../
drwxrwxr-x  2 ubuntu ubuntu  4096 Apr 21 02:30 .circleci/
-rw-rw-r--  1 ubuntu ubuntu    36 Apr 21 02:30 .dockerignore
-rw-rw-r--  1 ubuntu ubuntu   476 Apr 21 02:30 .fossa.yml
drwxrwxr-x  8 ubuntu ubuntu  4096 Apr 21 02:34 .git/
drwxrwxr-x  2 ubuntu ubuntu  4096 Apr 21 02:30 .github/
-rw-rw-r--  1 ubuntu ubuntu   253 Apr 21 02:30 .gitignore
drwxrwxr-x  2 ubuntu ubuntu  4096 Apr 21 02:31 .go-pkg-cache/
-rw-rw-r--  1 ubuntu ubuntu  4914 Apr 21 02:30 CONTRIBUTING.md
lrwxrwxrwx  1 ubuntu ubuntu    16 Apr 21 02:30 Dockerfile -> Dockerfile.amd64
-rw-rw-r--  1 ubuntu ubuntu  1153 Apr 21 02:30 Dockerfile.amd64
-rw-rw-r--  1 ubuntu ubuntu   202 Apr 21 02:30 Dockerfile.arm64
-rw-rw-r--  1 ubuntu ubuntu   204 Apr 21 02:30 Dockerfile.ppc64le
-rw-rw-r--  1 ubuntu ubuntu   269 Apr 21 02:30 Dockerfile.s390x
-rw-rw-r--  1 ubuntu ubuntu 10143 Apr 21 02:30 LICENSE
-rw-rw-r--  1 ubuntu ubuntu 15710 Apr 21 02:30 Makefile
-rw-rw-r--  1 ubuntu ubuntu 13201 Apr 21 02:31 Makefile.common
-rw-rw-r--  1 ubuntu ubuntu 13201 Apr 21 02:31 Makefile.common.v0.37
-rw-rw-r--  1 ubuntu ubuntu  2510 Apr 21 02:30 README.md
-rw-rw-r--  1 ubuntu ubuntu  2444 Apr 21 02:30 RELEASING.md
drwxrwxr-x  2 ubuntu ubuntu  4096 Apr 21 02:31 bin/
drwxrwxr-x  5 ubuntu ubuntu  4096 Apr 21 02:30 calicoctl/
drwxrwxr-x  2 ubuntu ubuntu  4096 Apr 21 02:30 git-hooks/
-rw-rw-r--  1 ubuntu ubuntu  1781 Apr 21 02:30 go.mod
-rw-rw-r--  1 ubuntu ubuntu 73766 Apr 21 02:30 go.sum
-rwxrwxr-x  1 ubuntu ubuntu    63 Apr 21 02:30 install-git-hooks*
drwxrwxr-x  2 ubuntu ubuntu  4096 Apr 21 02:30 report/
drwxrwxr-x  4 ubuntu ubuntu  4096 Apr 21 02:30 test-data/
drwxrwxr-x  4 ubuntu ubuntu  4096 Apr 21 02:30 tests/
ubuntu@node11:~/calicoctl$ cd bin/
ubuntu@node11:~/calicoctl/bin$ ll
total 8
drwxrwxr-x  2 ubuntu ubuntu 4096 Apr 21 02:31 ./
drwxrwxr-x 12 ubuntu ubuntu 4096 Apr 21 02:31 ../
ubuntu@node11:~/calicoctl/bin$ cd ..
ubuntu@node11:~/calicoctl$ ll calicoctl/
calicoctl.go  commands/     resourcemgr/  util/
ubuntu@node11:~/calicoctl$ sudo make build OS=linux ARCH=amd64
make build-calicoctl BUILDOS=linux ARCH=amd64
make[1]: Entering directory '/home/ubuntu/calicoctl'
mkdir -p bin
mkdir -p .go-pkg-cache bin /home/ubuntu/go/pkg/mod && docker run --rm --net=host --init -e GO111MODULE=on -v /home/ubuntu/go/pkg/mod:/go/pkg/mod:rw -e LOCAL_USER_ID=0 -e GOCACHE=/go-cache -e GOARCH=amd64 -e GOPATH=/go -e OS=linux -e GOOS=linux -e GOFLAGS= -v /home/ubuntu/calicoctl:/go/src/github.com/projectcalico/calicoctl:rw -v /home/ubuntu/calicoctl/.go-pkg-cache:/go-cache:rw -w /go/src/github.com/projectcalico/calicoctl \
  -e CALICOCTL_GIT_REVISION=31c11cc4 \
  -v /home/ubuntu/calicoctl/bin:/go/src/github.com/projectcalico/calicoctl/bin \
  calico/go-build:v0.37 \
  go build -v -o bin/calicoctl-linux-amd64 -ldflags "-X github.com/projectcalico/calicoctl/calicoctl/commands.VERSION=v3.14.0-0.dev-17-g31c11cc4 -X github.com/projectcalico/calicoctl/calicoctl/commands.GIT_REVISION=31c11cc4 -s -w" "./calicoctl/calicoctl.go"
Starting with UID : 0
useradd: UID 0 is not unique
su-exec: getpwnam(user): Success
Makefile:89: recipe for target 'build-calicoctl' failed
make[1]: *** [build-calicoctl] Error 1
make[1]: Leaving directory '/home/ubuntu/calicoctl'
Makefile:87: recipe for target 'bin/calicoctl-linux-amd64' failed
make: *** [bin/calicoctl-linux-amd64] Error 2
ubuntu@node11:~/calicoctl$ ll
total 236
drwxrwxr-x 12 ubuntu ubuntu  4096 Apr 21 02:31 ./
drwxr-xr-x  9 ubuntu ubuntu  4096 Apr 21 02:31 ../
drwxrwxr-x  2 ubuntu ubuntu  4096 Apr 21 02:30 .circleci/
-rw-rw-r--  1 ubuntu ubuntu    36 Apr 21 02:30 .dockerignore
-rw-rw-r--  1 ubuntu ubuntu   476 Apr 21 02:30 .fossa.yml
drwxrwxr-x  8 ubuntu ubuntu  4096 Apr 21 02:40 .git/
drwxrwxr-x  2 ubuntu ubuntu  4096 Apr 21 02:30 .github/
-rw-rw-r--  1 ubuntu ubuntu   253 Apr 21 02:30 .gitignore
drwxrwxr-x  2 ubuntu ubuntu  4096 Apr 21 02:31 .go-pkg-cache/
-rw-rw-r--  1 ubuntu ubuntu  4914 Apr 21 02:30 CONTRIBUTING.md
lrwxrwxrwx  1 ubuntu ubuntu    16 Apr 21 02:30 Dockerfile -> Dockerfile.amd64
-rw-rw-r--  1 ubuntu ubuntu  1153 Apr 21 02:30 Dockerfile.amd64
-rw-rw-r--  1 ubuntu ubuntu   202 Apr 21 02:30 Dockerfile.arm64
-rw-rw-r--  1 ubuntu ubuntu   204 Apr 21 02:30 Dockerfile.ppc64le
-rw-rw-r--  1 ubuntu ubuntu   269 Apr 21 02:30 Dockerfile.s390x
-rw-rw-r--  1 ubuntu ubuntu 10143 Apr 21 02:30 LICENSE
-rw-rw-r--  1 ubuntu ubuntu 15710 Apr 21 02:30 Makefile
-rw-rw-r--  1 ubuntu ubuntu 13201 Apr 21 02:31 Makefile.common
-rw-rw-r--  1 ubuntu ubuntu 13201 Apr 21 02:31 Makefile.common.v0.37
-rw-rw-r--  1 ubuntu ubuntu  2510 Apr 21 02:30 README.md
-rw-rw-r--  1 ubuntu ubuntu  2444 Apr 21 02:30 RELEASING.md
drwxrwxr-x  2 ubuntu ubuntu  4096 Apr 21 02:31 bin/
drwxrwxr-x  5 ubuntu ubuntu  4096 Apr 21 02:30 calicoctl/
drwxrwxr-x  2 ubuntu ubuntu  4096 Apr 21 02:30 git-hooks/
-rw-rw-r--  1 ubuntu ubuntu  1781 Apr 21 02:30 go.mod
-rw-rw-r--  1 ubuntu ubuntu 73766 Apr 21 02:30 go.sum
-rwxrwxr-x  1 ubuntu ubuntu    63 Apr 21 02:30 install-git-hooks*
drwxrwxr-x  2 ubuntu ubuntu  4096 Apr 21 02:30 report/
drwxrwxr-x  4 ubuntu ubuntu  4096 Apr 21 02:30 test-data/
drwxrwxr-x  4 ubuntu ubuntu  4096 Apr 21 02:30 tests/

**Comment by caseydavenport** [comment]
Please don't run the build as `sudo` - you shouldn't need to! 

`make build` is working for me.

**Comment by elgamal2020** [comment]
Hi no , it dosnt work for me , did you try with ubuntu 18.04 ?

**Comment by 420691301** [comment]
I encountered the same error. Because I always use root by default in my development environment. `useradd` will go wrong with `LOCAL_USER_ID=0`. How about using `RUN_AS_ROOT=true` instead of `LOCAL_USER_ID=$(LOCAL_USER_ID)` when `LOCAL_USER_ID` is 0?

**Comment by gunboe** [comment]
Dont use sudo!

Add the docker group if it doesn't already exist:
```
sudo groupadd docker
```

Add the connected user "$USER" to the docker group. Change the user name to match your preferred user if you do not want to use your current user:
```
sudo gpasswd -a $USER docker
```

Either do a `newgrp docker` or log out/in (prefer) to activate the changes to groups.

Finaly, you can use:
```
docker run hello-world
```

to check if you can run docker without sudo.
