### ISSUE TITLE
POD connectivity within K8s installed over openstack / IPIP encapsulation 

### ISSUE THREAD

**Issue by elgamal2020** [projectcalico/calicoctl#2136]
Hello,
 
I have two cluster , each with 3 nodes with roles (master/worker) one setup on virtualbox and another on Openstack
 
For the Virtualbox environment , there are no problems I tried IPIP encap to always,never and cross subnet and the pod to pod communication across nodes are working perfectly 
 
In the Openstack environment when I set the IPIP encap to never pod to pod communication across the 3 nodes are functioning 
 
But when set to cross-subnet or always , it is not anymore working 
“Crosssubnet should work as the 3 VMs are sharing the same Openstack subnet”
 
I suspect the MTU size , so the MTU inside the pod has the following 
 ```
```

ifconfig -a
eth0     Link encap:Ethernet HWaddr C6:74:36:72:04:44
         inet addr:10.233.90.42 Bcast:0.0.0.0 Mask:255.255.255.255
         UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
         RX packets:195 errors:0 dropped:0 overruns:0 frame:0
         TX packets:6593 errors:0 dropped:0 overruns:0 carrier:0
         collisions:0 txqueuelen:0
         RX bytes:9070 (8.8 KiB) TX bytes:636426 (621.5 KiB)

lo       Link encap:Local Loopback
         inet addr:127.0.0.1 Mask:255.0.0.0
         UP LOOPBACK RUNNING MTU:65536 Metric:1
         RX packets:0 errors:0 dropped:0 overruns:0 frame:0
         TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
         collisions:0 txqueuelen:1000
         RX bytes:0 (0.0 B) TX bytes:0 (0.0 B)

tunl0    Link encap:UNSPEC HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
         NOARP MTU:1480 Metric:1
         RX packets:0 errors:0 dropped:0 overruns:0 frame:0
         TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
         collisions:0 txqueuelen:1000
         RX bytes:0 (0.0 B) TX bytes:0 (0.0 B)
```
 
```
Then the MTU of the tunnel interface at the nodes are t
tunl0: flags=193<UP,RUNNING,NOARP> mtu 1440
 

**

- [ ] Could you please guide me what will be the correct MTU frames inside an Openstack environment ?
- 
- [ ] Also why it is not working when I configure it to CrossSubnet although it is working on the same subnet and there should be no encapsulation ?

**

 
kubectl get nodes -o wide
NAME   STATUS  ROLES   AGE  VERSION  INTERNAL-IP   EXTERNAL-IP  OS-IMAGE            KERNEL-VERSION      CONTAINER-RUNTIME
node1   Ready   master  15d  v1.18.2  10.20.100.19  <none>       Ubuntu 18.04.1 LTS  4.15.0-106-generic  docker://18.9.7
node2  Ready   master  15d  v1.18.2  10.20.100.29  <none>       Ubuntu 18.04.1 LTS  4.15.0-101-generic  docker://18.9.7
node3  Ready   master  15d  v1.18.2  10.20.100.26  <none>       Ubuntu 18.04.1 LTS  4.15.0-101-generic  docker://18.9.7

HOST ifconfig
```
ifconfig -a
cali0ac0f731f3f: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
       inet6 fe80::ecee:eeff:feee:eeee prefixlen 64 scopeid 0x20<link>
       ether ee:ee:ee:ee:ee:ee txqueuelen 0 (Ethernet)
       RX packets 85248 bytes 7097164 (7.0 MB)
       RX errors 0 dropped 0 overruns 0 frame 0
       TX packets 89384 bytes 30596844 (30.5 MB)
       TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

cali3afb93a317d: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
       inet6 fe80::ecee:eeff:feee:eeee prefixlen 64 scopeid 0x20<link>
       ether ee:ee:ee:ee:ee:ee txqueuelen 0 (Ethernet)
       RX packets 0 bytes 0 (0.0 B)
       RX errors 0 dropped 0 overruns 0 frame 0
       TX packets 26 bytes 1916 (1.9 KB)
       TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

cali557e553306b: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
       inet6 fe80::ecee:eeff:feee:eeee prefixlen 64 scopeid 0x20<link>
       ether ee:ee:ee:ee:ee:ee txqueuelen 0 (Ethernet)
       RX packets 555 bytes 53606 (53.6 KB)
       RX errors 0 dropped 0 overruns 0 frame 0
       TX packets 549 bytes 52386 (52.3 KB)
       TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

cali591c35bc76a: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
       inet6 fe80::ecee:eeff:feee:eeee prefixlen 64 scopeid 0x20<link>
       ether ee:ee:ee:ee:ee:ee txqueuelen 0 (Ethernet)
       RX packets 0 bytes 0 (0.0 B)
       RX errors 0 dropped 0 overruns 0 frame 0
       TX packets 26 bytes 1916 (1.9 KB)
       TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

calib3cf52b9376: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
       inet6 fe80::ecee:eeff:feee:eeee prefixlen 64 scopeid 0x20<link>
       ether ee:ee:ee:ee:ee:ee txqueuelen 0 (Ethernet)
       RX packets 112 bytes 10640 (10.6 KB)
       RX errors 0 dropped 0 overruns 0 frame 0
       TX packets 93 bytes 8146 (8.1 KB)
       TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

calidb39aa71068: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
       inet6 fe80::ecee:eeff:feee:eeee prefixlen 64 scopeid 0x20<link>
       ether ee:ee:ee:ee:ee:ee txqueuelen 0 (Ethernet)
       RX packets 43649 bytes 10013072 (10.0 MB)
       RX errors 0 dropped 0 overruns 0 frame 0
       TX packets 57191 bytes 6562605 (6.5 MB)
       TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST> mtu 1500
       inet 172.17.0.1 netmask 255.255.0.0 broadcast 172.17.255.255
       ether 02:42:10:8f:f4:6b txqueuelen 0 (Ethernet)
       RX packets 0 bytes 0 (0.0 B)
       RX errors 0 dropped 0 overruns 0 frame 0
       TX packets 0 bytes 0 (0.0 B)
       TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

ens3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
       inet 10.20.100.29 netmask 255.255.255.0 broadcast 10.20.100.255
       inet6 fe80::f816:3eff:fe28:9b0c prefixlen 64 scopeid 0x20<link>
       ether fa:16:3e:28:9b:0c txqueuelen 1000 (Ethernet)
       RX packets 6448135 bytes 1188170195 (1.1 GB)
       RX errors 0 dropped 0 overruns 0 frame 0
       TX packets 6404416 bytes 1207331697 (1.2 GB)
       TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

ens4: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
       inet 10.20.10.12 netmask 255.255.255.0 broadcast 10.20.10.255
       inet6 fe80::f816:3eff:fe77:c8ec prefixlen 64 scopeid 0x20<link>
       ether fa:16:3e:77:c8:ec txqueuelen 1000 (Ethernet)
       RX packets 93 bytes 12354 (12.3 KB)
       RX errors 0 dropped 0 overruns 0 frame 0
       TX packets 61 bytes 4782 (4.7 KB)
       TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

kube-ipvs0: flags=130<BROADCAST,NOARP> mtu 1500
       inet 10.233.0.1 netmask 255.255.255.255 broadcast 10.233.0.1
       ether ae:c9:71:40:f5:b5 txqueuelen 0 (Ethernet)
       RX packets 0 bytes 0 (0.0 B)
       RX errors 0 dropped 0 overruns 0 frame 0
       TX packets 0 bytes 0 (0.0 B)
       TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING> mtu 65536
       inet 127.0.0.1 netmask 255.0.0.0
       inet6 ::1 prefixlen 128 scopeid 0x10<host>
       loop txqueuelen 1000 (Local Loopback)
       RX packets 4928870 bytes 1251320435 (1.2 GB)
       RX errors 0 dropped 0 overruns 0 frame 0
       TX packets 4928870 bytes 1251320435 (1.2 GB)
       TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

nodelocaldns: flags=130<BROADCAST,NOARP> mtu 1500
       inet 169.254.25.10 netmask 255.255.255.255 broadcast 169.254.25.10
       ether ea:99:94:2d:66:c5 txqueuelen 0 (Ethernet)
       RX packets 0 bytes 0 (0.0 B)
       RX errors 0 dropped 0 overruns 0 frame 0
       TX packets 0 bytes 0 (0.0 B)
       TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

tunl0: flags=193<UP,RUNNING,NOARP> mtu 1440
       inet 10.233.96.33 netmask 255.255.255.255
       tunnel  txqueuelen 1000 (IPIP Tunnel)
       RX packets 0 bytes 0 (0.0 B)
       RX errors 0 dropped 0 overruns 0 frame 0
       TX packets 544 bytes 72149 (72.1 KB)
       TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

```

Inside the pod 

ifconfig -a
eth0     Link encap:Ethernet HWaddr C6:74:36:72:04:44
         inet addr:10.233.90.42 Bcast:0.0.0.0 Mask:255.255.255.255
         UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
         RX packets:195 errors:0 dropped:0 overruns:0 frame:0
         TX packets:6593 errors:0 dropped:0 overruns:0 carrier:0
         collisions:0 txqueuelen:0
         RX bytes:9070 (8.8 KiB) TX bytes:636426 (621.5 KiB)

lo       Link encap:Local Loopback
         inet addr:127.0.0.1 Mask:255.0.0.0
         UP LOOPBACK RUNNING MTU:65536 Metric:1
         RX packets:0 errors:0 dropped:0 overruns:0 frame:0
         TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
         collisions:0 txqueuelen:1000
         RX bytes:0 (0.0 B) TX bytes:0 (0.0 B)

tunl0    Link encap:UNSPEC HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
         NOARP MTU:1480 Metric:1
         RX packets:0 errors:0 dropped:0 overruns:0 frame:0
         TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
         collisions:0 txqueuelen:1000
         RX bytes:0 (0.0 B) TX bytes:0 (0.0 B)


``````

sudo -i calicoctl get ippool --config /home/ubuntu/calicoctl.cfg -o wide
NAME          CIDR            NAT   IPIPMODE  VXLANMODE  DISABLED  SELECTOR
default-pool  10.233.64.0/18  true  Always    Never      false     all()
sudo  calicoctl version
Client Version:   v3.14.0
Git commit:       c97876ba
no etcd endpoints specified
sudo  calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |    PEER TYPE    | STATE | SINCE  |   INFO    |
+--------------+-------------------+-------+----------+-------------+
| 10.20.100.29 | node-to-node mesh | up   | 13:33:56 | Established |
| 10.20.100.26 | node-to-node mesh | up   | 13:33:56 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.
```
```

**Comment by caseydavenport** [comment]
Have you checked to make sure there is not RPF enabled in your underlying OpenStack network? Even if it is a L2 network, if RPF is being performed that may block packets from pod IP addresses. You'll either need to disable the RPF in the openstack network, or use encap within the L2 subnet.

This is similar to AWS, where you'd need to disable src/dst checks to use unencap'd traffic within a subnet.

**Comment by elgamal2020** [comment]
Hi Casey,

Thanks a lot for your answer , I have disabled the antispoofing allowing the POD CIDR adresses on my port 

  443  openstack port set c0b1fc21-2dd7-4bf3-9d4e-ab23f341d7f8  --allowed-address ip-address=10.233.64.0/18
  444  openstack port set 53cd2e3d-0c13-492c-a09f-721457659b2a  --allowed-address ip-address=10.233.64.0/18
  445  openstack port set b2c49dba-3b8a-4f29-82d5-8386d093841f --allowed-address ip-address=10.233.64.0/18


If not , it will not work with Encap set to never , here I am really suspecting the MTU setting , but I dont know what the exact values should be configured
