### ISSUE TITLE
calicoctl v3.16.1 binary does not run on macOS

### ISSUE THREAD

**Issue by askulkarni2** [projectcalico/calicoctl#2182]
Tried to run calicoctl the latest version v3.16.1 on MacOS and it appears to be broken. Previous version works as expected.

## Steps to Reproduce (for bugs)
```
$ curl -O -L  https://github.com/projectcalico/calicoctl/releases/download/v3.16.1/calicoctl-darwin-amd64
$ chmod +x calicoctl-darwin-amd64
$ mv calicoctl-darwin-amd64 calicoctl
$ ./calicoctl -h 
zsh: exec format error: calicoctl
```

Previous [version](https://github.com/projectcalico/calicoctl/releases/download/v3.16.0/calicoctl-darwin-amd64) works as expected using the same steps.

## Your Environment
* Operating System and version: macOS Mojave

**Comment by lmm** [comment]
@askulkarni2 could you try again? I tried the same steps on my Mojave macbook and calicoctl worked for me.

**Comment by askulkarni2** [comment]
@lmm its working now, though I am not sure what changed :)
