### ISSUE TITLE
Node diagnostic error dumping felix stats

### ISSUE THREAD

**Issue by tanvp112** [projectcalico/calicoctl#2241]
```
$ sudo calicoctl node diags --log-dir=$PWD
Collecting diagnostics
Using temp dir: /tmp/calico885665184
Dumping netstat
Dumping routes (IPv4)
Dumping routes (IPv6)
Dumping interface info (IPv4)
Dumping interface info (IPv6)
Dumping iptables (IPv4)
Dumping iptables (IPv6)
Dumping ipsets
Dumping ipsets (container)
Copying journal for calico-node.service
Dumping felix stats
**_Failed to run command: pkill -SIGUSR1 felix
Error:
Copying Calico logs
Error creating log directory: mkdir /tmp/calico885665184/diagnostics/logs: file exists_**

Diags saved to /tmp/calico885665184/diags-20201227_135403.tar.gz
If required, you can upload the diagnostics bundle to a file sharing service
such as transfer.sh using curl or similar.  For example:

    curl --upload-file /tmp/calico885665184/diags-20201227_135403.tar.gz https://transfer.sh//tmp/calico885665184/diags-20201227_135403.tar.gz

```
There is nothing in the logs directory complaint:

$ ls -l /tmp/calico885665184/diagnostics/logs
total 0

--log-dir seems has no effect, too.

**Comment by caseydavenport** [comment]
> Dumping felix stats

This will only gather data if felix is running on the local node, which it isn't always. Did the other data collect properly (e.g., iptables, routes, etc)?

Is calico/node running on the node that you ran this command on?

**Comment by tanvp112** [comment]
$ sudo calicoctl node status
Calico process is running.

IPv4 BGP status
+---------------+-------------------+-------+----------+-------------+
| PEER ADDRESS  |     PEER TYPE     | STATE |  SINCE    |    INFO        |
+---------------+-------------------+-------+----------+-------------+
| xxx.xxx.xxx.xxx | node-to-node mesh | up    | 01:49:17 | Established |
+---------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.

Any other command I can use to check further?

**Comment by song-jiang** [comment]
`ps -aux  | grep felix ` to see if felix process is running.

**Comment by tanvp112** [comment]
yes, run as root with command: calico-node -felix

**Comment by lmm** [comment]
Hi @tanvp112 , are you still having issues with `calicoctl node status`?

**Comment by tanvp112** [comment]
hi, the issue is the following command. Please see first message.

sudo calicoctl node diags --log-dir=$PWD
