### ISSUE TITLE
Container runtime support for calicoctl

### ISSUE THREAD

**Issue by kidrocknroll** [projectcalico/calicoctl#2242]
Container Runtime support for `calicoctl`?

## Expected Behavior

`calico node status` will show node status

## Current Behavior

Now is empty

![image](https://user-images.githubusercontent.com/22533109/103191215-19231a00-490f-11eb-999d-6ca3f589579c.png)

![image](https://user-images.githubusercontent.com/22533109/103191252-33f58e80-490f-11eb-81be-380964530317.png)

## Possible Solution

Maybe this is because `calicoctl` does not support CRI-O? I am new here and I try to search for supporting arguments about container runtime, Only find [this issue](https://github.com/projectcalico/calicoctl/issues/564) related... Since docker and k8s are possibly split away in the future, will `--runtime` be added more option?

## Context

![image](https://user-images.githubusercontent.com/22533109/103191616-969b5a00-4910-11eb-9216-5047380cb60e.png)

## Your Environment

* calicoctl version:

```
Client Version:    v3.16.3
Git commit:        7d066703
```

* calico/node version:

```
calico v3.16.3
```

* Orchestrator type and version:

```
kubernetes v1.18.14

[root@VM-128-16-centos ~]# crio --version
crio version 1.18.4
Version:       1.18.4
GitCommit:     aba91e59ec78e3299e443a7364e2cf8909af4606
GitTreeState:  dirty
BuildDate:     2020-12-23T11:46:56Z
GoVersion:     go1.14.7
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

* Operating System and version:

```
Centos 7
```

**Comment by caseydavenport** [comment]
@kidrocknroll what makes you think that something is wrong?

It looks like calicoctl has detected the Calico is running on that node, and that it is not peered with anything else. I don't think container runtime should impact this command, since it communicates through the bird.ctl socket rather than container-runtime specific mechanisms.

**Comment by kidrocknroll** [comment]
> @kidrocknroll what makes you think that something is wrong?
> 
> It looks like calicoctl has detected the Calico is running on that node, and that it is not peered with anything else. I don't think container runtime should impact this command, since it communicates through the bird.ctl socket rather than container-runtime specific mechanisms.

Sry for the delay... My Problem is why Calicoctl shows `No IPv4 Peer Found` while I have at least one node indeed...

**Comment by caseydavenport** [comment]
How did you install Calico? Do you have BGP peers configured or are you using VXLAN mode?
