### ISSUE TITLE
Why the prompt for `sudo` when executing `calicoctl node checksystem`?

### ISSUE THREAD

**Issue by cdancy** [projectcalico/calicoctl#2268]
For all tools running against a given k8s system that I've ever used I've never found one that prompted me to run with `sudo`. I guess my assumption is that should I have the necessary access to the k8s system than that in itself would define the necessary permissions. Maybe there is some history here I'm missing?

**Comment by lmm** [comment]
Hey @cdancy - the `node checksystem` command actually runs some checks against the node machine itself. It's used to determine if the host is capable of running Calico but I think that the command might be a bit out of date.

**Comment by cdancy** [comment]
Ok fair enough. I just see various reference in your guys code to check for root/sudo when I would think that, should the user have the necessary credentials in their relevant kubeconfig then any of the internal commands (assuming calico is installed of course) would just work. That seems to be the standard amongst other projects (i.e. kubectl, istioctl, glooctl, etc..).
________________________________

**Comment by lmm** [comment]
@cdancy I think you're right that we should be limiting sudo usage. In this specific case, you might be logged onto the node as a normal user without access to the files needed by the `node checksystem` command hence the sudo (maybe there's another way of doing those checks?)
