### ISSUE TITLE
the calico can not working well

### ISSUE THREAD

**Issue by auqf** [projectcalico/calicoctl#2290]
the calicoctl yaml is https://docs.projectcalico.org/manifests/calicoctl.yaml and the calico yaml is https://docs.projectcalico.org/manifests/tigera-operator.yaml
![image](https://user-images.githubusercontent.com/8895540/112403405-4f730880-8d49-11eb-9cdc-408cb42b7adf.png)
![image](https://user-images.githubusercontent.com/8895540/112403428-5d288e00-8d49-11eb-8d25-21e8bd038a4e.png)

**Comment by song-jiang** [comment]
@auqf What is the status of calico-node and operator pods by running `kubectl get pod -A`?
