### ISSUE TITLE
we shouldn't need the --log-dir option for calicoctl diags

### ISSUE THREAD

**Issue by spikecurtis** [projectcalico/calicoctl#560]
The log dir is set when `calicoctl node` is activated, so we shouldn't need to use the --log-dir option when we gather diagnostics.  If the node container is running or stopped but not removed, we can get the logging dir using `docker inspect`.  

The only time a user should need to use this option is if they used a custom director AND have removed the calico-node container.  (So don't remove it completely.)

**Comment by matthewdupre** [comment]
I've took a quick look at what supporting this would mean, and a few things jumped out.

1. We don't use --log-dir for rkt or the libnetwork plugin.  As such this issue doesn't apply, but we should get round to doing them.

**Comment by matthewdupre** [comment]
(Oops, accidentally hit close)

**Comment by caseydavenport** [comment]
Closing as wont fix for now, feel free to re-open if someone cares to implement this.
