### ISSUE TITLE
How to limit the network speed between containers managed by calico?

### ISSUE THREAD

**Issue by frostynova** [projectcalico/calicoctl#577]

**Comment by robbrockbank** [comment]
Hi @frostynova - this is something that has had a little thought, but not progressed very far.

Do you have a specific use case that that you can share and any thoughts on grnularity of configuration etc.

**Comment by frostynova** [comment]
@robbrockbank Maybe we can use iptables + tc to limit the "calixxxx" interfaces?

**Comment by robbrockbank** [comment]
Hi @frostynova - yes our line of thinking had led us to tc.  We were keen to get thoughts on use cases so that we could discuss how this would look to the user.  Do you have any thoughts on what you'd like to see?

**Comment by frostynova** [comment]
@robbrockbank It will be better to be a key-value in etcd, so that our controllers can set it dynamically

**Comment by robbrockbank** [comment]
@frostynova 

There are discussions about in the core Calico team regarding QoS, of which this would be subset of the work.  Nothing concrete in the plan as far as I am aware.  I would recommend raising this issue in the Calico project ( https://github.com/projectcalico/calico ) - I think full integration with Calico and Calico data model is the preferred approach for this.

**Comment by rikatz** [comment]
Guys, about this issue:

Did we have had any evolution in this? 

Contiv does implements this using Openvswitch, but I think this is not the right way. Maybe setting this through 'tc command' is a good choice (and also, CoreOS have tc built in, as example!).

Thanks!

**Comment by caseydavenport** [comment]
Closing in favor of https://github.com/projectcalico/calico/issues/797
