### ISSUE TITLE
Document and test IPv6 support in calico-docker

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calicoctl#603]
Calico supports IPv6 but we don't do a very good job of explaining to users how to use it. Let's do a better job of documenting and testing it.
- [ ] `calicoctl node` can be run in IPv6 only mode (or v4 only or mixed) - should/does this just determine how bird shares routes?
- [ ] IPv6 can be used for talking to etcd (and/or IPv4?)
- [ ] containers can have 0 or more IPv4 and IPv6 addresses

Libnetwork support is "incomplete" - both at their end (e.g. https://github.com/docker/docker/issues/17666) and in our plugin so let's just focus on "default" networking for now.

**Comment by gunjan5** [comment]
should this be added to v1.0.0 milestone?

**Comment by caseydavenport** [comment]
Yeah, I think so.

This is actually two issues though.

- Documentation
- libnetwork missing support

**Comment by robbrockbank** [comment]
Opened a docs issue for docs - there is already a libnetwork =-plugin issue for this.  Do we need this issue open?

**Comment by tomdee** [comment]
So we have https://github.com/projectcalico/libnetwork-plugin/issues/72 for libnetwork-plugin
and https://github.com/projectcalico/calico/issues/227 for the docker libnetwork part of the docs.

But what about the other bits, e.g. can someone run Calico on an IPv6 only network - can they talk to etcd using IPv6? Can the bird instances talk to each other using IPv6? How do they configure it?

I don't think this is a v1.0.0 issue though - @caseydavenport can you remove it if you agree?

**Comment by caseydavenport** [comment]
Yeah, don't think this is v1.0.0.  

It's a shame we don't document better - I'd like to make this a priority after the next release.
