### ISSUE TITLE
Add timestamps to `calico/node` startup output

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calicoctl#826]
When running the `calico/node` container using a process manager like upstart or systemd, we don't produce timestamps in the output of `calicoctl node`.

This makes debugging in this case difficult.  We should at a minimum print a timestamp at the time the command is being run, perhaps behind a `--verbose` flag if we don't want to clutter the output for the non-managed case.

e.g:

```
core@calico-02 ~ $ sudo calicoctl node
No IP provided. Using detected IP: 172.18.18.102
Pulling Docker image calico/node:v0.16.1

Calico node is running with id: 66ef1bbc10f1d0648b74c3a4a0b72c491d92d4637a6ae31ff0146f48ffce6244
```

**Comment by tomdee** [comment]
See #737 too

**Comment by tomdee** [comment]
Worth noting that journalctl will add timestamps so I'm not sure why we need to add them too...

**Comment by caseydavenport** [comment]
The reasoning being that not all `calico/node` deployments will use systemd/journalctl.  Kubernetes self-hosted deployments being one example.

**Comment by caseydavenport** [comment]
Assigning to @2blesd2bstresd since this will be fixed up by his startup.go changes.
