### ISSUE TITLE
Using Calico with Azure

### ISSUE THREAD

**Issue by ghost** [projectcalico/calicoctl#949]
Will it be possible use Calico for building Kubernetes in Azure? I have not found any documentation on this. Under what circumstances, do we need to use --ipip mode? Does Azure need that?

Thanks.

**Comment by robbrockbank** [comment]
Hi @codefx9,

Azure don't support IPIP so it's not currently possible to use Calico on Azure.  However, we are working with the Azure team on a solution for this.  Keep an eye on this issue, and we'll update it with any developments.

**Comment by evan2645** [comment]
@robbrockbank any idea if the proposed solution will enable native non-IPIP operation on Azure, similar to an AWS VPC with instance Source/Dest checks disabled?

**Comment by matthewdupre** [comment]
For the time being people may want to use Calico policy with some other network (e.g. Flannel => Canal).

Assigning this to @lxpollitt because I think he might be more in touch with any Azure discussions.

**Comment by josephjacks** [comment]
Hi @robbrockbank - any new developments? We are seeing customers looking to use Calico on Azure.

**Comment by brendandburns** [comment]
Update, there are templates here:

https://github.com/Azure/acs-engine/pull/151

**Comment by frankgreco** [comment]
Could I get an explanation as to why this issue was closed? Was a native networking solution being implemented that didn't force you down the asc-engine path

**Comment by ozdanborne** [comment]
This is the top search result when googling "Calico azure". We should do a better job of explaining current azure support here.

**Comment by caseydavenport** [comment]
@ozdanborne sounds like we might need a doc [like this one](http://docs.projectcalico.org/v2.2/reference/public-cloud/aws) but for Azure.

**Comment by caseydavenport** [comment]
I think the status of this is:
- You can use Calico on Azure in policy-only mode for enforcing policy on top of Azure networking.
- Calico is integrated into acs-engine today.
- We're missing some documentation, which is covered here: https://github.com/projectcalico/calico/issues/220

**Comment by lwr20** [comment]
FYI, Calico now supports Azure using VXLAN encap.
https://docs.projectcalico.org/getting-started/kubernetes/self-managed-public-cloud/azure#calico-networking
