### ISSUE TITLE
Docker IpamDriver.RequestAddress error

### ISSUE THREAD

**Issue by hoppers99** [projectcalico/calicoctl#963]
Twice, after changing the pool using calicoctl (pool remove then pool add) redeployment of docker containers has begun to fail with the below message being logged.

```
I0504 14:52:35.785369 12610 exec.cpp:143] Version: 0.28.1
I0504 14:52:35.791190 12615 exec.cpp:217] Executor registered on slave 326bb85f-f572-4f9f-b22f-caa213a906ac-S1
docker: Error response from daemon: IpamDriver.RequestAddress: {
  "Err": ""
}.
```

Resolution attempts the first time covered:
- Restarting calico-node container
- Removing and re-adding the pool
- Restarting the agent

Eventually, I added a second pool and containers instantly started getting IP's assigned out of that range. Removal of the first pool then left things working on the new one.

On the second occasion, I found that: Adding any subnet that was within either the current one (removing the current one first) or in the previously broken range made no difference (including adding a /26 from the originally broken but since removed /24), but adding a new subnet that had not previously been used caused allocations to begin from that new range.

Running on CentOS 7 64bit on VMWare, with DCOS (open version) and containers being managed using Marathon

```
$ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64

$ calicoctl version
0.19.0
```

Happy to provide any additional detail 

calococtl diags: [diags-050516_130532.tar.gz](https://github.com/projectcalico/calico-containers/files/249819/diags-050516_130532.tar.gz)

journalctl -u docker.service --no-pager:  [docker.log.zip](https://github.com/projectcalico/calico-containers/files/249820/docker.log.zip)

**Comment by tomdee** [comment]
Hmmm, this has fallen through the cracks. I don't think kind/support is the best label here - it's either a bug or an enhancement, I'm pretty sure this is more than user error.

**Comment by caseydavenport** [comment]
@tomdee does this bug still apply?  We've since made significant changes to our libnetwork plugin (e.g porting to Go)
