### ISSUE TITLE
Node reboots causing calico node to fail to start due to clashing hostname

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calicoctl#967]
Had a couple of reports that after a node reboot the calico node is failing to restart due to a clashing hostname.

Prior to the reboot, the hostname used by calicoctl and stored in etcd was the short name.  After reboot, however, the hostname is fully qualified and therefore clashes with the existing entry in etcd.

Looks like it could be related to:
https://bugs.launchpad.net/cloud-init/+bug/1246485

Is this something we should try and workaround?

**Comment by heidecke** [comment]
On an unpatched host (CentOS 7.2 in this case), setting the hostname and fqdn with cloudinit causes this behavior.

Sample config:
```
#cloud-config
hostname: node-001
fqdn: node-001.example.com
```

**Comment by frostynova** [comment]
Also met this problem and I found there is no way unless `export HOSTNAME` in running `calicoctl node` bash to fix it. 

So maybe we can add a `calicoctl node rename` subcommand?

**Comment by caseydavenport** [comment]
Nodes can now be renamed using `calicoctl`.

Otherwise, this isn't a Calico issue, so I'm going to close this.
