### ISSUE TITLE
rkt calicoctl and systemd units

### ISSUE THREAD

**Issue by untoreh** [projectcalico/calicoctl#985]
- `--detach=false` should run rkt without systemd-run so that you can monitor the node from 1 unit file
- you should be able to specify rkt path and stage1 path

Or is it intended to work this way? And I have to use a full rkt command line inside a unit file?

**Comment by caseydavenport** [comment]
I think this is fixed in the [latest instructions for running Calico with rkt](http://docs.projectcalico.org/v2.2/getting-started/rkt/installation/manual#run-caliconode-and-configure-the-node)
